# Generated by guix-transfer
builtins.derivation {
  name = "pciutils-3.13.0.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/pq24yb7jw5rqgccsssvkk9n4lj9m1ri3-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/66alicjhn34r3fdisxzh1xvlkfhvllm9-module-import-compiled.nix).out}"
    "${builtins.path { name = ''pciutils-3.13.0.tar.zst-builder''; path = ./../sources/znr4lxkmz6yig257mcbr859yvas0hscs-pciutils-3.13.0.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "pciutils-hurd64.patch"; path = ./../sources/kkmzbc464y2kkbf5g9qh2817p0my4npf-pciutils-hurd64.patch; })
    (builtins.path { name = "pciutils-3.13.0.tar.zst-builder"; path = ./../sources/znr4lxkmz6yig257mcbr859yvas0hscs-pciutils-3.13.0.tar.zst-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 1))";
  __phantom_deps = "${(import ../store/gyhiimwajbnkd9myji0qfi40jhy7w9y2-xz-5.4.5.nix).out} ${(import ../store/y36mmg3s4zg7d4b1pnnpl70fkz9hd2s1-pciutils-3.13.0.tar.xz.nix).out} ${(import ../store/vpi87n22f8dbhvbwaqr470xp83hnbf1y-tar-1.35.nix).out} ${(import ../store/759rgw9c7j48gb1bv5fgr2sb3d9f5p1v-patch-2.7.6.nix).out} ${(import ../store/r2mqn9i7k9h1xzrx3jbihckz3lhymvpv-zstd-1.5.6.nix).out}";
}
