# Generated by guix-transfer
builtins.derivation {
  name = "zipbomb-docbook-xml-4.5.zip";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-Tk4DeiuDyYxslIGDkNS90/bhD27GLdeRiFlOJhkNx7Q=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/docbook-xml-4.5.zip/sha256/1d671lcjckjri28xfbf6dq7y3xnkppa910w1jin8rjc35dx06kjf";
}
