# Generated by guix-transfer
builtins.derivation {
  name = "uri-template-1.3.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-DgD462XhjH3iDVlaFDNunzN+rVgMcJNBQWJLbR/9rMc=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/uri-template-1.3.0.tar.gz/sha256/1ixczlgnsjv2850r6w0cb2npwcwzdqri8njr1pi7v371cpmzh00f";
}
