# Generated by guix-transfer
builtins.derivation {
  name = "docbook-xml-4.3.zip";
  system = "x86_64-linux";
  builder = "${(import ../store/0wsxd5g0xbxncz609bqq5hbg48hx8cpm-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/69fricvrgmnbmbm6hi7j08m4cvagza7h-module-import-compiled.nix).out}"
    "${builtins.path { name = ''docbook-xml-4.3.zip-builder''; path = ./../sources/ar70gr4pbf70ri798mfhpx75kf0ci9gh-docbook-xml-4.3.zip-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "docbook-xml-4.3.zip-builder"; path = ./../sources/ar70gr4pbf70ri798mfhpx75kf0ci9gh-docbook-xml-4.3.zip-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  preferLocalBuild = "1";
  __phantom_deps = "${(import ../store/46qp1slpy37dqaawsyhbdqgssw11rfz6-unzip-6.0.nix).out} ${(import ../store/42y0ld1r6byy7fdyk1j79hh7h65n4n4p-zipbomb-docbook-xml-4.3.zip.nix).out}";
}
