# Generated by guix-transfer
builtins.derivation {
  name = "guile-3.0.9.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-GiYlrHKyNm6VeS8/51j9Lfd1tARKkKSpeHMm5mwNdQ0=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/guile-3.0.9.tar.xz/sha256/03bm1mnfc9kkg2ls942a0js7bxrdzmcffgrgg6anwdmjfan2a9hs";
}
