# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://github.com/projectmallard/mallard-ducktype"; rev = "1.0.2"; hash = "sha256-jHjzTBBRBh//bOrdnyCRmZRmpupgDaDRuZGAd75baco="; name = "mallard-ducktype-1.0.2-checkout"; fetchSubmodules = false; }
