# Generated by guix-transfer
builtins.derivation {
  name = "bison-3.8.2.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-m7oCFMz38QecXVkhAEUie89hlRmEDr+oDNOEnP9aW/I=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/bison-3.8.2.tar.xz/sha256/1wjvbbzrr16k1jlby3l436an3kvv492h08arbnf0gwgprha05flv";
}
