# Generated by guix-transfer
builtins.derivation {
  name = "rust-ciborium-ll-0.2.2.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-V2Y7ZT2UijOL+z7rqbsv1fz67Lnhmeh+HtpNnoskD9k=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-ciborium-ll-0.2.2.tar.gz/sha256/1n8g4j5rwkfs3rzfi6g1p7ngmz6m5yxsksryzf5k72ll7mjknrjp";
}
