# Generated by guix-transfer
builtins.derivation {
  name = "rust-doc-comment-0.3.3.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-/qQbujLZabUTmXdSc1YFBUvA36krTFa/EYny4XS+ehA=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/doc-comment/0.3.3/download";
}
