# Generated by guix-transfer
builtins.derivation {
  name = "typeguard-4.4.4.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-On/S3/twXU0O+u1DBqcEyJud7oULaI8GCosWFaeeX3Q=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://files.pythonhosted.org/packages/source/t/typeguard/typeguard-4.4.4.tar.gz";
}
