# Generated by guix-transfer
builtins.derivation {
  name = "rust-unarray-0.1.4.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-6uqFszTbWD/jJ00StM0YgAMr6rQJwNd0vgRNRICrmpQ=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-unarray-0.1.4.tar.gz/sha256/154smf048k84prsdgh09nkm2n0w0336v84jd4zikyn6v6jrqbspa";
}
