# Generated by guix-transfer
builtins.derivation {
  name = "rust-cargo-options-0.7.5.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-dIjkFXhpHPJqpcjszRg8sxdS/LaLnFseiOZyeoPHgXE=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-cargo-options-0.7.5.tar.gz/sha256/0wc1qy1plwp6i0g5p74bnvy545xk7hccvv68lmmg4739g0ay923l";
}
