# Generated by guix-transfer
builtins.derivation {
  name = "libsoup-2.74.3.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-5Ld8Qc/EyMWgNfzcMgx7xs+3XvfFoDQVPfFBP6HZLxM=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://download.gnome.org/sources/libsoup/2.74/libsoup-2.74.3.tar.xz";
}
