# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://github.com/openexr/openexr"; rev = "v2.5.7"; hash = "sha256-yBDSLTESNsS7irw1yt06FoDJKlsWcYKC5aExGlcGSu4="; name = "ilmbase-2.5.7-checkout"; fetchSubmodules = false; }
