# Generated by guix-transfer
builtins.derivation {
  name = "httpbin-0.10.2.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-YyFIaYJhyGhOotK2JM3qhFtAKx/pFzbonfiGQIxjF6k=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/httpbin-0.10.2.tar.gz/sha256/1a8pcf6411pqkpl3c5z93wml0nw4xb6j9dnjl976ij31h9llh8b3";
}
