# Generated by guix-transfer
builtins.derivation {
  name = "wget-1.25.0.tar.lz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-GSJcx1awoIj8gRSNxqQKDI8ymvf9hIPxx7L+UPTgih8=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://ftp.gnu.org/gnu/wget/wget-1.25.0.tar.lz";
}
