# Generated by guix-transfer
builtins.derivation {
  name = "rust-slab-0.4.9.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-j5Kklvt2a0F8mWucXlfa8vetOwvr4cz8pIVjkOPTu2c=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/slab/0.4.9/download";
}
