# Generated by guix-transfer
builtins.derivation {
  name = "rust-fs4-0.12.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-wpwwaEQYVH1HbwtI6E9IIWORGcSDsezNVmyM0M0F9SE=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-fs4-0.12.0.tar.gz/sha256/08gm0p6x133cav6yrcc3qhcr2qr1917yhj0bdx3psm0q8il31762";
}
