# Generated by guix-transfer
builtins.derivation {
  name = "gcc-mesboot-wrapper-4.9.4";
  system = "x86_64-linux";
  builder = "${(import ../store/xxpwmhk6fpk8c3x18vrz1yfzh1bvppm5-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import''; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; }}"
    "-C"
    "${(import ../store/g1g9hl4rdrinpkr04d79w724bld8biiv-module-import-compiled.nix).out}"
    "${builtins.path { name = ''gcc-mesboot-wrapper-4.9.4-builder''; path = ./../sources/94v4aw9xwraww6dgkf7a4a20mkksz784-gcc-mesboot-wrapper-4.9.4-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import"; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; })
    (builtins.path { name = "gcc-mesboot-wrapper-4.9.4-builder"; path = ./../sources/94v4aw9xwraww6dgkf7a4a20mkksz784-gcc-mesboot-wrapper-4.9.4-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/p4isigdja4ixm0qhrwi6jm37f8r9rwqy-gcc-mesboot-4.9.4.nix).out} ${(import ../store/mncciknsffbxrwgdr9ryhg42ilp90842-glibc-mesboot-2.16.0.nix).out} ${(import ../store/6xj20c1k9jiprxqs2g3vv334szmnl30c-gash-utils-boot-0.2.0.nix).out} ${(import ../store/b2s1388ivb74nxs8cz71wcijdhs5d5qs-gash-boot-0.3.1.nix).out}";
}
