# Generated by guix-transfer
builtins.derivation {
  name = "automake-1.17.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/hn59viz2gmjdjjikmjmmlf5lnnp4wzn1-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/nnjrv59xc0zvampmfnv1xac2gk3f8ffp-module-import-compiled.nix).out}"
    "${builtins.path { name = ''automake-1.17.tar.zst-builder''; path = ./../sources/n1cmszzwlnd9yhjwiryc62j898mnw3vc-automake-1.17.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "automake-skip-amhello-tests.patch"; path = ./../sources/5qd96kxzi9rhl2j3hzkpwk1zhbxv9g46-automake-skip-amhello-tests.patch; })
    (builtins.path { name = "automake-1.17.tar.zst-builder"; path = ./../sources/n1cmszzwlnd9yhjwiryc62j898mnw3vc-automake-1.17.tar.zst-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 1))";
  __phantom_deps = "${(import ../store/qkdakgwyj3w8ppa95g3gp3rx6if2bbsp-automake-1.17.tar.xz.nix).out} ${(import ../store/h9ys9ff47zjq8g6glpw9vckvjszbid19-xz-5.4.5.nix).out} ${(import ../store/6mcsn3vji1fs82g0jlksppd7nwiyzk0x-tar-1.35.nix).out} ${(import ../store/ix63qg734rsvk1jafvk2d9f83nhssk1a-patch-2.7.6.nix).out} ${(import ../store/sq6pj4hf188957l7vjnc38lavkpcj4pl-zstd-1.5.6.nix).out}";
}
