# Generated by guix-transfer
builtins.derivation {
  name = "rust-fdeflate-0.3.7.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-HmhTtSZJ1KxcC9AjIM3cW6lWvbQHxLdaLGt1v1FQD4w=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-fdeflate-0.3.7.tar.gz/sha256/130ga18vyxbb5idbgi07njymdaavvk6j08yh1dfarm294ssm6s0y";
}
