# Generated by guix-transfer
builtins.derivation {
  name = "rust-similar-2.7.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-u7tdllkUFkauZHtC/glNr2xhktFiCHC0SdlVf3SLLao=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-similar-2.7.0.tar.gz/sha256/1aidids7ymfr96s70232s6962v5g9l4zwhkvcjp4c5hlb6b5vfxv";
}
