# Generated by guix-transfer
builtins.derivation {
  name = "pexpect-4.9.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-7n1BEj88mREFDqLC2sEHVo3EOy07DHVXozISw5jq0w8=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/pexpect-4.9.0.tar.gz/sha256/03ykxacc64ijldbpa31v5lxw93an0z0xmhm21q2i369w7w942zgf";
}
