# Generated by guix-transfer
builtins.derivation {
  name = "glibc-utf8-locales-2.41";
  system = "x86_64-linux";
  builder = "${(import ../store/c4ay50vfyk7bxiiy4gzz8wp6d6b9qfay-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/7skwz4rdpxxc3s03vb07mqvpxr8s6j1h-module-import-compiled.nix).out}"
    "${builtins.path { name = ''glibc-utf8-locales-2.41-builder''; path = ./../sources/im4d0c0hsa875fcbnp6vs25kdg2fl8pp-glibc-utf8-locales-2.41-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "glibc-utf8-locales-2.41-builder"; path = ./../sources/im4d0c0hsa875fcbnp6vs25kdg2fl8pp-glibc-utf8-locales-2.41-builder; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/424mrddaf4aiwpisixqxj3jnbjvihzpl-glibc-2.41.nix).out} ${(import ../store/mgli9qik2kx4fa0d0w3ilsaay00haw59-gzip-1.14.nix).out} ${(import ../store/vz33hm7r8nx8q12kgmgbzrcbp0y2cqmy-linux-libre-headers-6.12.17.nix).out}";
}
