# Generated by guix-transfer
builtins.derivation {
  name = "Parse-Yapp-1.21.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-OBDpmDCPui4PTyYEMDUDKwJ85RzlyKUqi440DKZfE+U=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://www.cpan.org/authors/id/W/WB/WBRASWELL/Parse-Yapp-1.21.tar.gz";
}
