# Generated by guix-transfer
builtins.derivation {
  name = "rust-rand-chacha-0.3.1.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-5sEKY6D6MiUr5J0h53CdTUuvjSMcLbzh6qgUG5sSfYg=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-rand-chacha-0.3.1.tar.gz/sha256/123x2adin558xbhvqb8w4f6syjsdkmqff8cxwhmjacpsl1ihmhg6";
}
