# Generated by guix-transfer
builtins.derivation {
  name = "rustc-1.74.0-src.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-iCtYS8Mhxdz+d82qafJ3kGuTYlXveAj81cdJKSXPEEk=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://static.rust-lang.org/dist/rustc-1.74.0-src.tar.gz";
}
