# Generated by guix-transfer
builtins.derivation {
  name = "rust-plotters-backend-0.3.7.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-30LhPBKVihaz9/Q4a5qx8+eTORTs6kjacTlDUmOkFyo=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-plotters-backend-0.3.7.tar.gz/sha256/0ahpliim4hrrf7d4ispc2hwr7rzkn6d6nf7lyyrid2lm28yf2hnz";
}
