# Generated by guix-transfer
builtins.derivation {
  name = "rust-pin-utils-0.1.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-i4cNjBUbby+5PoShMUYTjwXQLtEcfnxU+IJqqvfJ8YQ=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-pin-utils-0.1.0.tar.gz/sha256/117ir7vslsl2z1a7qzhws4pd01cg2d3338c47swjyvqv2n60v1wb";
}
