# Generated by guix-transfer
builtins.derivation {
  name = "rust-log-0.4.27.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-E9wt81HjICeDof4NRDdfcpX/tASSZ7DzAYNG3BIqHZQ=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-log-0.4.27.tar.gz/sha256/150x589dqil307rv0rwj0jsgz5bjbwvl83gyl61jf873a7rjvp0k";
}
