# Generated by guix-transfer
builtins.derivation {
  name = "libunistring-1.3.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-8kV4bIMdJRUPPftDF82hrMXj95pdpK0HPdyliIZWlSc=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://ftp.gnu.org/gnu/libunistring/libunistring-1.3.tar.xz";
}
