# Generated by guix-transfer
builtins.derivation {
  name = "rust-libredox-0.1.3.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-wP83vVkMolBj41r3RcNDy3oCcZBvt7N+SBPo958AJo0=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/libredox/0.1.3/download";
}
