# Generated by guix-transfer
builtins.derivation {
  name = "rust-wasm-bindgen-shared-0.2.100.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-GgXXO5M6hH1szN2o+DiiL/EBrZv5PjNoTznB9fDuzj0=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-wasm-bindgen-shared-0.2.100.tar.gz/sha256/0gffxvqgbh9r9xl36gprkfnh3w9gl8wgia6xrin7v11sjcxxf18s";
}
