# Generated by guix-transfer
builtins.derivation {
  name = "elementpath-5.0.4.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-he2TVl1ulK76FgsS82sSy+S+a/m73ga4DyxclIKaJfs=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/elementpath-5.0.4.tar.gz/sha256/1yr5ka198p1c1yw0dpmvz5mvxr6b29mz64hb2vxax53fbmb97vc5";
}
