# Generated by guix-transfer
builtins.derivation {
  name = "rust-malloc-buf-0.0.6.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-YruQf+iNVNjZzjKjzOq0IY7S9rfTVhfK/prfhOQ5Gcs=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-malloc-buf-0.0.6.tar.gz/sha256/1jqr77j89pwszv51fmnknzvd53i1nkmcr8rjrvcxhm4dx1zr1fv2";
}
