# Generated by guix-transfer
builtins.derivation {
  name = "texlive-metafont-2025.2-checkout";
  system = "x86_64-linux";
  builder = "${(import ../store/pq24yb7jw5rqgccsssvkk9n4lj9m1ri3-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import''; path = ./../sources/l9qrfq20vvrf1r54k0fr7xds1f9dlqmk-m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import; }}"
    "-L"
    "${(import ../store/6mck8fp83ybv03b7dxya714l3fdnn4cp-guile-json-4.7.3.nix).out}/share/guile/site/3.0"
    "-L"
    "${(import ../store/fsk3sj51w8mwrnh3g62h07nxhzvjn48f-guile-gnutls-5.0.1.nix).out}/share/guile/site/3.0"
    "-L"
    "${(import ../store/2xh860c4p4347d8y8a9w36hmlhvl29pf-guile-lzlib-0.3.0.nix).out}/share/guile/site/3.0"
    "-C"
    "${(import ../store/s2iv51rnw5fl3jrnsm9n86y38fgaqhk9-module-import-compiled.nix).out}"
    "-C"
    "${(import ../store/6mck8fp83ybv03b7dxya714l3fdnn4cp-guile-json-4.7.3.nix).out}/lib/guile/3.0/site-ccache"
    "-C"
    "${(import ../store/fsk3sj51w8mwrnh3g62h07nxhzvjn48f-guile-gnutls-5.0.1.nix).out}/lib/guile/3.0/site-ccache"
    "-C"
    "${(import ../store/2xh860c4p4347d8y8a9w36hmlhvl29pf-guile-lzlib-0.3.0.nix).out}/lib/guile/3.0/site-ccache"
    "${builtins.path { name = ''svn-multi-download''; path = ./../sources/sncvp7xxnhhxrzx5ysf4vipcgn96bplq-svn-multi-download; }}"
  ];
  srcs = [
    (builtins.path { name = "svn-multi-download"; path = ./../sources/sncvp7xxnhhxrzx5ysf4vipcgn96bplq-svn-multi-download; })
    (builtins.path { name = "m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import"; path = ./../sources/l9qrfq20vvrf1r54k0fr7xds1f9dlqmk-m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import; })
  ];
  outputHash = "sha256-enliZEtUXi2yFap/1G7vb4QD7dbr8rxe6xOyv8NsjRM=";
  outputHashAlgo = "sha256";
  outputHashMode = "recursive";
  hash = "122,121,98,100,75,84,94,45,178,21,170,127,212,110,239,111,132,3,237,214,235,242,188,94,235,19,178,191,195,108,141,19";
  impureEnvVars = "http_proxy https_proxy LC_ALL LC_MESSAGES LANG COLUMNS";
  preferLocalBuild = "1";
  "svn locations" = "(\"doc/man/man1/inimf.1\" \"doc/man/man1/inimf.man1.pdf\" \"doc/man/man1/mf-nowin.1\" \"doc/man/man1/mf-nowin.man1.pdf\" \"doc/man/man1/mf.1\" \"doc/man/man1/mf.man1.pdf\" \"metafont/base/\" \"metafont/config/\" \"metafont/misc/\")";
  "svn revision" = "74725";
  "svn url" = "svn://www.tug.org/texlive/tags/texlive-2025.2/Master/texmf-dist";
  __phantom_deps = "${(import ../store/fsk3sj51w8mwrnh3g62h07nxhzvjn48f-guile-gnutls-5.0.1.nix).debug} ${(import ../store/aya7s19lzhq96588fnd4hhbn858g0jkl-gzip-1.14.nix).out} ${(import ../store/ias0rvxiq1wnkqmbg111r8lkng6iy4jl-tar-1.35.nix).out} ${(import ../store/nc349a1nlybhrjdnnwz54kh960ymsh2z-subversion-1.14.5.nix).out}";
}
