# Generated by guix-transfer
builtins.derivation {
  name = "Linux-PAM-1.5.2.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-5OxxMakdpEUSV0Jo9JPG2MoQXIcJFpG46bVspoXU+U0=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/Linux-PAM-1.5.2.tar.xz/sha256/0kgrsj2scv5mx6w925h9hxf11jnqqs9z8s22aw94b90xm4qp3v74";
}
