# Generated by guix-transfer
builtins.derivation {
  name = "setuptools-80.9.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-82tHQC7N52jb+vxG6OQge0NgxlTx87uER18KKGKPsZw=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/setuptools-80.9.0.tar.gz/sha256/175iixi2h2jz8y2bpwziak360hvv43jfhipwzbdniryd5r04fszk";
}
