# Generated by guix-transfer
builtins.derivation {
  name = "rust-crossbeam-channel-0.5.15.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-grj4+GizaWf5YGeQ0ZA1cN6c6vhwp7+fu9MBbWNqLLI=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/crossbeam-channel/0.5.15/download";
}
