# Generated by guix-transfer
builtins.derivation {
  name = "tdb-1.4.12.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-bOSydJiBLQkjfs5loNbfrAlBYQ5wmEjsuCKqJBCEzXo=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://www.samba.org/ftp/tdb/tdb-1.4.12.tar.gz";
}
