# Generated by guix-transfer
builtins.derivation {
  name = "boost-0001-unordered-fix-copy-assign.patch";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-xuBEKfvxYp8Q9FbUfZz9oaicSx8kJmXLTAkc2EsNRiY=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/boost-0001-unordered-fix-copy-assign.patch/sha256/09j61m5xh7099k5na9i43x5rra51znf7vm2nyh89yqpizcll9q66";
}
