# Generated by guix-transfer
builtins.derivation {
  name = "readline82-004";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-eVcu6uuCr9xoadetTLqdT1GbEhgHDhf6kLvs1JvVJaw=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/readline82-004/sha256/1b15sndx9v5vj3x1f3h73099nlagknx4rbfpd5ldrbw2xgm2wmvr";
}
