# Generated by guix-transfer
builtins.derivation {
  name = "libunwind-static-arm";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-+EE64AcHsai8852TU+Z7lyPIy/MuzIkhY9cHw2NdY8o=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://raw.githubusercontent.com/JuliaLang/julia/v1.8.2/deps/patches/libunwind-static-arm.patch";
}
