# Generated by guix-transfer
builtins.derivation {
  name = "rust-futures-timer-3.0.3.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-8oiwpPIPmla10dpX4iJ8Zht7FhaOL3I2X1e2MybimyQ=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/futures-timer/3.0.3/download";
}
