# Generated by guix-transfer
builtins.derivation {
  name = "rust-derivative-2.2.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-/MPdXp6cCyldbh5NgR+28VfV/9eEuNIC/GLqyANadws=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-derivative-2.2.0.tar.gz/sha256/02vpb81wisk2zh1d5f44szzxamzinqgq2k8ydrfjj2wwkrgdvhzw";
}
