# Generated by guix-transfer
builtins.derivation {
  name = "rust-miniz-oxide-0.8.7.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-/3DOPkiuQ/oHWGPO9i6LQ7caTyOCIpkg4N82JZKRlDA=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-miniz-oxide-0.8.7.tar.gz/sha256/0c4lj692adnzw0h9j8l24d7imds3icpgdkk3b03zlhxf90zcww7z";
}
