# Generated by guix-transfer
builtins.derivation {
  name = "ruby-hydra-minimal-0.0-0.5abfa37";
  system = "x86_64-linux";
  builder = "${(import ../store/pq24yb7jw5rqgccsssvkk9n4lj9m1ri3-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''pyx18y48b2awppb6lv9p0k5mj5rr0jx7-module-import''; path = ./../sources/i124nf2qpnj5f9fzg4c0jqiw0pilvwg1-pyx18y48b2awppb6lv9p0k5mj5rr0jx7-module-import; }}"
    "-C"
    "${(import ../store/vf6vc4s7l34zl29kipplkka0r6zj4wir-module-import-compiled.nix).out}"
    "${builtins.path { name = ''ruby-hydra-minimal-0.0-0.5abfa37-builder''; path = ./../sources/qvq2zbrzqpqlc2ws7v59r9yvfw0n6mxv-ruby-hydra-minimal-0.0-0.5abfa37-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "ruby-hydra-minimal-0.0-0.5abfa37-builder"; path = ./../sources/qvq2zbrzqpqlc2ws7v59r9yvfw0n6mxv-ruby-hydra-minimal-0.0-0.5abfa37-builder; })
    (builtins.path { name = "pyx18y48b2awppb6lv9p0k5mj5rr0jx7-module-import"; path = ./../sources/i124nf2qpnj5f9fzg4c0jqiw0pilvwg1-pyx18y48b2awppb6lv9p0k5mj5rr0jx7-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/9cfyiki77cb1mllyxxs1ixy33bm1214j-gcc-14.3.0.nix).out} ${(import ../store/gyhiimwajbnkd9myji0qfi40jhy7w9y2-xz-5.4.5.nix).out} ${(import ../store/rbhimv41bbbkz2kniak22fyyps9mydsb-glibc-2.41.nix).out} ${(import ../store/1hcljqw9cly8x9bjf1gpfgzi7ywznc04-file-5.46.nix).out} ${(import ../store/svxillvi9y908w6l6x65dwxxfaxx0ycv-bash-minimal-5.2.37.nix).out} ${(import ../store/08bq32vfm5vz5x0q3f59p8rchaacbcgb-gzip-1.14.nix).out} ${(import ../store/7q3s1hw0ypig963xf2hq7wjv7n5pi1gm-gawk-5.3.0.nix).out} ${(import ../store/7k1lnisy7ni10jhg255wccyajn1jxlbx-ld-wrapper-0.nix).out} ${(import ../store/jaljxxzhxhhhnyryiz0rnclg2v4cfkwi-ruby-2.7.8.nix).out} ${(import ../store/vpi87n22f8dbhvbwaqr470xp83hnbf1y-tar-1.35.nix).out} ${(import ../store/cr6hjki7qzkg039lwrgyqz0wfyknxkb2-linux-libre-headers-6.12.17.nix).out} ${(import ../store/kcaqm2akaszy6501lgjmi1syk6mmn6ix-coreutils-9.1.nix).out} ${(import ../store/asynp6xqahcq9rb7kd57n3ixak0vzglk-ruby-hydra-minimal-0.0-0.5abfa37-checkout.nix).out} ${(import ../store/6rnjjw6cwrasz8x7ha2ksiz370ffyj0g-binutils-2.44.nix).out} ${(import ../store/m0hczqciprwc7vsdhgrayc7iacxi8vnl-bzip2-1.0.8.nix).out} ${(import ../store/rf1bk37xg9sxcxa27rsp5720jcf10vzk-make-4.4.1.nix).out} ${(import ../store/739qrmpdy457iqwyg34px0snh2y86zxm-diffutils-3.12.nix).out} ${(import ../store/j6wynqb22667xfacixfmrnzdjybssszz-grep-3.11.nix).out} ${(import ../store/759rgw9c7j48gb1bv5fgr2sb3d9f5p1v-patch-2.7.6.nix).out} ${(import ../store/r2mqn9i7k9h1xzrx3jbihckz3lhymvpv-zstd-1.5.6.nix).out} ${(import ../store/y5b1z1lgkbs35ny3f0k6ydx7vqykdzk8-sed-4.9.nix).out} ${(import ../store/qv8g7l8fhnjh87bkzpg7giivw08ib3nd-findutils-4.10.0.nix).out} ${(import ../store/jqcih2q3wxxgn8jklwqq700kx8hn9427-zlib-1.3.1.nix).out} ${(import ../store/rbhimv41bbbkz2kniak22fyyps9mydsb-glibc-2.41.nix).static}";
}
