# Generated by guix-transfer
builtins.derivation {
  name = "rust-crossbeam-epoch-0.9.18.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-W4KsSjwsqcNGCWTwIOFALt1XU0EddzeqOcNxStG1Qg4=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-crossbeam-epoch-0.9.18.tar.gz/sha256/03j2np8llwf376m3fxqx859mgp9f83hj1w34153c7a9c7i5ar0jv";
}
