# Generated by guix-transfer
builtins.derivation {
  name = "libunwind-prefer-extbl";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-GVHNpUQ3lcX643kp39dLVjXeg2SOTGqQxZX2b7Cmw10=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/libunwind-prefer-extbl/sha256/0pf3lsq6zxlmqn86lk4fcj1xwdan9gbxyabrwgxcb59p8jjwsl8r";
}
