# Generated by guix-transfer
builtins.derivation {
  name = "findutils-4.10.0.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/0wsxd5g0xbxncz609bqq5hbg48hx8cpm-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/69fricvrgmnbmbm6hi7j08m4cvagza7h-module-import-compiled.nix).out}"
    "${builtins.path { name = ''findutils-4.10.0.tar.zst-builder''; path = ./../sources/z85sr5im8w3hnmpmj902jq7af985gqn8-findutils-4.10.0.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "findutils-localstatedir.patch"; path = ./../sources/xn0wb7d2k1v2yjkby7x885w77vfsdxjm-findutils-localstatedir.patch; })
    (builtins.path { name = "findutils-4.10.0.tar.zst-builder"; path = ./../sources/z85sr5im8w3hnmpmj902jq7af985gqn8-findutils-4.10.0.tar.zst-builder; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 1))";
  __phantom_deps = "${(import ../store/fl18v8zafk6wpc2yqxrahapqw7l7n073-xz-5.4.5.nix).out} ${(import ../store/xfi7v5bnbj9mfr8nycx75yj9zx5dnpsm-findutils-4.10.0.tar.xz.nix).out} ${(import ../store/pv1ibrv4pc1km18w8i0iiwklhpn6h9lc-tar-1.35.nix).out} ${(import ../store/q8sb66r0q7l58drjj8wdqlf2808abkar-patch-2.7.6.nix).out} ${(import ../store/f60dfz81yizjj1j5x7pzdcmmhc38yr1v-zstd-1.5.6.nix).out}";
}
