# Generated by guix-transfer
builtins.derivation {
  name = "openssl-3.0.8.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/sgnxvqlfbjdjmxy7k28xvkvbn9kslr42-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/fyk8kj0y0gh4mgxa3hxb6nf5y8pgjjps-module-import-compiled.nix).out}"
    "${builtins.path { name = ''openssl-3.0.8.tar.zst-builder''; path = ./../sources/92xlzvpngz95hbf8w30yfrwadx53hkyd-openssl-3.0.8.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "openssl-3.0.8.tar.zst-builder"; path = ./../sources/92xlzvpngz95hbf8w30yfrwadx53hkyd-openssl-3.0.8.tar.zst-builder; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "openssl-3.0-c-rehash-in.patch"; path = ./../sources/71k1d3pd616m10qywnr4lv4zw94ankcp-openssl-3.0-c-rehash-in.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 1))";
  __phantom_deps = "${(import ../store/n1i0fxp66k7acj2dg4jnsahczkvmqlsx-zstd-1.5.6.nix).out} ${(import ../store/amz4fdcmpiw99rhcvbkckmbjrk8dxdrg-gzip-1.14.nix).out} ${(import ../store/2y6bgirwmqfqj1x0chrh4yx6v56mpcva-patch-2.7.6.nix).out} ${(import ../store/j6zi7idf8wj9al9b9z5lwdmc3ms0kp5f-xz-5.4.5.nix).out} ${(import ../store/fa2kg40vfbixad74wdqp8mk3hdf55r7d-tar-1.35.nix).out} ${(import ../store/83h6ihm240dq5m1ha0i15h0lj5w9kbsj-openssl-3.0.8.tar.gz.nix).out}";
}
