# Generated by guix-transfer
builtins.derivation {
  name = "make-boot0-4.4.1";
  system = "x86_64-linux";
  builder = "${(import ../store/3sgvmyxar0bp0r707sgivngr256jlw8k-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import''; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; }}"
    "-C"
    "${(import ../store/f1pxw9ip8s5g4ka338rz03kza9ip49mz-module-import-compiled.nix).out}"
    "${builtins.path { name = ''make-boot0-4.4.1-builder''; path = ./../sources/7ayrxgr2x8gwgf0q06m0338a4ai0l7cr-make-boot0-4.4.1-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import"; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; })
    (builtins.path { name = "make-boot0-4.4.1-builder"; path = ./../sources/7ayrxgr2x8gwgf0q06m0338a4ai0l7cr-make-boot0-4.4.1-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/gfpvgsvc1ybh204xmv63g6js4ql0cn7h-gcc-mesboot-4.9.4.nix).out} ${(import ../store/9xcq8cvgs76cz1qsrmgnhyx25glz9m49-coreutils-mesboot-9.1.nix).out} ${(import ../store/3z41km14vl4iwll9nz0nayrn9x1r8n9d-bash-mesboot-5.2.37.nix).out} ${(import ../store/lr9ya21fn56knxaamc7wqds2c4valcfb-patch-mesboot-2.5.9.nix).out} ${(import ../store/i5nxf74jcqxslj812zr1iim2yj813sv3-glibc-mesboot-2.16.0.nix).out} ${(import ../store/nh69aqrp9g4h7y4dzpff2sbymgv10c3z-gawk-mesboot-3.1.8.nix).out} ${(import ../store/x2pmbrya5z47p67wq4g4p0hz65nzspmk-grep-mesboot-3.11.nix).out} ${(import ../store/gz6n0z0vj0phxgcdxdjdlyjficdmnjxl-make-4.4.1.tar.xz.nix).out} ${(import ../store/gvvzwfdbb0nqnzj2knggj53cxqhc9fsn-gzip-mesboot-1.2.4.nix).out} ${(import ../store/a7999q8jd8qp3402j5cvl699mw75k1z8-gcc-mesboot-wrapper-4.9.4.nix).out} ${(import ../store/pa53m4v2xxzv6q5akyj2f37m1v32lxlq-make-mesboot-3.82.nix).out} ${(import ../store/n9ylp3zqzp31193s0xspy9vpnk9rjc3s-xz-mesboot-5.4.5.nix).out} ${(import ../store/x48vkd7jd2s317c8v0nrj7vrwhnc0pp8-sed-mesboot-4.8.nix).out} ${(import ../store/yy3fsc6mia1p218fhx0vwwjljc0c8hy7-tar-mesboot-1.35.nix).out} ${(import ../store/gdhpfbbyzmg9kkfkdz104k86l3jjxxh8-binutils-mesboot-2.20.1a.nix).out}";
}
