# Generated by guix-transfer
builtins.derivation {
  name = "uri-template-1.3.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-DgD462XhjH3iDVlaFDNunzN+rVgMcJNBQWJLbR/9rMc=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://files.pythonhosted.org/packages/source/u/uri-template/uri-template-1.3.0.tar.gz";
}
