# Generated by guix-transfer
builtins.derivation {
  name = "rust-icu-normalizer-1.5.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-Gc4+DaLsaFmdGTyT0IgULv1/nF1vybgDd0hVdH3GqE8=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-icu-normalizer-1.5.0.tar.gz/sha256/0kx8qryp8ma8fw1vijbgbnf7zz9f2j4d14rw36fmjs7cl86kxkhr";
}
