# Generated by guix-transfer
builtins.derivation {
  name = "xdgmime-0.0-2.1792967-checkout";
  system = "x86_64-linux";
  builder = "builtin:git-download";
  outputHash = "sha256-9ecbSEcUgrYWRN9eF5Ill7/kkuJqSBo6viLyOiledxE=";
  outputHashAlgo = "sha256";
  outputHashMode = "recursive";
  commit = "179296748e92bd91bf531656632a1056307fb7b7";
  impureEnvVars = "http_proxy https_proxy LC_ALL LC_MESSAGES LANG COLUMNS";
  preferLocalBuild = "1";
  "recursive?" = "#f";
  url = "\"https://gitlab.freedesktop.org/xdg/xdgmime.git\"";
}
