# Generated by guix-transfer
builtins.derivation {
  name = "autoconf-2.69.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-ZOvOyfisWySHElqGp3YNJZGsnh09vVlIljP53mKldoQ=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/autoconf-2.69.tar.xz/sha256/113nlmidxy9kjr45kg9x3ngar4951mvag1js2a3j8nxcz34wxsv4";
}
