# Generated by guix-transfer
builtins.derivation {
  name = "texlive-epstopdf-2025.2-checkout";
  system = "x86_64-linux";
  builder = "${(import ../store/c4ay50vfyk7bxiiy4gzz8wp6d6b9qfay-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import''; path = ./../sources/l9qrfq20vvrf1r54k0fr7xds1f9dlqmk-m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import; }}"
    "-L"
    "${(import ../store/c2gkblz7ldljj3c5hais6rsil0gvds6g-guile-json-4.7.3.nix).out}/share/guile/site/3.0"
    "-L"
    "${(import ../store/cvqbmc0pjkzrc7792s9m6a5z11anldqw-guile-gnutls-5.0.1.nix).out}/share/guile/site/3.0"
    "-L"
    "${(import ../store/yh4j343fbv1jgh126adkw6cypc538in5-guile-lzlib-0.3.0.nix).out}/share/guile/site/3.0"
    "-C"
    "${(import ../store/zcspj822jiimswyrxcq47p0ksnqfag58-module-import-compiled.nix).out}"
    "-C"
    "${(import ../store/c2gkblz7ldljj3c5hais6rsil0gvds6g-guile-json-4.7.3.nix).out}/lib/guile/3.0/site-ccache"
    "-C"
    "${(import ../store/cvqbmc0pjkzrc7792s9m6a5z11anldqw-guile-gnutls-5.0.1.nix).out}/lib/guile/3.0/site-ccache"
    "-C"
    "${(import ../store/yh4j343fbv1jgh126adkw6cypc538in5-guile-lzlib-0.3.0.nix).out}/lib/guile/3.0/site-ccache"
    "${builtins.path { name = ''svn-multi-download''; path = ./../sources/sncvp7xxnhhxrzx5ysf4vipcgn96bplq-svn-multi-download; }}"
  ];
  srcs = [
    (builtins.path { name = "svn-multi-download"; path = ./../sources/sncvp7xxnhhxrzx5ysf4vipcgn96bplq-svn-multi-download; })
    (builtins.path { name = "m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import"; path = ./../sources/l9qrfq20vvrf1r54k0fr7xds1f9dlqmk-m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import; })
  ];
  outputHash = "sha256-W7VaGHej0hAdV+i5WN4ux+qbjHHzy/srdDglp44O49w=";
  outputHashAlgo = "sha256";
  outputHashMode = "recursive";
  hash = "91,181,90,24,119,163,210,16,29,87,232,185,88,222,46,199,234,155,140,113,243,203,251,43,116,56,37,167,142,14,227,220";
  impureEnvVars = "http_proxy https_proxy LC_ALL LC_MESSAGES LANG COLUMNS";
  preferLocalBuild = "1";
  "svn locations" = "(\"doc/man/man1/epstopdf.1\" \"doc/man/man1/epstopdf.man1.pdf\" \"doc/man/man1/repstopdf.1\" \"doc/man/man1/repstopdf.man1.pdf\" \"doc/support/epstopdf/\" \"scripts/epstopdf/\")";
  "svn revision" = "74725";
  "svn url" = "svn://www.tug.org/texlive/tags/texlive-2025.2/Master/texmf-dist";
  __phantom_deps = "${(import ../store/cvqbmc0pjkzrc7792s9m6a5z11anldqw-guile-gnutls-5.0.1.nix).debug} ${(import ../store/krbriqmrrydjbprcasbx5qgvmwxgylwm-gzip-1.14.nix).out} ${(import ../store/dafhznysnlnqbjvnhb4gbby26r5pn3n2-tar-1.35.nix).out} ${(import ../store/27l1shfiksw4413z2bwb72wxa1n5zbfh-subversion-1.14.5.nix).out}";
}
