# Generated by guix-transfer
builtins.derivation {
  name = "net-base-5.3";
  system = "x86_64-linux";
  builder = "${(import ../store/hn59viz2gmjdjjikmjmmlf5lnnp4wzn1-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/nnjrv59xc0zvampmfnv1xac2gk3f8ffp-module-import-compiled.nix).out}"
    "${builtins.path { name = ''net-base-5.3-builder''; path = ./../sources/k8ld3ywg6pqfbmrshclki3i4k29cpc14-net-base-5.3-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "net-base-5.3-builder"; path = ./../sources/k8ld3ywg6pqfbmrshclki3i4k29cpc14-net-base-5.3-builder; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/xszrqvdmg6hybxf84hsg9q0kcl8hagag-netbase_5.3.tar.xz.nix).out} ${(import ../store/47vrqp50amqr5vzf2nhirb6m7pzjz898-tar-1.35.nix).out} ${(import ../store/iclgk2vkv5psn59v746fk0wiy5nl65z3-xz-5.4.5.nix).out}";
}
