# Generated by guix-transfer
builtins.derivation {
  name = "binutils-mesboot0-2.20.1a";
  system = "x86_64-linux";
  builder = "${(import ../store/3sgvmyxar0bp0r707sgivngr256jlw8k-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import''; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; }}"
    "-C"
    "${(import ../store/f1pxw9ip8s5g4ka338rz03kza9ip49mz-module-import-compiled.nix).out}"
    "${builtins.path { name = ''binutils-mesboot0-2.20.1a-builder''; path = ./../sources/q5z37ydf1d1j7p9disfp1c3bd9ihiv73-binutils-mesboot0-2.20.1a-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import"; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; })
    (builtins.path { name = "binutils-mesboot0-2.20.1a-builder"; path = ./../sources/q5z37ydf1d1j7p9disfp1c3bd9ihiv73-binutils-mesboot0-2.20.1a-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/xvcs6bjwxn94js3m8vzy54xrkbhp6v2k-binutils-2.20.1a.tar.xz.nix).out} ${(import ../store/kccamw56m6xs1a8dprpl298nb4sjjg3x-gzip-mesboot-1.2.4.nix).out} ${(import ../store/7xys2xa5sskz1qakac92sydx83hfhjsp-patch-mesboot-2.5.9.nix).out} ${(import ../store/kqgx82wczsgs3ps0hyh4sak2fp7nz8jv-gash-utils-boot-0.2.0.nix).out} ${(import ../store/x6yr5bpjnj89rnn1rxawhk0cgn0wx9jw-bootar-1b.nix).out} ${(import ../store/b65ygsqbgf75q7d578g11rp83im7b71n-make-mesboot0-3.80.nix).out} ${(import ../store/bwx4qmi4638ia9mmrhbav5sh7izvbv8n-gash-boot-0.3.1.nix).out} ${(import ../store/ppda7jxss3clnhd31y5av17lp3viccvd-tcc-boot-0.9.27.nix).out}";
}
