# Generated by guix-transfer
builtins.derivation {
  name = "pdm_backend-2.4.5.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-VsAZxEAwitrV0FfAjLt3fmX0O5kaOwkgdJeBJYly/ls=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/pdm_backend-2.4.5.tar.gz/sha256/0nzyfa4jb0cpfhh0jfqsk4xz8rbyfyxqrh2ps3axm2ih8321kh2n";
}
