# Generated by guix-transfer
builtins.derivation {
  name = "readline-8.2.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-P+txcfFqhO6CyhijbXub4QmlLAT0kqBTMx19EJUAfDU=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://ftp.gnu.org/gnu/readline/readline-8.2.tar.gz";
}
