# Generated by guix-transfer
builtins.derivation {
  name = "libXt-1.3.1.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/pq24yb7jw5rqgccsssvkk9n4lj9m1ri3-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/66alicjhn34r3fdisxzh1xvlkfhvllm9-module-import-compiled.nix).out}"
    "${builtins.path { name = ''libXt-1.3.1.tar.zst-builder''; path = ./../sources/6xlyxinsidajlvjgql8p9cmpikwnaj5l-libXt-1.3.1.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "libxt-guix-search-paths.patch"; path = ./../sources/7gj07j88w4qc062zf440hq2wq2m6imir-libxt-guix-search-paths.patch; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "libXt-1.3.1.tar.zst-builder"; path = ./../sources/6xlyxinsidajlvjgql8p9cmpikwnaj5l-libXt-1.3.1.tar.zst-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 1))";
  __phantom_deps = "${(import ../store/zk318zd7m8y0v1k3fwq7rzz305nbvwsb-libXt-1.3.1.tar.xz.nix).out} ${(import ../store/gyhiimwajbnkd9myji0qfi40jhy7w9y2-xz-5.4.5.nix).out} ${(import ../store/vpi87n22f8dbhvbwaqr470xp83hnbf1y-tar-1.35.nix).out} ${(import ../store/759rgw9c7j48gb1bv5fgr2sb3d9f5p1v-patch-2.7.6.nix).out} ${(import ../store/r2mqn9i7k9h1xzrx3jbihckz3lhymvpv-zstd-1.5.6.nix).out}";
}
