# Generated by guix-transfer
builtins.derivation {
  name = "procps-ng-4.0.3.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/0wsxd5g0xbxncz609bqq5hbg48hx8cpm-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/69fricvrgmnbmbm6hi7j08m4cvagza7h-module-import-compiled.nix).out}"
    "${builtins.path { name = ''procps-ng-4.0.3.tar.zst-builder''; path = ./../sources/iaykxmdll8da2zmi4jgnrvbn6mik85i1-procps-ng-4.0.3.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "procps-ng-4.0.3.tar.zst-builder"; path = ./../sources/iaykxmdll8da2zmi4jgnrvbn6mik85i1-procps-ng-4.0.3.tar.zst-builder; })
    (builtins.path { name = "procps-strtod-test.patch"; path = ./../sources/r7wfn7aasq35pb8jgx0cn58r2zmsj95k-procps-strtod-test.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 1))";
  __phantom_deps = "${(import ../store/fmnh1rwlg4r228hfcyq64mk8vxzx24p7-procps-ng-4.0.3.tar.xz.nix).out} ${(import ../store/fl18v8zafk6wpc2yqxrahapqw7l7n073-xz-5.4.5.nix).out} ${(import ../store/pv1ibrv4pc1km18w8i0iiwklhpn6h9lc-tar-1.35.nix).out} ${(import ../store/q8sb66r0q7l58drjj8wdqlf2808abkar-patch-2.7.6.nix).out} ${(import ../store/f60dfz81yizjj1j5x7pzdcmmhc38yr1v-zstd-1.5.6.nix).out}";
}
