# Generated by guix-transfer
builtins.derivation {
  name = "sassc-3.6.2-checkout";
  system = "x86_64-linux";
  builder = "builtin:git-download";
  outputHash = "sha256-jcs3+orRqKt9C3c2FTdeaj4H2rBP74lW3HF8CHSm7lQ=";
  outputHashAlgo = "sha256";
  outputHashMode = "recursive";
  commit = "3.6.2";
  impureEnvVars = "http_proxy https_proxy LC_ALL LC_MESSAGES LANG COLUMNS";
  preferLocalBuild = "1";
  "recursive?" = "#f";
  url = "\"https://github.com/sass/sassc\"";
}
