# Generated by guix-transfer
builtins.derivation {
  name = "rust-webpki-roots-0.26.8.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-IhCykffqU2F/uvzEk58QkUIU7BWqzlumIpOmaPMixck=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/webpki-roots/0.26.8/download";
}
