# Generated by guix-transfer
builtins.derivation {
  name = "gcc-14.3.0.tar.xz";
  system = "x86_64-linux";
  builder = "${(import ../store/xxpwmhk6fpk8c3x18vrz1yfzh1bvppm5-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/70ns6s1k8i1kzkwhhbyw02p2a4lxfba0-module-import-compiled.nix).out}"
    "${builtins.path { name = ''gcc-14.3.0.tar.xz-builder''; path = ./../sources/d2vhkpn4g8plmdhkj7jl8ga1ds6kb9pg-gcc-14.3.0.tar.xz-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "gcc-5.0-libvtv-runpath.patch"; path = ./../sources/q9qlyld3rch8kd3qrxcss1r2p1fhdv95-gcc-5.0-libvtv-runpath.patch; })
    (builtins.path { name = "gcc-12-strmov-store-file-names.patch"; path = ./../sources/ydfd42mc58s9glr4wgf6jdvrfr52bnsw-gcc-12-strmov-store-file-names.patch; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "gcc-14.3.0.tar.xz-builder"; path = ./../sources/d2vhkpn4g8plmdhkj7jl8ga1ds6kb9pg-gcc-14.3.0.tar.xz-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 2))";
  __phantom_deps = "${(import ../store/fkkl5lv3kpda2zn3scc6cfmq1r8x08ph-gcc-14.3.0.tar.xz.nix).out} ${(import ../store/d4fnn1wjwqhwkzgf0i8aw4qfglnm41v4-coreutils-boot0-9.1.nix).out} ${(import ../store/r9lli79l2f45sfis06sa8hyp6s0pkxhc-bootstrap-binaries-0.nix).out}";
}
