# Generated by guix-transfer
builtins.derivation {
  name = "ruamel.yaml-0.18.14.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-cie3aq7DZN8Vk2cw7799crMMC3mx1Xi7uOPcstgfUrc=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://files.pythonhosted.org/packages/source/r/ruamel.yaml/ruamel.yaml-0.18.14.tar.gz";
}
