# Generated by guix-transfer
builtins.derivation {
  name = "rust-num-conv-0.1.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-UdUV0y+xgu43zaLM3LkpUNajwok6ooDlQGccLNDzsdk=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/num-conv/0.1.0/download";
}
