# Generated by guix-transfer
builtins.derivation {
  name = "python-wrapper-3.11.14";
  system = "x86_64-linux";
  builder = "${(import ../store/hn59viz2gmjdjjikmjmmlf5lnnp4wzn1-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/nnjrv59xc0zvampmfnv1xac2gk3f8ffp-module-import-compiled.nix).out}"
    "${builtins.path { name = ''python-wrapper-3.11.14-builder''; path = ./../sources/cs75ybgqk5g4sv21g2p4shb1bpl78xrb-python-wrapper-3.11.14-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "python-wrapper-3.11.14-builder"; path = ./../sources/cs75ybgqk5g4sv21g2p4shb1bpl78xrb-python-wrapper-3.11.14-builder; })
    (builtins.path { name = "sitecustomize.py"; path = ./../sources/sm310qy71q4i1s4rn0a5a29ryyiydvd4-sitecustomize.py; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/f0hqw9r6gaasc4863ga522yq5sh37jmh-unzip-6.0.nix).out} ${(import ../store/6gznwawm88kxfavwyklghwhx8hrif0qm-bash-5.2.37.nix).out} ${(import ../store/wvmfl79ns4n1byjic3ggmwdr36iw2z89-python-3.11.14.nix).out} ${(import ../store/0khsl4mgrx8zxdpkxc05qjjxkx3vj038-tzdata-2025a.nix).out} ${(import ../store/5pfc3m5k8bjw72sdvfvg2ikhkrmyhhh0-zip-3.0.nix).out} ${(import ../store/xav3wsb3h8qvqxqxsfi2r1r318gp72hx-pkg-config-0.29.2.nix).out}";
}
