# Generated by guix-transfer
builtins.derivation {
  name = "libfontenc-1.1.8.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-ewLD1AUjbg2GgGsd6daGj+YMMTYos4NQsDKRSqT9FMY=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/libfontenc-1.1.8.tar.xz/sha256/1ihlznj4m49jn1887cr86qqhrrlghvbfj7bbh230svi30pac60kv";
}
