# Generated by guix-transfer
builtins.derivation {
  name = "python-minimal-wrapper-3.11.11";
  system = "x86_64-linux";
  builder = "${import ../store/h6j68xwpj7dm4xbrkw5n28k434wlw0g0-guile-3.0.9.nix}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${../sources/zfz0k7p3wv8g31j0ycb3p9s75wpyq3jw-jsxgc979x79h81kzqz9n6cpf5pk4z262-module-import}"
    "-C"
    "${import ../store/li5xpkgwwawrqd9zkdzjlpincr26cmpg-module-import-compiled.nix}"
    "${../sources/85j2k3jrpjaf0s3ffvnyj4xgw76fbrg3-python-minimal-wrapper-3.11.11-builder}"
  ];
  __phantom_deps = "84yinmp3w14m3ppgsnwap78rjs72b1c6-bash-5.1.16 a57q0y1dp68br1d0s6m0mnw2vwmckd37-python-minimal-3.11.11 ir729ga0gcix1xwjx7w34yl0y9rcz38k-unzip-6.0 m7901m67935kyigr9svbmfr08ns2z9qx-pkg-config-0.29.2 piyskqbpp1n8w9vs5p6bfg2zm47xcxhi-zip-3.0 vpzrxr5c519j1rjd0a60ikdw08khj166-tzdata-2023d";
}
