# Generated by guix-transfer
builtins.derivation {
  name = "rust-hermit-abi-0.1.19.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-YrRnNDuUukdtyyUA0kLa27OVV9+IkxCsd8XZkQCqrDM=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-hermit-abi-0.1.19.tar.gz/sha256/0cxcm8093nf5fyn114w8vxbrbcyvv91d4015rdnlgfll7cs6gd32";
}
