# Generated by guix-transfer
builtins.derivation {
  name = "readline82-003";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-JPWHuka0btKxhozK+ZR1BP66FUu4+qvUra6mPvfmrLA=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://ftp.gnu.org/gnu/readline/readline-8.2-patches/readline82-003";
}
