# Generated by guix-transfer
builtins.derivation {
  name = "xcb-util-0.4.1.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-Wr47u9jlTw+j7JRSkbfo+oz9PMzENxj4dYQw+UEm5RI=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/xcb-util-0.4.1.tar.xz/sha256/04p54r0zjc44fpw1hdy4rhygv37sx2vr2lllxjihykz5v2xkpgjs";
}
