# Generated by guix-transfer
builtins.derivation {
  name = "libX11-1.8.12.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-+gJvm7AST01sgI+a70BXqtZeezXY/0OVHO8Kvga7mpo=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/libX11-1.8.12.tar.xz/sha256/16lspc3bw2pg3jal7zyq6mxmxmmaax0fz6lgh1n4skqjn2dny0ps";
}
