# Generated by guix-transfer
builtins.derivation {
  name = "rust-getrandom-0.2.15.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-xFZ8jbEK6RCJyZr4TGjDjaPsLwh8P4KWC82/Nla29Nc=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-getrandom-0.2.15.tar.gz/sha256/1mzlnrb3dgyd1fb84gvw10pyr8wdqdl4ry4sr64i1s8an66pqmn4";
}
