# Generated by guix-transfer
builtins.derivation {
  name = "rust-rustversion-1.0.20.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-7e04LF9feGuYllLElUTEh32fAVzCLhRaXqjqZsKSHNI=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/rustversion/1.0.20/download";
}
