# Generated by guix-transfer
builtins.derivation {
  name = "rust-lockfree-object-pool-0.1.6.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-k3TvQihALUt+QD5YOMuIDZ7mYzFLCpANWmqr8MITVS4=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/lockfree-object-pool/0.1.6/download";
}
