# Generated by guix-transfer
builtins.derivation {
  name = "serf-1.3.10.tar.bz2";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-voHvCLqiUW7Np2p3rffe97wyJ+61eLmjO0X3tB3AZOY=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/serf-1.3.10.tar.bz2/sha256/1rk4q0fv9xs57fivjy5mxqkk5g7pvvvssxvalz6nwld2p84fz0dy";
}
