# Generated by guix-transfer
builtins.derivation {
  name = "libsoup-2.74.3.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-5Ld8Qc/EyMWgNfzcMgx7xs+3XvfFoDQVPfFBP6HZLxM=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/libsoup-2.74.3.tar.xz/sha256/04rgv6hkyhgi7lak9865yxgbgky6gc635p7w6nhcbj64rx0prdz4";
}
