# Generated by guix-transfer
builtins.derivation {
  name = "trio-typing-0.10.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-Bl7mhCltUqirDiN0ZmMBrsNu5XR6wOemHyMCUPiQesM=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/trio-typing-0.10.0.tar.gz/sha256/1hvsj3w500i33ykfgh3sfkjnxhxf05incx131smshlkd562fcph6";
}
