# Generated by guix-transfer
builtins.derivation {
  name = "rust-terminal-size-0.4.2.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-RcZIHEgp5Mxjgl5ixJGGo0U4t7J1C3OyZlgf+2Evte0=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-terminal-size-0.4.2.tar.gz/sha256/1vdm5xhzn7sqcsr762vmnavkhid3hs8w8qjyh9iwrr1990f4iij5";
}
