# Generated by guix-transfer
builtins.derivation {
  name = "rustc-1.74.0-src.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/0wsxd5g0xbxncz609bqq5hbg48hx8cpm-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/69fricvrgmnbmbm6hi7j08m4cvagza7h-module-import-compiled.nix).out}"
    "${builtins.path { name = ''rustc-1.74.0-src.tar.zst-builder''; path = ./../sources/08fqm1v8jpy4q4hfwapc9md2bgbxwcgm-rustc-1.74.0-src.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "rustc-1.74.0-src.tar.zst-builder"; path = ./../sources/08fqm1v8jpy4q4hfwapc9md2bgbxwcgm-rustc-1.74.0-src.tar.zst-builder; })
    (builtins.path { name = "rust-1.70-fix-rustix-build.patch"; path = ./../sources/x00n4yvhd5n0fjkgi6jpxcg19w0c8y9j-rust-1.70-fix-rustix-build.patch; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 1))";
  __phantom_deps = "${(import ../store/fl18v8zafk6wpc2yqxrahapqw7l7n073-xz-5.4.5.nix).out} ${(import ../store/ifnnyhrlkkgrddjwmlhzklipy814hlbx-rustc-1.74.0-src.tar.gz.nix).out} ${(import ../store/qial9rx6j4r00ivwxk25wbsi0fjzibwl-gzip-1.14.nix).out} ${(import ../store/pv1ibrv4pc1km18w8i0iiwklhpn6h9lc-tar-1.35.nix).out} ${(import ../store/q8sb66r0q7l58drjj8wdqlf2808abkar-patch-2.7.6.nix).out} ${(import ../store/f60dfz81yizjj1j5x7pzdcmmhc38yr1v-zstd-1.5.6.nix).out}";
}
