# Generated by guix-transfer
builtins.derivation {
  name = "libstdc++-headers-13.3.0";
  system = "x86_64-linux";
  builder = "${(import ../store/c4ay50vfyk7bxiiy4gzz8wp6d6b9qfay-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "${builtins.path { name = ''libstdc++-headers-13.3.0-builder''; path = ./../sources/pcpdxh1lj72g6g2cfnj83i2zvly4yj74-libstdc++-headers-13.3.0-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "libstdc++-headers-13.3.0-builder"; path = ./../sources/pcpdxh1lj72g6g2cfnj83i2zvly4yj74-libstdc++-headers-13.3.0-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/062hivclqmav6bdnhj681fc5xlmq4w07-libstdc++-13.3.0.nix).out} ${(import ../store/69r2690qilhpcpxxys4qxfpvsd068030-gcc-13.3.0.tar.zst.nix).out}";
}
