# Generated by guix-transfer
builtins.derivation {
  name = "bash52-030";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-w/9zIw4SOs21rCFpIaOG3490NARZUz13bQKBGh92aY8=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/bash52-030/sha256/13v9fqgim082dmvkslsr0hs793yzhsij2s91mjswsfhj1qip7zy3";
}
