# Generated by guix-transfer
builtins.derivation {
  name = "rust-fdeflate-0.3.7.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-HmhTtSZJ1KxcC9AjIM3cW6lWvbQHxLdaLGt1v1FQD4w=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/fdeflate/0.3.7/download";
}
