# Generated by guix-transfer
builtins.derivation {
  name = "emacs-shut-up-0.3.3-checkout";
  system = "x86_64-linux";
  builder = "builtin:git-download";
  outputHash = "sha256-oYxJG9l+5iPJUwJO2gQ++hbZfP6cPykHu8yoDDPP1a4=";
  outputHashAlgo = "sha256";
  outputHashMode = "recursive";
  commit = "v0.3.3";
  impureEnvVars = "http_proxy https_proxy LC_ALL LC_MESSAGES LANG COLUMNS";
  preferLocalBuild = "1";
  "recursive?" = "#f";
  url = "\"https://github.com/cask/shut-up\"";
}
