# Generated by guix-transfer
builtins.derivation {
  name = "gawk-mesboot-3.1.8";
  system = "x86_64-linux";
  builder = "${(import ../store/3sgvmyxar0bp0r707sgivngr256jlw8k-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import''; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; }}"
    "-C"
    "${(import ../store/f1pxw9ip8s5g4ka338rz03kza9ip49mz-module-import-compiled.nix).out}"
    "${builtins.path { name = ''gawk-mesboot-3.1.8-builder''; path = ./../sources/m85xsiwhvr0cjbbpjpx4rnqy2rac5vhl-gawk-mesboot-3.1.8-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import"; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; })
    (builtins.path { name = "gawk-mesboot-3.1.8-builder"; path = ./../sources/m85xsiwhvr0cjbbpjpx4rnqy2rac5vhl-gawk-mesboot-3.1.8-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/klsq7svky73yillz3x11y7xkzpd0dd2d-gawk-3.1.8.tar.gz.nix).out} ${(import ../store/l46qfmdxhqdb47fglp4m1hb9swq6jzkp-linux-libre-headers-bootstrap-0.nix).out} ${(import ../store/6q4wczw41fysqyy94zkv5fv8sya0jxpp-patch-mesboot-2.5.9.nix).out} ${(import ../store/kqgx82wczsgs3ps0hyh4sak2fp7nz8jv-gash-utils-boot-0.2.0.nix).out} ${(import ../store/x6yr5bpjnj89rnn1rxawhk0cgn0wx9jw-bootar-1b.nix).out} ${(import ../store/d26qydiaj7q4xb0y6kxy95l8smjm07g1-gcc-mesboot1-4.6.4.nix).out} ${(import ../store/730yn4856ykv2306b65pbq3rcnyngi7f-gzip-mesboot-1.2.4.nix).out} ${(import ../store/njaqylj1hfrg3zzand13rijp4mfqjbmz-make-mesboot-3.82.nix).out} ${(import ../store/g4d9mmhvis6dw00drnwqa69rynlp8m06-glibc-mesboot0-2.2.5.nix).out} ${(import ../store/s8kk5nws9as3wvf7qc9h06lzljm98c8a-binutils-mesboot1-2.20.1a.nix).out} ${(import ../store/bwx4qmi4638ia9mmrhbav5sh7izvbv8n-gash-boot-0.3.1.nix).out}";
}
