# Generated by guix-transfer
builtins.derivation {
  name = "bash52-014";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-PvkkbykG7x5Iego/TGR64cKJy9hFnKp9tc4RjvE25iQ=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://ftp.gnu.org/gnu/bash/bash-5.2-patches/bash52-014";
}
