# Generated by guix-transfer
builtins.derivation {
  name = "rust-wasi-0.14.2+wasi-0.2.4.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-loP5pamY2HPA0h/L48CDAJZwFJqPqyKGRLi9NrLEjLM=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-wasi-0.14.2+wasi-0.2.4.tar.gz/sha256/1cwcqjr3dgdq8j325awgk8a715h0hg0f7jqzsb077n4qm6jzk0wn";
}
