# Generated by guix-transfer
builtins.derivation {
  name = "gcc-mesboot-wrapper-4.9.4";
  system = "x86_64-linux";
  builder = "${(import ../store/3sgvmyxar0bp0r707sgivngr256jlw8k-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import''; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; }}"
    "-C"
    "${(import ../store/f1pxw9ip8s5g4ka338rz03kza9ip49mz-module-import-compiled.nix).out}"
    "${builtins.path { name = ''gcc-mesboot-wrapper-4.9.4-builder''; path = ./../sources/94v4aw9xwraww6dgkf7a4a20mkksz784-gcc-mesboot-wrapper-4.9.4-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import"; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; })
    (builtins.path { name = "gcc-mesboot-wrapper-4.9.4-builder"; path = ./../sources/94v4aw9xwraww6dgkf7a4a20mkksz784-gcc-mesboot-wrapper-4.9.4-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/f3c9i4bahdgm1yriwrx4whzzx1is7kaq-gcc-mesboot-4.9.4.nix).out} ${(import ../store/jy5cfxablyf32ifmf3yvxy2k0b47n7nf-glibc-mesboot-2.16.0.nix).out} ${(import ../store/kqgx82wczsgs3ps0hyh4sak2fp7nz8jv-gash-utils-boot-0.2.0.nix).out} ${(import ../store/bwx4qmi4638ia9mmrhbav5sh7izvbv8n-gash-boot-0.3.1.nix).out}";
}
