# Generated by guix-transfer
builtins.derivation {
  name = "rust-textwrap-0.16.2.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-wTVHYVpE3JxFKopTRjis3wcSDUtoR8gXhwXaBjBqMFc=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/textwrap/0.16.2/download";
}
