# Generated by guix-transfer
builtins.derivation {
  name = "rust-wide-0.7.32.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-QbVXa5qBYz8+jfKWzgBjBCpzUHY2y+lWxhEz3XA0qyI=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/wide/0.7.32/download";
}
