# Generated by guix-transfer
builtins.derivation {
  name = "rust-platform-info-2.0.5.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-dTmus/3Yy09qMxMHz3GhA5zudelOinFyW5SE9KDZRRo=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/platform-info/2.0.5/download";
}
