# Generated by guix-transfer
builtins.derivation {
  name = "gmp-6.3.0.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/f75k9wv63ksf2s8m5jfnhzbwvbqv84ps-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/g04gyzlav8k6j9bsh5awq479yyiga760-module-import-compiled.nix).out}"
    "${builtins.path { name = ''gmp-6.3.0.tar.zst-builder''; path = ./../sources/0shk37sv4z5yvxrr7alw5akmpg5rvjha-gmp-6.3.0.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "gmp-6.3.0.tar.zst-builder"; path = ./../sources/0shk37sv4z5yvxrr7alw5akmpg5rvjha-gmp-6.3.0.tar.zst-builder; })
    (builtins.path { name = "gmp-faulty-test.patch"; path = ./../sources/q2aaga2sv71piv27zfm9k9qhpzp5v18m-gmp-faulty-test.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 1))";
  __phantom_deps = "${(import ../store/prbr2b006j916llx53bhzla6vx1rxpih-patch-2.7.6.nix).out} ${(import ../store/nr0b4mv2xq7nsn4rmj9j13rkcz0vglnl-gmp-6.3.0.tar.xz.nix).out} ${(import ../store/jg77mkrxf4mj622s55bqsw667cryqyxd-tar-1.35.nix).out} ${(import ../store/6yl1l324h9vk7jm4xcjk7silhilby7zp-zstd-1.5.6.nix).out} ${(import ../store/nlxczvbla673cx586blzfwml5ix51rnq-xz-5.4.5.nix).out}";
}
