# Generated by guix-transfer
builtins.derivation {
  name = "gcc-13.3.0.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/c4ay50vfyk7bxiiy4gzz8wp6d6b9qfay-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/7skwz4rdpxxc3s03vb07mqvpxr8s6j1h-module-import-compiled.nix).out}"
    "${builtins.path { name = ''gcc-13.3.0.tar.zst-builder''; path = ./../sources/lx385ipq70zf6yd0aj6g2d5c1qk7bgb1-gcc-13.3.0.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "gcc-5.0-libvtv-runpath.patch"; path = ./../sources/q9qlyld3rch8kd3qrxcss1r2p1fhdv95-gcc-5.0-libvtv-runpath.patch; })
    (builtins.path { name = "gcc-12-strmov-store-file-names.patch"; path = ./../sources/ydfd42mc58s9glr4wgf6jdvrfr52bnsw-gcc-12-strmov-store-file-names.patch; })
    (builtins.path { name = "gcc-13.3.0.tar.zst-builder"; path = ./../sources/lx385ipq70zf6yd0aj6g2d5c1qk7bgb1-gcc-13.3.0.tar.zst-builder; })
    (builtins.path { name = "gcc-13-libsanitizer-no-crypt.patch"; path = ./../sources/wgdp25lqia8w0zgbl6wgsacxclyzg443-gcc-13-libsanitizer-no-crypt.patch; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "gcc-libstdc++-newer-gcc.patch"; path = ./../sources/y8zpwwcfnga8wh1qbdzk9k5sp83r9jmy-gcc-libstdc++-newer-gcc.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 4))";
  __phantom_deps = "${(import ../store/3f5ch18ghnzfbkk1iv2rk12j6n37lp51-xz-5.4.5.nix).out} ${(import ../store/fhskwarrjxl0726s5svlyqabd7i3ipy2-tar-1.35.nix).out} ${(import ../store/bs5jzy6r2zfk2hn9g21h7biwssm56266-patch-2.7.6.nix).out} ${(import ../store/bkz6caby7psjjdp3sj3sw2rcd28m95zl-gcc-13.3.0.tar.xz.nix).out} ${(import ../store/j62jcz2m4jjnvv3z42mdxvs73xp8d95s-zstd-1.5.6.nix).out}";
}
