# Generated by guix-transfer
builtins.derivation {
  name = "libdrm-2.4.124.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-rDYpP2HKSq+vSxaip6//MSqk9cN8n715fenjwIY8o3k=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/libdrm-2.4.124.tar.xz/sha256/0yd37j3c1qz9gmwvv7vwqgss8aiizypsg8hn9fpsyjnac4zjjdmc";
}
