# Generated by guix-transfer
builtins.derivation {
  name = "rust-winapi-i686-pc-windows-gnu-0.4.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-rDuHxjYgQm3ZuZHlzgMp7/VFvMu7NPO+Cf9vtqtRt7Y=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/winapi-i686-pc-windows-gnu/0.4.0/download";
}
