# Generated by guix-transfer
builtins.derivation {
  name = "rust-console-0.15.11.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-BUzLWxD58sv1HrNVyh0FwtJ5zhgEaI0Nt0tHM6Wur9g=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-console-0.15.11.tar.gz/sha256/1n5gmsjk6isbnw6qss043377kln20lfwlmdk3vswpwpr21dwnk05";
}
