# Generated by guix-transfer
builtins.derivation {
  name = "guile-2.0.9.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-A3sQNSKi0NfWnH/9jeaD3+W7S1nB+v1wtP/Tl/0vV/A=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "http://alpha.gnu.org/gnu/guix/bootstrap/x86_64-linux/20131110/guile-2.0.9.tar.xz";
}
