# Generated by guix-transfer
builtins.derivation {
  name = "rust-wasi-0.14.2+wasi-0.2.4.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-loP5pamY2HPA0h/L48CDAJZwFJqPqyKGRLi9NrLEjLM=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/wasi/0.14.2+wasi-0.2.4/download";
}
