# Generated by guix-transfer
builtins.derivation {
  name = "findutils-4.10.0.tar.xz";
  system = "x86_64-linux";
  builder = "${(import ../store/3sgvmyxar0bp0r707sgivngr256jlw8k-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/vqpyw7y1k6p4barzxp5x7j41h8ax7w1b-module-import-compiled.nix).out}"
    "${builtins.path { name = ''findutils-4.10.0.tar.xz-builder''; path = ./../sources/zhhbcf37scpjyrqx68x0h3q6wi2md7ha-findutils-4.10.0.tar.xz-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "findutils-localstatedir.patch"; path = ./../sources/xn0wb7d2k1v2yjkby7x885w77vfsdxjm-findutils-localstatedir.patch; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "findutils-4.10.0.tar.xz-builder"; path = ./../sources/zhhbcf37scpjyrqx68x0h3q6wi2md7ha-findutils-4.10.0.tar.xz-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 1))";
  __phantom_deps = "${(import ../store/axs3mf1kb3z69mbhzplsydwl3m3smkch-findutils-4.10.0.tar.xz.nix).out} ${(import ../store/gx9yhjw5zcfzxm1d3gmfb5sbc64xw6ww-bootstrap-binaries-0.nix).out}";
}
