# Generated by guix-transfer
builtins.derivation {
  name = "rust-windows-x86-64-gnullvm-0.52.6.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-JNWyPcQXQSZ5aBOW8rSfPejBRz3rUWvTRBCHLv9R7Q0=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/windows_x86_64_gnullvm/0.52.6/download";
}
