# Generated by guix-transfer
builtins.derivation {
  name = "pytest-trio-0.8.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-g2PbYzannmxTN1ohI6Qd2+zMSqk/k3iGUWQXiaVvtS4=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://files.pythonhosted.org/packages/source/p/pytest-trio/pytest-trio-0.8.0.tar.gz";
}
