# Generated by guix-transfer
builtins.derivation {
  name = "rust-windows-sys-0.52.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-KCvl82qM54H62MiuGPo/m+/1fsG1LLPeB4kgFCXZoz0=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/windows-sys/0.52.0/download";
}
