# Generated by guix-transfer
builtins.derivation {
  name = "rust-glib-0.19.9.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-OWUCefE1RpRlAY2q4LpTNXlCpSEhN1FXd9X9ynSYSkQ=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/glib/0.19.9/download";
}
