# Generated by guix-transfer
builtins.derivation {
  name = "gash-utils-boot-0.2.0";
  system = "x86_64-linux";
  builder = "${(import ../store/8ldwd1vqvlrg2lvjxfyqm5lg0v2v0i76-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''n4vnmaaac03xaviwzx2544h625x1qq3i-module-import''; path = ./../sources/30saz8qghpd87bp6bbj9c8w7mvq7zwbx-n4vnmaaac03xaviwzx2544h625x1qq3i-module-import; }}"
    "-C"
    "${(import ../store/83fw4dx4psqlvcqsf5c949vim8hxy284-module-import-compiled.nix).out}"
    "${builtins.path { name = ''gash-utils-boot-0.2.0-builder''; path = ./../sources/1hkzgxz92hyr69k2mkb10q6mbmpny5i2-gash-utils-boot-0.2.0-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "gash-utils-boot-0.2.0-builder"; path = ./../sources/1hkzgxz92hyr69k2mkb10q6mbmpny5i2-gash-utils-boot-0.2.0-builder; })
    (builtins.path { name = "n4vnmaaac03xaviwzx2544h625x1qq3i-module-import"; path = ./../sources/30saz8qghpd87bp6bbj9c8w7mvq7zwbx-n4vnmaaac03xaviwzx2544h625x1qq3i-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/27dv0nikhia0vgv9g862nvgxbnazmlhf-bootar-1b.nix).out} ${(import ../store/i8ddd0yhv545vkzf8z679pm5lvk3g3yc-gash-boot-0.3.1.nix).out} ${(import ../store/7jw1bdg6gbp0f03ld1xwh68b22fmp76y-gash-utils-0.2.0.tar.gz.nix).out}";
}
