# Generated by guix-transfer
builtins.derivation {
  name = "rust-rgb-0.8.50.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-Vzl9FmRnAEg7Z9LdZRHXkxj50Ff9vSGkBmrqyLQdMQo=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/rgb/0.8.50/download";
}
