# Generated by guix-transfer
builtins.derivation {
  name = "mercurial-7.1.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/hn59viz2gmjdjjikmjmmlf5lnnp4wzn1-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/nnjrv59xc0zvampmfnv1xac2gk3f8ffp-module-import-compiled.nix).out}"
    "${builtins.path { name = ''mercurial-7.1.tar.zst-builder''; path = ./../sources/5yyy1iahgfmd8vg65apwmqbs638kpvsf-mercurial-7.1.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "mercurial-7.1.tar.zst-builder"; path = ./../sources/5yyy1iahgfmd8vg65apwmqbs638kpvsf-mercurial-7.1.tar.zst-builder; })
    (builtins.path { name = "mercurial-hg-extension-path.patch"; path = ./../sources/hp7nnh3v0rwkrk0v91bzw2xp8zjd8hzc-mercurial-hg-extension-path.patch; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 1))";
  __phantom_deps = "${(import ../store/h9ys9ff47zjq8g6glpw9vckvjszbid19-xz-5.4.5.nix).out} ${(import ../store/xdhd9k0narw3a72pspxgm0hgdww3a4x0-gzip-1.14.nix).out} ${(import ../store/6mcsn3vji1fs82g0jlksppd7nwiyzk0x-tar-1.35.nix).out} ${(import ../store/3dkv752q177fnqymgmr8cphflfxriarb-mercurial-7.1.tar.gz.nix).out} ${(import ../store/ix63qg734rsvk1jafvk2d9f83nhssk1a-patch-2.7.6.nix).out} ${(import ../store/sq6pj4hf188957l7vjnc38lavkpcj4pl-zstd-1.5.6.nix).out}";
}
