# Generated by guix-transfer
builtins.derivation {
  name = "bash52-001";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-9C8v7pI7wiCfQGoYknchIcRn9EUzvt/gChdhOdpdMQo=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://ftp.gnu.org/gnu/bash/bash-5.2-patches/bash52-001";
}
