# Generated by guix-transfer
builtins.derivation {
  name = "glibc-2.39.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-93vUfPgXDFc2Wue/hmlsEYrbOxINMlnGTFAtPcHi2SY=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/glibc-2.39.tar.xz/sha256/09nrwb0ksbah9k35jchd28xxp2hidilqdgz7b8v5f30pz1yd8yzp";
}
