# Generated by guix-transfer
builtins.derivation {
  name = "python-py-cpuinfo-9.0.0";
  system = "x86_64-linux";
  builder = "${(import ../store/hn59viz2gmjdjjikmjmmlf5lnnp4wzn1-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''qyfdq7birq9lw0kcgpsq7hs3raj1a9sg-module-import''; path = ./../sources/sx4dwnhh25m6q07qkg8hx56a7cl1yll7-qyfdq7birq9lw0kcgpsq7hs3raj1a9sg-module-import; }}"
    "-L"
    "${(import ../store/0jgi9nl1jj70nqyv0xzwpismpd521g0m-guile-json-4.7.3.nix).out}/share/guile/site/3.0"
    "-C"
    "${(import ../store/790ivfypsb3mg2ir74kskd0rm6r94kzx-module-import-compiled.nix).out}"
    "-C"
    "${(import ../store/0jgi9nl1jj70nqyv0xzwpismpd521g0m-guile-json-4.7.3.nix).out}/lib/guile/3.0/site-ccache"
    "${builtins.path { name = ''python-py-cpuinfo-9.0.0-builder''; path = ./../sources/kpw8s5jp9m8vh271xvy1nl9h4xwz3xgx-python-py-cpuinfo-9.0.0-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "python-py-cpuinfo-9.0.0-builder"; path = ./../sources/kpw8s5jp9m8vh271xvy1nl9h4xwz3xgx-python-py-cpuinfo-9.0.0-builder; })
    (builtins.path { name = "sanity-check.py"; path = ./../sources/09lx08cjsa3ppv6aindzi8dh3y3nqs8r-sanity-check.py; })
    (builtins.path { name = "qyfdq7birq9lw0kcgpsq7hs3raj1a9sg-module-import"; path = ./../sources/sx4dwnhh25m6q07qkg8hx56a7cl1yll7-qyfdq7birq9lw0kcgpsq7hs3raj1a9sg-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/4qm7wl53v2zck0w88am7cbifcqz63ib8-python-wrapper-3.11.14.nix).out} ${(import ../store/asrzfr2qas01nlii0qczhzlxd7zr4rdy-gcc-14.3.0.nix).out} ${(import ../store/h9ys9ff47zjq8g6glpw9vckvjszbid19-xz-5.4.5.nix).out} ${(import ../store/9c2qf69dhbrgpqx2a8ab46qphsgi110w-glibc-2.41.nix).out} ${(import ../store/dh4rlzrx7kj128kimpp40x350gvcnxda-file-5.46.nix).out} ${(import ../store/d3ipgrk70f0iq21pln0q6fpw6r4iw5xx-bash-minimal-5.2.37.nix).out} ${(import ../store/xdhd9k0narw3a72pspxgm0hgdww3a4x0-gzip-1.14.nix).out} ${(import ../store/wvmfl79ns4n1byjic3ggmwdr36iw2z89-python-3.11.14.nix).out} ${(import ../store/gqq9b0s40fd9j498bwqky7r0m9h11r3y-gawk-5.3.0.nix).out} ${(import ../store/p157xy8a0kv4p30x49rmds66a3dlpqfd-ld-wrapper-0.nix).out} ${(import ../store/hslhbz1vhyv57h8ik51kh2vi36c3zsjd-python-py-cpuinfo-9.0.0-checkout.nix).out} ${(import ../store/6mcsn3vji1fs82g0jlksppd7nwiyzk0x-tar-1.35.nix).out} ${(import ../store/dkhqfiqzfbx2iwlgy5i252v39gfm1xhi-linux-libre-headers-6.12.17.nix).out} ${(import ../store/9cjadwpjygly4pan6fks8gzxmv2dvfvb-coreutils-9.1.nix).out} ${(import ../store/n7a6qpk7xgxl8j78a9ngnbqb2lcjad0x-binutils-2.44.nix).out} ${(import ../store/1579v3jai551gzha5i02ccazjxy382jk-bzip2-1.0.8.nix).out} ${(import ../store/mqyj4agc5ji9pzyb5xia0cb2iziy9lp2-make-4.4.1.nix).out} ${(import ../store/k4p5rnkc77gdfzh8jaxxr088500d2ik4-diffutils-3.12.nix).out} ${(import ../store/s522q9vy9vdx3ar51z4gv0x9i0p5cjv0-grep-3.11.nix).out} ${(import ../store/1vznszlgvzr5lyfjj998119znq5mdirb-python-setuptools-80.9.0.nix).out} ${(import ../store/ix63qg734rsvk1jafvk2d9f83nhssk1a-patch-2.7.6.nix).out} ${(import ../store/sq6pj4hf188957l7vjnc38lavkpcj4pl-zstd-1.5.6.nix).out} ${(import ../store/zq2byd52990bdwcxjpgk1frry438wfrh-sed-4.9.nix).out} ${(import ../store/mq36a6vmid855whv156dnrjd3s52dysk-findutils-4.10.0.nix).out} ${(import ../store/9c2qf69dhbrgpqx2a8ab46qphsgi110w-glibc-2.41.nix).static}";
}
