# Generated by guix-transfer
builtins.derivation {
  name = "uvloop-0.21.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-O/ErD9poRHgGp62Ee/pZFhMXcnXTW2ckse5XP6o3BOM=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://files.pythonhosted.org/packages/source/u/uvloop/uvloop-0.21.0.tar.gz";
}
