# Generated by guix-transfer
builtins.derivation {
  name = "rust-num-integer-0.1.46.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-eWlmH9KVilywluVsjhrQRErCu80AYb0oZgSFpEh5hY8=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/num-integer/0.1.46/download";
}
