# Generated by guix-transfer
builtins.derivation {
  name = "rust-openssl-0.10.72.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-/t/qfVih9zEYQwpV2moobnsESWFzbOlqFqFwaOol5do=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-openssl-0.10.72.tar.gz/sha256/1np54pm6hw512rmfjv3kc54h8yvf51mdlm8a8cc33xx1b1yympzy";
}
