# Generated by guix-transfer
builtins.derivation {
  name = "sphinxcontrib_applehelp-2.0.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-LynvMxc1zpWO+kc0hz8ISUGXCJTGCQQIsHnGGy4cBtE=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/sphinxcontrib_applehelp-2.0.0.tar.gz/sha256/1l863hp1pikrn04082f6jh49fha910zqfd27za79bkim2wryya9g";
}
