# Generated by guix-transfer
builtins.derivation {
  name = "lxml-6.0.1.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-KzqILr8n3QJt84Aah89J/3kTNuD5Sw+tGV23fgEkBpA=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/lxml-6.0.1.tar.gz/sha256/14064h0pxdsx36nhyjzrw0v16ygz977qf6l0ydnh5p97pwp8hfib";
}
