# Generated by guix-transfer
builtins.derivation {
  name = "rust-rustls-pki-types-1.11.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-kXziZGJKS02xw2Tcw1v8qd7QFNCpWM1HrT6WDpiOpRw=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-rustls-pki-types-1.11.0.tar.gz/sha256/0755isc0x5iymm3wsn59s0ad1pm9zidw7p34qfqlsjsac9jf4z4i";
}
