# Generated by guix-transfer
builtins.derivation {
  name = "rust-filetime-0.2.25.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-NcBSLpgeaMv6jD+XhEGl80swuW4UazPNM1kXa1D+hYY=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-filetime-0.2.25.tar.gz/sha256/11l5zr86n5sr6g6k6sqldswk0jzklm0q95rzikxcns0yk0p55h1m";
}
