# Generated by guix-transfer
builtins.derivation {
  name = "libusb-1.0.25.tar.bz2";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-iijvGXp5frrCcC8JXoGXXisCsu7/J3T6kJx4p071CEk=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://github.com/libusb/libusb/releases/download/v1.0.25/libusb-1.0.25.tar.bz2";
}
