# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://github.com/vcrhonek/hwdata"; rev = "v0.392"; hash = "sha256-DjtPoPZZwFmVRZTOG4A+2KXI6zw68QEwq0iFRoV+5c4="; name = "hwdata-0.392-checkout"; fetchSubmodules = false; }
