# Generated by guix-transfer
builtins.derivation {
  name = "vulkan-headers-1.4.321.0";
  system = "x86_64-linux";
  builder = "${(import ../store/c4ay50vfyk7bxiiy4gzz8wp6d6b9qfay-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''2s4hmyqpmqxgxsg9mpn6nyk4hqq3vlw6-module-import''; path = ./../sources/xjjq0c2i6ygwbdz70vfzx5j008czkxqk-2s4hmyqpmqxgxsg9mpn6nyk4hqq3vlw6-module-import; }}"
    "-C"
    "${(import ../store/vv6q782h4ka717nrsp3173bf4bk7ryyz-module-import-compiled.nix).out}"
    "${builtins.path { name = ''vulkan-headers-1.4.321.0-builder''; path = ./../sources/6lmvfrlxfykz3m8m3r07hi3hgqxsrn51-vulkan-headers-1.4.321.0-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "2s4hmyqpmqxgxsg9mpn6nyk4hqq3vlw6-module-import"; path = ./../sources/xjjq0c2i6ygwbdz70vfzx5j008czkxqk-2s4hmyqpmqxgxsg9mpn6nyk4hqq3vlw6-module-import; })
    (builtins.path { name = "vulkan-headers-1.4.321.0-builder"; path = ./../sources/6lmvfrlxfykz3m8m3r07hi3hgqxsrn51-vulkan-headers-1.4.321.0-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/i2l427rm2inz1rg89zy0n39l5rb5yla8-gcc-14.3.0.nix).out} ${(import ../store/3f5ch18ghnzfbkk1iv2rk12j6n37lp51-xz-5.4.5.nix).out} ${(import ../store/424mrddaf4aiwpisixqxj3jnbjvihzpl-glibc-2.41.nix).out} ${(import ../store/ashl3ad6rql26f1g0dm8gv4k1r8w4ycr-file-5.46.nix).out} ${(import ../store/7r40ypzacwbj5mc8ypx11cy4idqr0ran-bash-minimal-5.2.37.nix).out} ${(import ../store/8wg103mjrc4gzj8aq9l1ir8yb7nhqvc6-gzip-1.14.nix).out} ${(import ../store/r40sixlbax8ydbvzsxpw691mmydw16bb-gawk-5.3.0.nix).out} ${(import ../store/2ibdvba6m3j7vkg73m3aw2xvin4ygjng-ld-wrapper-0.nix).out} ${(import ../store/fhskwarrjxl0726s5svlyqabd7i3ipy2-tar-1.35.nix).out} ${(import ../store/vz33hm7r8nx8q12kgmgbzrcbp0y2cqmy-linux-libre-headers-6.12.17.nix).out} ${(import ../store/d4knmps8s4akzwj9196wkqdxz5bgr50b-ninja-1.13.2.nix).out} ${(import ../store/fj3kwiqp3g3hhgv69gnx1ph4sk8j7ilj-coreutils-9.1.nix).out} ${(import ../store/rns4ppspkqywp3pscs72snzpsgqa93pp-binutils-2.44.nix).out} ${(import ../store/5vxv8y96ddbc566cgn39j888ndjy83aq-bzip2-1.0.8.nix).out} ${(import ../store/xipkl7i2c4akbz7zirb2fpyvvh82p41j-make-4.4.1.nix).out} ${(import ../store/37rwan0h7m70ayy51q2lj370qcq1f3b3-diffutils-3.12.nix).out} ${(import ../store/2k1i5gbqlin1djd84q3r5q2ygxzm4v1k-grep-3.11.nix).out} ${(import ../store/rrw5xxfyan3fnwswp150j4d5hd4nxigv-vulkan-headers-1.4.321.0-checkout.nix).out} ${(import ../store/bs5jzy6r2zfk2hn9g21h7biwssm56266-patch-2.7.6.nix).out} ${(import ../store/j62jcz2m4jjnvv3z42mdxvs73xp8d95s-zstd-1.5.6.nix).out} ${(import ../store/pqbzhrzha6rvhmgs6n29f4b7ddk2d013-sed-4.9.nix).out} ${(import ../store/jp2dpz34l4c8skmjav3aa5mi87387vr7-findutils-4.10.0.nix).out} ${(import ../store/xp796wmhxllmljz0q29i958q9lnf9i65-cmake-minimal-3.31.10.nix).out} ${(import ../store/424mrddaf4aiwpisixqxj3jnbjvihzpl-glibc-2.41.nix).static}";
}
