# Generated by guix-transfer
builtins.derivation {
  name = "rust-data-encoding-2.8.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-V19139JXON9bkbjkPhTUS9oUY3pY+ud5/SsGT4vz4BA=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-data-encoding-2.8.0.tar.gz/sha256/0470yf5ly1ibzmwygyjqg9ii9njbsha3xr5qj5dxyf2psbgpapsp";
}
