# Generated by guix-transfer
builtins.derivation {
  name = "rustc-1.81.0-src.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-hyRI/r3/MuUMPJCn4V+bstsTHRPFiP6QcbDtiIN8z6c=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rustc-1.81.0-src.tar.gz/sha256/19yggj1qivdhf68gx2652cfi7nxjkdgy39wh7h6facpzppz4h947";
}
