# Generated by guix-transfer
builtins.derivation {
  name = "netbase_5.3.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-gfbGl5UETWK4rZWc+drwSdBUX9RmxShgrT+TOx6XuIs=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/netbase_5.3.tar.xz/sha256/12xqjwg3p4rzmmh2iib6sigm9l29y3dgk74mmnw64k84jnbwdxl1";
}
