# Generated by guix-transfer
builtins.derivation {
  name = "rust-urlencoding-2.1.3.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-2vjbo7frhwyvHd7te8nSoEnzz9+ufLUhsIfMM65MSdo=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-urlencoding-2.1.3.tar.gz/sha256/1nj99jp37k47n0hvaz5fvz7z6jd0sb4ppvfy3nphr1zbnyixpy6s";
}
