# Generated by guix-transfer
builtins.derivation {
  name = "at-spi2-core-2.52.0.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-CsP8gyDI0B+hR8Jyun+gOAY4nGsD08QG0II+MONf9as=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://download.gnome.org/sources/at-spi2-core/2.52/at-spi2-core-2.52.0.tar.xz";
}
