# Generated by guix-transfer
builtins.derivation {
  name = "rust-winsafe-0.0.19.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-0TXRerdwJSrZXpqHLTZc8wkOO+hko0q0b0hVWZPvyQQ=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/winsafe/0.0.19/download";
}
