# Generated by guix-transfer
builtins.derivation {
  name = "PySocks-1.7.1.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-P4gEVx6+FZw4CsbeN2Q7tGhZcGVdO7okNTDWVYt5mqA=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/PySocks-1.7.1.tar.gz/sha256/184sg65mbmih6ljblfsxcmq5js5l7dj3gpn618w9q5dy3rbh921z";
}
