# Generated by guix-transfer
builtins.derivation {
  name = "module-import-compiled";
  system = "x86_64-linux";
  builder = "${(import ../store/0wsxd5g0xbxncz609bqq5hbg48hx8cpm-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "${builtins.path { name = ''compile-modules''; path = ./../sources/nxxhqnbq2xwaac8221dbg2l0jblqmpaf-compile-modules; }}"
  ];
  srcs = [
    (builtins.path { name = "build-utils.scm"; path = ./../sources/mcpxrl5ql7qyib48qn6g235balyhz7ym-build-utils.scm; })
    (builtins.path { name = "nbn274scj93ph4iwc5bvv1af5cwa668h-module-import"; path = ./../sources/90i85p6x241x9ly4a2kdljz6xg0q9vmp-nbn274scj93ph4iwc5bvv1af5cwa668h-module-import; })
    (builtins.path { name = "compile-modules"; path = ./../sources/nxxhqnbq2xwaac8221dbg2l0jblqmpaf-compile-modules; })
  ];
  GUILE_WARN_DEPRECATED = "no";
  extensions = "";
  "module count" = "6";
  modules = "${builtins.path { name = ''nbn274scj93ph4iwc5bvv1af5cwa668h-module-import''; path = ./../sources/90i85p6x241x9ly4a2kdljz6xg0q9vmp-nbn274scj93ph4iwc5bvv1af5cwa668h-module-import; }}";
  "optimization level" = "1";
  preferLocalBuild = "1";
}
