# Generated by guix-transfer
builtins.derivation {
  name = "hello-runtime-env";
  system = "x86_64-linux";
  builder = "${(import ../store/hn59viz2gmjdjjikmjmmlf5lnnp4wzn1-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
    "-C"
    "${(import ../store/y1zhhyv04z5fnhg9ashiqdfxd6k0hzfd-module-import-compiled.nix).out}"
    "${builtins.path { name = ''hello-runtime-env-builder''; path = ./../sources/z6kmw22n72aqibh3frybmzlw5p0qagkw-hello-runtime-env-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "hello-runtime-env-builder"; path = ./../sources/z6kmw22n72aqibh3frybmzlw5p0qagkw-hello-runtime-env-builder; })
    (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  allowSubstitutes = "0";
  "guix properties" = "((type . guixpkgs-runtime-env))";
  preferLocalBuild = "1";
  __phantom_deps = "${(import ../store/xv7wf6a3zhn5z4jgnbcc4c9bhqrzwgji-hello-2.12.2.nix).out}";
}
