# Generated by guix-transfer
builtins.derivation {
  name = "NormalizationTest.txt";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-2BGXFFPnB14a1W+xswHuzlqoB1e4H2FW50ob+zrlzrE=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/NormalizationTest.txt/sha256/1cffwlxgn6sawxb627xqaw3shnnfxq0v7cbgsld5w1z7aca9f4fq";
}
