# Generated by guix-transfer
builtins.derivation {
  name = "libgd-2.3.3.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/hn59viz2gmjdjjikmjmmlf5lnnp4wzn1-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/nnjrv59xc0zvampmfnv1xac2gk3f8ffp-module-import-compiled.nix).out}"
    "${builtins.path { name = ''libgd-2.3.3.tar.zst-builder''; path = ./../sources/ly4wjda2ypxj5czcnww8m1yd4ah7a68n-libgd-2.3.3.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "libgd-2.3.3.tar.zst-builder"; path = ./../sources/ly4wjda2ypxj5czcnww8m1yd4ah7a68n-libgd-2.3.3.tar.zst-builder; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "gd-fix-tests-on-i686.patch"; path = ./../sources/hr0ih2hln6i85h0yn8s1nnmx5gsb850w-gd-fix-tests-on-i686.patch; })
    (builtins.path { name = "gd-brect-bounds.patch"; path = ./../sources/4m9cjcj0m40drmwghq3i0l9mhxi7vl59-gd-brect-bounds.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 2))";
  __phantom_deps = "${(import ../store/h9ys9ff47zjq8g6glpw9vckvjszbid19-xz-5.4.5.nix).out} ${(import ../store/6mcsn3vji1fs82g0jlksppd7nwiyzk0x-tar-1.35.nix).out} ${(import ../store/vnra0a80bvab5xlygvmw55r25fwril7c-libgd-2.3.3.tar.xz.nix).out} ${(import ../store/ix63qg734rsvk1jafvk2d9f83nhssk1a-patch-2.7.6.nix).out} ${(import ../store/sq6pj4hf188957l7vjnc38lavkpcj4pl-zstd-1.5.6.nix).out}";
}
