# Generated by guix-transfer
builtins.derivation {
  name = "service_identity-24.2.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-uGg7oT8NOcbNXWJdLF9lQh1tcHsBOzdcNVdRVXy+jgk=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/service_identity-24.2.0.tar.gz/sha256/02cfpry5alap6mf3ffq1gdq6s7a2cmgjqpb2bp6wcf8d7yhkns5q";
}
