# Generated by guix-transfer
builtins.derivation {
  name = "hicolor-icon-theme-0.17.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-MXSENSJx0Yy7z6w4aOq3mNZ//xuEAudAuqb/QdWIqdg=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/hicolor-icon-theme-0.17.tar.xz/sha256/1n59i3al3zx6p90ff0l43gzpzmlqnzm6hf5cryxqrlbi48sq8x1i";
}
