# Generated by guix-transfer
builtins.derivation {
  name = "trio-0.28.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-TlR4lv6eilZY5U5MfF+h23SMu7qnyWXn1AUFuSjHPAU=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/trio-0.28.0.tar.gz/sha256/019wqwlbj185skknbjd7paxqqx6vl5gpqk2fwmc5d2lyzsb7hm2f";
}
