# Generated by guix-transfer
builtins.derivation {
  name = "rust-simba-0.8.1.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-BhUHyU/Gq0uhyaAwUBhAjjEuF8BB62O++Kpyb6M6zq4=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-simba-0.8.1.tar.gz/sha256/1bnf7ainywmaz2z67ss1q0bjwccf80c50c50r6hlpay69z4hf586";
}
