# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://github.com/llvm/llvm-project"; rev = "llvmorg-19.1.7"; hash = "sha256-cZAB5vZjeTsXt9QHbP5xluWNQnAHByHtHnAhVDV0E6I="; name = "llvm-project-19.1.7-checkout"; fetchSubmodules = false; }
