# Generated by guix-transfer
builtins.derivation {
  name = "jsonpointer-3.0.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-Ky1ynyCRUi1hw7MfguEYcPYLaPQ/vHBct2v0uDKvWe8=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/jsonpointer-3.0.0.tar.gz/sha256/1vsrmwrbix3bnxf71g1zyil0pxkh33hq47xkqdhjslli42gp4b9b";
}
