# Generated by guix-transfer
builtins.derivation {
  name = "pyparsing-3.2.3.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-ucE/GriztUL3Lij2NLrU3nWKs85FRuQwGXCtb6d8OL4=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/pyparsing-3.2.3.tar.gz/sha256/1giqgjknzbbh34qf8ij5rsrqlxfysjx39xi85vvl5ddkp0d3zhdr";
}
