# Generated by guix-transfer
builtins.derivation {
  name = "libunwind-cfa-rsp";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-0mQ6ifCfzXXeZjhKYbO8ncJX/GtNmz2nwiVrWmBYRWM=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://raw.githubusercontent.com/JuliaLang/julia/v1.8.2/deps/patches/libunwind-cfa-rsp.patch";
}
