# Generated by guix-transfer
builtins.derivation {
  name = "rust-predicates-tree-1.0.12.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-ct0tbTgd+3Ohk8f8pTZRjXyu45/IUD9059wL4FMbQlw=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-predicates-tree-1.0.12.tar.gz/sha256/0p223d9y02ywwxs3yl68kziswz4da4vabz67jfhp7yqx71njvpbj";
}
