# Generated by guix-transfer
builtins.derivation {
  name = "rust-getrandom-0.3.2.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-c/6oRQ7qS6w5QESPt65Q2R8DT5QRmfzZ2QmloHqkVfA=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-getrandom-0.3.2.tar.gz/sha256/1w2mlixa1989v7czr68iji7h67yra2pbg3s480wsqjza1r2sizkk";
}
