# Generated by guix-transfer
builtins.derivation {
  name = "sed-4.9.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-0UeKGPAzpzrBaCKQH2Uz0wtr5WG8vORv/Xq86TYCKC4=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://ftp.gnu.org/gnu/sed/sed-4.9.tar.gz";
}
