# Generated by guix-transfer
builtins.derivation {
  name = "rust-rstest-macros-0.22.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-xeFxHn0U90sSpYQRxUIYXvf7fy5/jubilAqINihSK0I=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-rstest-macros-0.22.0.tar.gz/sha256/0hiba8l3d20ajkifd3kz5rzzpxsy311ca4c4ll94pxqlglg73qf5";
}
