# Generated by guix-transfer
builtins.derivation {
  name = "guile-fibers-1.3.1-checkout";
  system = "x86_64-linux";
  builder = "${(import ../store/0wsxd5g0xbxncz609bqq5hbg48hx8cpm-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/69fricvrgmnbmbm6hi7j08m4cvagza7h-module-import-compiled.nix).out}"
    "${builtins.path { name = ''guile-fibers-1.3.1-checkout-builder''; path = ./../sources/sgr9xwgvnf7gjiy30a5fh95ijglsxyqw-guile-fibers-1.3.1-checkout-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "guile-fibers-1.3.1-checkout-builder"; path = ./../sources/sgr9xwgvnf7gjiy30a5fh95ijglsxyqw-guile-fibers-1.3.1-checkout-builder; })
    (builtins.path { name = "guile-fibers-libevent-timeout.patch"; path = ./../sources/si8ca90qdxvgn85gqhh71bhk62gczgpb-guile-fibers-libevent-timeout.patch; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "guile-fibers-libevent-32-bit.patch"; path = ./../sources/cpnpvlmsjbac2n77shqjmdv24mdjxhrx-guile-fibers-libevent-32-bit.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 2))";
  __phantom_deps = "${(import ../store/fl18v8zafk6wpc2yqxrahapqw7l7n073-xz-5.4.5.nix).out} ${(import ../store/1rfvhvk2d11m8c41kwkihjfrkjxj36pw-guile-fibers-1.3.1-checkout.nix).out} ${(import ../store/pv1ibrv4pc1km18w8i0iiwklhpn6h9lc-tar-1.35.nix).out} ${(import ../store/q8sb66r0q7l58drjj8wdqlf2808abkar-patch-2.7.6.nix).out} ${(import ../store/f60dfz81yizjj1j5x7pzdcmmhc38yr1v-zstd-1.5.6.nix).out}";
}
