# Generated by guix-transfer
builtins.derivation {
  name = "rust-core-foundation-0.9.4.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-keGV4JGpPEb3EC7HgYoqo5Th4XccOrSCWWP6A+Ra+48=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-core-foundation-0.9.4.tar.gz/sha256/13zvbbj07yk3b61b8fhwfzhy35535a583irf23vlcg59j7h9bqci";
}
