# Generated by guix-transfer
builtins.derivation {
  name = "rust-pep440-rs-0.6.6.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-Rm6toxecLgacqJe5kAbLsz+BYpDq7sYkZO6pB+Iq44U=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/pep440_rs/0.6.6/download";
}
