# Generated by guix-transfer
builtins.derivation {
  name = "unzip60.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-A22WmRZG0ESe0KqVLk++IbR2zplKvCduSdMOaGcIvTc=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://downloads.sourceforge.net/infozip/UnZip%206.x%20%28latest%29/UnZip%206.0/unzip60.tar.gz";
}
