# Generated by guix-transfer
builtins.derivation {
  name = "typogrify-2.1.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-8KoATpgDKm5r5MnaZefrcVDjbKO/UIrbzagrTQA+Ye4=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://files.pythonhosted.org/packages/source/t/typogrify/typogrify-2.1.0.tar.gz";
}
