# Generated by guix-transfer
builtins.derivation {
  name = "bash52-021";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-gzS4gRetBHWY8jWBrrDGbAJIzdd6vDtOJZEzqjB2UM0=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/bash52-021/sha256/1kahfqqalcwi4m73pg3ssz6lh0kcqsqax09myac7a15d2y0vhd43";
}
