# Generated by guix-transfer
builtins.derivation {
  name = "groff-1.22.4.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-5457TLfewxCEkAT6iIR8RHAejRM7XUwTBX2HbButApM=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://ftp.gnu.org/gnu/groff/groff-1.22.4.tar.gz";
}
