# Generated by guix-transfer
builtins.derivation {
  name = "iso8601-1.0.2.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-J/UDIg5oRdnblU+yErlbA2LYt+bBsjJqhwYcPek1lLE=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/iso8601-1.0.2.tar.gz/sha256/1ccl6plks706hxm35cn1wsvxhqh3bfwi5cjgjpdxjib81qi07x97";
}
