# Generated by guix-transfer
builtins.derivation {
  name = "rust-strsim-0.11.1.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-fai1c2hF2fL8uDfqXZ4mKFZLOwQ6cJSKPwt3iDjF+08=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-strsim-0.11.1.tar.gz/sha256/0kzvqlw8hxqb7y598w1s0hxlnmi84sg5vsipp3yg5na5d1rvba3x";
}
