# Generated by guix-transfer
builtins.derivation {
  name = "rust-windows-implement-0.60.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-pH/d0TrwgpDmf0rKv0tFn2R1UnGPaDp7QV0pCsdEqDY=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/windows-implement/0.60.0/download";
}
