# Generated by guix-transfer
builtins.derivation {
  name = "elementpath-5.0.4.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-he2TVl1ulK76FgsS82sSy+S+a/m73ga4DyxclIKaJfs=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://files.pythonhosted.org/packages/source/e/elementpath/elementpath-5.0.4.tar.gz";
}
