# Generated by guix-transfer
builtins.derivation {
  name = "binutils-mesboot-2.20.1a";
  system = "x86_64-linux";
  builder = "${import ../store/p5v431hpxdm5qffl79h47h8mn2kx8na4-guile-bootstrap-2.0.nix}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${../sources/9p7iwxh6r030nilkb9690djwc7mcf9w2-6qhr7s8431yv7ikcax3l30hw6cim95kc-module-import}"
    "-C"
    "${import ../store/j1niviwm09f99xbgp9rjb267igaazxpz-module-import-compiled.nix}"
    "${../sources/d1nd93maz72bk6jrn81n1g34v59dis4b-binutils-mesboot-2.20.1a-builder}"
  ];
  __phantom_deps = "16wnvy6wf9d34qhdj3qakxrvwkyfban9-gcc-mesboot1-4.6.4 1n598h4cl6p4fbl7ynpqpm71dmxvgz2y-gzip-mesboot-1.2.4 5y9jn40w575kklsdcdgi9vnvhmrhpika-gash-utils-boot-0.2.0 81jyqagp22ff0ihjdyhzipy8vdk1bn2f-binutils-2.20.1a.tar.xz askl34y8khf586j2xc3aiwbl8nvd0asz-glibc-mesboot0-2.2.5 cz73rskq7ivwx0zxyrs539b8iwq1z8a5-bootar-1b g9g4mwzvdws6avx83f30bx9j1750v92l-make-mesboot-3.82 iv04wlr9pm4jgi2a2y5c7ilgzkjviyba-patch-mesboot-2.5.9 nlml8w1f6lfd7981jww2s5nhbzwl5xy4-gash-boot-0.3.0 s9a54k6m9iajhymy6lfcc9iyr010wh0j-linux-libre-headers-bootstrap-0 wlvlml9xyxrq534jkl37yx6jnn3qna8y-binutils-mesboot1-2.20.1a";
}
