# Generated by guix-transfer
builtins.derivation {
  name = "diffutils-3.12.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-fIt/n8hgkUH96pzs6FJJ0whiQ5H/Yd7a9Sj8szdyff0=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/diffutils-3.12.tar.xz/sha256/1zbxf8vv7z18ypddwqgzj51n426k959fiv4wxbyl34b0r2gpz2vw";
}
