# Generated by guix-transfer
builtins.derivation {
  name = "rust-spin-0.9.8.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-aYDo11ESQfis9K6927H/k4317r6YaRQYxEaNC3Kpamc=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-spin-0.9.8.tar.gz/sha256/0rvam5r0p3a6qhc18scqpvpgb3ckzyqxpgdfyjnghh8ja7byi039";
}
