# Generated by guix-transfer
builtins.derivation {
  name = "qpdf-11.8.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-2TIfX7xQJRgDYwpWBN3F7ZpNk7wCPZp0NqMC58l0Elk=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://downloads.sourceforge.net/qpdf/qpdf/11.8.0/qpdf-11.8.0.tar.gz";
}
