# Generated by guix-transfer
builtins.derivation {
  name = "bash-5.2.37";
  system = "x86_64-linux";
  builder = "${(import ../store/wg6a52r8m6gpqyi8fkg4ckx79a8cssi2-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import''; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; }}"
    "-C"
    "${(import ../store/yb5imn763w97f8dzj9py4yi59mzppw84-module-import-compiled.nix).out}"
    "${builtins.path { name = ''bash-5.2.37-builder''; path = ./../sources/ld8g723ldy2w8idg4cp1j917187x4ya9-bash-5.2.37-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import"; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; })
    (builtins.path { name = "bash-5.2.37-builder"; path = ./../sources/ld8g723ldy2w8idg4cp1j917187x4ya9-bash-5.2.37-builder; })
  ];
  outputs = ["doc" "include" "out"];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/q2ay899c980awfsa9i7q5gf4qw5805mc-bash-5.2.tar.zst.nix).out} ${(import ../store/31ashainmlh2b95va2y34x2ls492xa1y-grep-3.11.nix).out} ${(import ../store/77m8plccwy1qqnz2s68v4g85r1qavby9-gcc-14.3.0.nix).out} ${(import ../store/j923mwirlxgbwz6lli9ys717bz5is3c0-bash-minimal-5.2.37.nix).out} ${(import ../store/1b09hlnii4m7l8d639xz3qjz2jrl2gd4-findutils-4.10.0.nix).out} ${(import ../store/26vsxzribmgfd5hw4d563dp1lhh8i67n-coreutils-9.1.nix).out} ${(import ../store/5ga5qq54wfy3ap0p53d35pa1n5y2d6dh-gzip-1.14.nix).out} ${(import ../store/rpliil4n64nif99wmscdf6000ksl9wlr-linux-libre-headers-6.12.17.nix).out} ${(import ../store/dnz4i3qgxdyw13z0aivi2gqcfn36nwzp-binutils-2.44.nix).out} ${(import ../store/pf3jksxkmrqnpnmma1wy14749hpn8npv-bzip2-1.0.8.nix).out} ${(import ../store/hdad4zwl98nl0hchzl9mkj6a0x28dvg9-tar-1.35.nix).out} ${(import ../store/xl31iqcfsavmw028lc04l6x2bvvzh35d-xz-5.4.5.nix).out} ${(import ../store/ydzjyx8bnxg5bng39m7nx5mn82kjaws4-make-4.4.1.nix).out} ${(import ../store/x0kbibmav8m6sddzp33v3qj0nlbjxfpa-sed-4.9.nix).out} ${(import ../store/0476sgzgnnwf85x8x27y7ichj72l3n3y-diffutils-3.12.nix).out} ${(import ../store/hqb17fm26sgvv4jcy2y2ca80bbg7rw85-glibc-2.41.nix).static} ${(import ../store/cxaw02yr7074xva2bwi8jir3ddmpnj0f-gawk-5.3.0.nix).out} ${(import ../store/hqb17fm26sgvv4jcy2y2ca80bbg7rw85-glibc-2.41.nix).out} ${(import ../store/wcjh64132wfjnxg2g22iv0gbnxcnpvfg-readline-8.2.13.nix).out} ${(import ../store/9dxbxqpc8dfiaqk5cx7ddrjn60vfgc9a-file-5.46.nix).out} ${(import ../store/k6phbn4vk739m795r8j61scq8q5sh8af-zstd-1.5.6.nix).out} ${(import ../store/ff6y99k1hy4iahyijz31kpyjyr9d5diq-ncurses-6.2.20210619.nix).out} ${(import ../store/lsj1cm30cfamf2kjwgr55cndm6krf71d-ld-wrapper-0.nix).out} ${(import ../store/r3k6250656z966lc83x9f64qrzhiy2n8-patch-2.7.6.nix).out}";
}
