# Generated by guix-transfer
builtins.derivation {
  name = "rust-string-cache-0.8.9.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-v3dro/p0+Dv0tjw9y7+CFz2yYy7YRSyy2JHTP0Wd5w8=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/string_cache/0.8.9/download";
}
