# Generated by guix-transfer
builtins.derivation {
  name = "aiosignal-1.4.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-9H7s2UaAg8ICnMmZRVAst3CLCCwjL5rKZdoUcVeyUcc=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/aiosignal-1.4.0.tar.gz/sha256/1isin9bp256scp59lbr35h48nw5p5i84b6f9kh1c50w08vcyqzpl";
}
