# Generated by guix-transfer
builtins.derivation {
  name = "ld-wrapper-0";
  system = "x86_64-linux";
  builder = "${(import ../store/0wsxd5g0xbxncz609bqq5hbg48hx8cpm-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/69fricvrgmnbmbm6hi7j08m4cvagza7h-module-import-compiled.nix).out}"
    "${builtins.path { name = ''ld-wrapper-0-builder''; path = ./../sources/kyjsilc62yfilfww3h334bm7iqj2pdnx-ld-wrapper-0-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "ld-wrapper-0-builder"; path = ./../sources/kyjsilc62yfilfww3h334bm7iqj2pdnx-ld-wrapper-0-builder; })
    (builtins.path { name = "ld-wrapper.in"; path = ./../sources/qsw2fycvyk1w029yn82ps1657h4cywcp-ld-wrapper.in; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/w4766awwnaqp9dzy41m80fax4k8jam1b-libunistring-1.3.nix).out} ${(import ../store/vdk1azd9bqhz63jaaniabg8i9rivqk7r-bash-minimal-5.2.37.nix).out} ${(import ../store/qjnbgq7m6k1qcqvzz5xnyn4nmb6xwj7q-binutils-2.44.nix).out} ${(import ../store/f1zcs0qndkvknani38ivmp300644j57a-libgc-8.2.8.nix).out}";
}
