# Generated by guix-transfer
builtins.derivation {
  name = "rust-stable-deref-trait-1.2.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-qPEScpUS+ORC2B+VqKfd8rfGuKGm9QmpWGQUKzDKstM=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-stable-deref-trait-1.2.0.tar.gz/sha256/1lxjr8q2n534b2lhkxd6l6wcddzjvnksi58zv11f9y0jjmr15wd8";
}
