# Generated by guix-transfer
builtins.derivation {
  name = "rust-vcpkg-0.2.15.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-rM1Opi97t6gv4jBm+wlX1I72d/buuCFfNy9S5IuzJCY=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/vcpkg/0.2.15/download";
}
