# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://github.com/KhronosGroup/glslang"; rev = "vulkan-sdk-1.4.321.0"; hash = "sha256-sPc+G7/ua7LQ7scuSvqWs7Q7Q+gFvXQ5wGQsEXbWH6w="; name = "glslang-1.4.321.0-checkout"; fetchSubmodules = false; }
