# Generated by guix-transfer
builtins.derivation {
  name = "rust-pyo3-macros-0.19.2.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-3+tMmVl+E2Uoxt19Xj3lQ00c6vSHQ2o/A7LVa2/J79E=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/pyo3-macros/0.19.2/download";
}
