# Generated by guix-transfer
builtins.derivation {
  name = "rust-futures-task-0.3.31.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-+Q99zgci6VEE/LCVWFkQwJdyUvKG41S14704kCzZmYg=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/futures-task/0.3.31/download";
}
