# Generated by guix-transfer
builtins.derivation {
  name = "re2c-4.2.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-ydwrJPNA0TWgehrGP/U/f490mX/tWk6RMqZAUNvD2h8=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://github.com/skvadrik/re2c/releases/download/4.2/re2c-4.2.tar.xz";
}
