# Generated by guix-transfer
builtins.derivation {
  name = "boost-0001-unordered-fix-copy-assign.patch";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-xuBEKfvxYp8Q9FbUfZz9oaicSx8kJmXLTAkc2EsNRiY=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://www.boost.org/patches/1_83_0/0001-unordered-fix-copy-assign.patch";
}
