# Generated by guix-transfer
builtins.derivation {
  name = "ld-wrapper-boot3-0";
  system = "x86_64-linux";
  builder = "${(import ../store/8ldwd1vqvlrg2lvjxfyqm5lg0v2v0i76-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/wn2s4pb2x5vf1g05a54v1l4laaycqpqd-module-import-compiled.nix).out}"
    "${builtins.path { name = ''ld-wrapper-boot3-0-builder''; path = ./../sources/pvsnn9d2ia5r1gr4rcmyqc4a5b110038-ld-wrapper-boot3-0-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "ld-wrapper.in"; path = ./../sources/qsw2fycvyk1w029yn82ps1657h4cywcp-ld-wrapper.in; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "ld-wrapper-boot3-0-builder"; path = ./../sources/pvsnn9d2ia5r1gr4rcmyqc4a5b110038-ld-wrapper-boot3-0-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/8apxp1kylcsgi99alzbffx5pf0x1zpnr-binutils-2.44.nix).out} ${(import ../store/jk15pcgb9a52h9rfkh41rz1x9n2sv2ka-bash-mesboot-5.2.37.nix).out}";
}
