# Generated by guix-transfer
builtins.derivation {
  name = "rust-serial-test-derive-0.5.1.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-sqzW3v7dtB62C7Ro+IJdDP0MKna8A7/SNbah3E9qGtU=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-serial-test-derive-0.5.1.tar.gz/sha256/1m8sd97xr8dn6p9by0xwfqm0rz8cbn1ghs5l1fv1xd6xzvgddb5j";
}
