# Generated by guix-transfer
builtins.derivation {
  name = "rust-globset-0.4.16.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-VKECjfxfXfXailanPmwVPJqXCOxXIyRwcDWSo/GOSfU=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-globset-0.4.16.tar.gz/sha256/1xa9ivqs74imf1q288spxh49g6iw2mn3x9snibdgapazzj6h58al";
}
