# Generated by guix-transfer
builtins.derivation {
  name = "Module-Build-0.4231.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-fg9MaSwXQMGshOoU1+o9i8eYsvsmwJh3Ip4E9DCytxc=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/Module-Build-0.4231.tar.gz/sha256/05xpn8qg814y49vrih16zfr9iiwb7pmdf57ahjnc2h0p5illq3vy";
}
