# Generated by guix-transfer
builtins.derivation {
  name = "pytest_subtests-0.14.2.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-cVSoZl/VKO5wp20AIWpE0TncPJyDUhoPd597CtT4AN4=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://files.pythonhosted.org/packages/source/p/pytest_subtests/pytest_subtests-0.14.2.tar.gz";
}
