# Generated by guix-transfer
builtins.derivation {
  name = "rust-rustls-pemfile-2.2.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-3OMU5f7j85lT1Gu2O7ikbUDC+Pt8xaO2yrK96XIdblA=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-rustls-pemfile-2.2.0.tar.gz/sha256/0l3f3mrfkgdjrava7ibwzgwc4h3dljw3pdkbsi9rkwz3zvji9qyw";
}
