# Generated by guix-transfer
builtins.derivation {
  name = "rust-futures-util-0.3.31.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-n6CDFbthIIjMORJJ79w7x3U28WyR9s9JXm++hbIKSoE=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-futures-util-0.3.31.tar.gz/sha256/10aa1ar8bgkgbr4wzxlidkqkcxf77gffyj8j7768h831pcaq784z";
}
