# Generated by guix-transfer
builtins.derivation {
  name = "rust-rfc2047-decoder-1.0.6.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-vDZUXRAhRWp1G1c1F8tS6MM5svZi5rJ3jvYpKCZ43ik=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/rfc2047-decoder/1.0.6/download";
}
