# Generated by guix-transfer
builtins.derivation {
  name = "rust-yoke-0.7.5.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-Eg5q75qmKePU9S3IzEOgFcdyQZTJffr0UYDS2vK3f0A=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-yoke-0.7.5.tar.gz/sha256/0h3znzrdmll0a7sglzf9ji0p5iqml11wrj1dypaf6ad6kbpnl3hj";
}
