# Generated by guix-transfer
builtins.derivation {
  name = "krb5-1.21.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-afiq/4VISDLfZ6S7rNmbklm9laq4xlH7vmXNyWIOqTs=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://web.mit.edu/kerberos/dist/krb5/1.21/krb5-1.21.tar.gz";
}
