# Generated by guix-transfer
builtins.derivation {
  name = "rust-language-tags-0.3.2.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-1DRZZLsUJIR5exYfRzpQOkNN53FJ3Yx0J3iMbhM3k4g=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/language-tags/0.3.2/download";
}
