# Generated by guix-transfer
builtins.derivation {
  name = "rust-url-2.5.4.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-Mvi2hsrdFHP0vQEXpdKNNrGt44Tqm1BpocQK7+1/2mA=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-url-2.5.4.tar.gz/sha256/0q6sgznyy2n4l5lm16zahkisvc9nip9aa5q1pps7656xra3bdy1j";
}
