# Generated by guix-transfer
builtins.derivation {
  name = "guile-pipe-0.0.0-0.0746ec3-checkout";
  system = "x86_64-linux";
  builder = "builtin:git-download";
  outputHash = "sha256-tDrA3PRrJKU8ukQ6O2dlkA5hiOXoECzOQPpx72DmDw0=";
  outputHashAlgo = "sha256";
  outputHashMode = "recursive";
  commit = "0746ec38d19d844dff0c6f62f209b2b6c8d8872e";
  impureEnvVars = "http_proxy https_proxy LC_ALL LC_MESSAGES LANG COLUMNS";
  preferLocalBuild = "1";
  "recursive?" = "#f";
  url = "\"https://github.com/joshwalters/guile-pipe\"";
}
