# Generated by guix-transfer
builtins.derivation {
  name = "types_python_dateutil-2.9.0.20250708.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-zNvXXastbJaWw1BXnzTP/iwoHkxfJ6WFsqJDjdHVyKs=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/types_python_dateutil-2.9.0.20250708.tar.gz/sha256/1ay8sp8qshx2na2sa9sz9hg2hb7yrws9ymshqfb9cv1dmdfxgnyc";
}
