# Generated by guix-transfer
builtins.derivation {
  name = "kexec-tools-2.0.31.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-io81Ddxm4ckFo6tSWn6bqWyB4E5w72k5ewFVtnuSLDE=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://www.kernel.org/pub/linux/utils/kernel/kexec/kexec-tools-2.0.31.tar.xz";
}
