# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://github.com/thepowersgang/mrustc"; rev = "06b87d1af49d2db3bd850fdee8888055dd540dd1"; hash = "sha256-buIP5xckNgkgmn4jnTh/hZDgFUSe5P08+GWNYtpQ3tQ="; name = "mrustc-0.11.2-1.06b87d1-checkout"; fetchSubmodules = false; }
