# Generated by guix-transfer
builtins.derivation {
  name = "binutils-mesboot-2.20.1a";
  system = "x86_64-linux";
  builder = "${(import ../store/8ldwd1vqvlrg2lvjxfyqm5lg0v2v0i76-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import''; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; }}"
    "-C"
    "${(import ../store/2sjrq5xy90chdrmvgc9fprq5bnz22gqi-module-import-compiled.nix).out}"
    "${builtins.path { name = ''binutils-mesboot-2.20.1a-builder''; path = ./../sources/ki319w1jbsgiydiy4a6hnxsk3b83bb46-binutils-mesboot-2.20.1a-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import"; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; })
    (builtins.path { name = "binutils-mesboot-2.20.1a-builder"; path = ./../sources/ki319w1jbsgiydiy4a6hnxsk3b83bb46-binutils-mesboot-2.20.1a-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/zpb35bqsysimci3v21ac9d7mn3v66nk6-linux-libre-headers-bootstrap-0.nix).out} ${(import ../store/x3sicdg21l237vlf6yh2yw8pjv07kz9z-binutils-2.20.1a.tar.xz.nix).out} ${(import ../store/a8fx0vgr7j5rqdbaxz8pf682nsp0kk25-binutils-mesboot1-2.20.1a.nix).out} ${(import ../store/nb7fnfskh95fhzcp3y5vvigrjg6l0wyp-patch-mesboot-2.5.9.nix).out} ${(import ../store/27dv0nikhia0vgv9g862nvgxbnazmlhf-bootar-1b.nix).out} ${(import ../store/ggqwrryaf2pvdwmx19vgvmjf3g4zxk86-gcc-mesboot1-4.6.4.nix).out} ${(import ../store/4syf9fh7jimn9kaz43jqns5binkz3sl8-glibc-mesboot0-2.2.5.nix).out} ${(import ../store/i8ddd0yhv545vkzf8z679pm5lvk3g3yc-gash-boot-0.3.1.nix).out} ${(import ../store/6xh3dcbzdyplbqzgvqj9vrhnx7y45bba-gash-utils-boot-0.2.0.nix).out} ${(import ../store/fr8i9nz1l56fbrhf559zvwgavlyfw78v-gzip-mesboot-1.2.4.nix).out} ${(import ../store/2gb1abz90r2ma189rjfc4pyr0apli8gv-make-mesboot-3.82.nix).out}";
}
