# Generated by guix-transfer
builtins.derivation {
  name = "rust-gobject-sys-0.19.8.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-Lml+JS1uBBb9HZ4Wm9pRwPHJJgJsOcoh++ixu1w7i54=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/gobject-sys/0.19.8/download";
}
