# Generated by guix-transfer
builtins.derivation {
  name = "vulkan-loader-1.4.321.0-checkout";
  system = "x86_64-linux";
  builder = "builtin:git-download";
  outputHash = "sha256-i06il1GRkjSlhY36XpIUCcd1Wy+If+Eennzbb//1dzk=";
  outputHashAlgo = "sha256";
  outputHashMode = "recursive";
  commit = "vulkan-sdk-1.4.321.0";
  impureEnvVars = "http_proxy https_proxy LC_ALL LC_MESSAGES LANG COLUMNS";
  preferLocalBuild = "1";
  "recursive?" = "#f";
  url = "\"https://github.com/KhronosGroup/Vulkan-Loader\"";
}
