# Generated by guix-transfer
builtins.derivation {
  name = "gcc-14.3.0.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-4Nx3KXYlYxrI5Q+pL//v6Jmk63AlktpcMu8E4ik6yjo=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/gcc-14.3.0.tar.xz/sha256/0fna78ly417g69fdm4i5f3ms96g8xzzjza8gwp41lqr5fqlpgp70";
}
