# Generated by guix-transfer
builtins.derivation {
  name = "p11-kit-0.24.1.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-2L54Pv1c1K5TTO5BMjOOP0DxgsMgXSOyAAlOyF+qrvg=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/p11-kit-0.24.1.tar.xz/sha256/1y5fm9gwhkh902r26p90qf1g2h1ziqrk4hgf9i9sxm2wzlz7ignq";
}
