# Generated by guix-transfer
builtins.derivation {
  name = "gcc-14.3.0.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-4Nx3KXYlYxrI5Q+pL//v6Jmk63AlktpcMu8E4ik6yjo=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://ftp.gnu.org/gnu/gcc/gcc-14.3.0/gcc-14.3.0.tar.xz";
}
