# Generated by guix-transfer
builtins.derivation {
  name = "tzdata-2025.1.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-JIlJCeiM2yi9FjbGiHgB32TLSFvVk/L9g+8pB1qB1pQ=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://files.pythonhosted.org/packages/source/t/tzdata/tzdata-2025.1.tar.gz";
}
