# Generated by guix-transfer
builtins.derivation {
  name = "bash52-002";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-RcxeG4dlUO7pb5W/+zbEG2y3wH0z9nHbVjRAXNAP17g=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/bash52-002/sha256/1f6p1z85qh1lavdp3xikgp0bfv0vqhvgpgwmdzlywl35hwdmxk25";
}
