# Generated by guix-transfer
builtins.derivation {
  name = "rust-idna-adapter-1.2.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-2sod8clXMgss8TmsYee9ZP7TBMUEDfAAp0WqHeO073E=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/idna_adapter/1.2.0/download";
}
