# Generated by guix-transfer
builtins.derivation {
  name = "python-tzlocal-5.2-checkout";
  system = "x86_64-linux";
  builder = "builtin:git-download";
  outputHash = "sha256-x9f709Kb3r1AiwTAQV1cvHhzUpZHKaWsRII77Uoc6qo=";
  outputHashAlgo = "sha256";
  outputHashMode = "recursive";
  commit = "5.2";
  impureEnvVars = "http_proxy https_proxy LC_ALL LC_MESSAGES LANG COLUMNS";
  preferLocalBuild = "1";
  "recursive?" = "#f";
  url = "\"https://github.com/regebro/tzlocal\"";
}
