# Generated by guix-transfer
builtins.derivation {
  name = "graphene-1.10.8-checkout";
  system = "x86_64-linux";
  builder = "builtin:git-download";
  outputHash = "sha256-iNMNzGHTNZ6YXRRNRYtGCtWMrYAPvhngAn4AkC+LQKE=";
  outputHashAlgo = "sha256";
  outputHashMode = "recursive";
  commit = "1.10.8";
  impureEnvVars = "http_proxy https_proxy LC_ALL LC_MESSAGES LANG COLUMNS";
  preferLocalBuild = "1";
  "recursive?" = "#f";
  url = "\"https://github.com/ebassi/graphene.git\"";
}
