# Generated by guix-transfer
builtins.derivation {
  name = "libusb-1.0.25.tar.bz2";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-iijvGXp5frrCcC8JXoGXXisCsu7/J3T6kJx4p071CEk=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/libusb-1.0.25.tar.bz2/sha256/0j88ym7afy4wj3x789zzxsr04asyjy0mw29gf31blzkrg8cyya4a";
}
