# Generated by guix-transfer
builtins.derivation {
  name = "libXtst-1.2.5.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-tQ1MJblwCadEcGwQOcWY9NjmSRDJ/eOBmU4criNdkkI=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/libXtst-1.2.5.tar.xz/sha256/0hljblisw72fk60y7zf9214ydn7lk32kj43cf12af2bhp4jlq3dm";
}
