# Generated by guix-transfer
builtins.derivation {
  name = "gcc-11.4.0.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-Py2yIrAH6KSiPNW6VnJu8I6LHx6yBV7nLBQCzqc6jdk=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/gcc-11.4.0.tar.xz/sha256/1ncd7akww0hl5kkmw1dj3qgqp3phdrr5dfnm7jia9s07n0ib4b9z";
}
