# Generated by guix-transfer
builtins.derivation {
  name = "bash52-029";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-Elyss35iVHGSSz7gbFTLG/IbO3/g5WnSSmgbDsSimYc=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/bash52-029/sha256/11wrlb20w6v89b96krg0gwxipwhvrda6rq1y9f972m32gsrsqp0j";
}
