# Generated by guix-transfer
builtins.derivation {
  name = "rust-minimal-lexical-0.2.1.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-aDVMXGvTbXP/P+zrBe+lm2rLdiZhf0livjIqgl5h95o=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-minimal-lexical-0.2.1.tar.gz/sha256/16ppc5g84aijpri4jzv14rvcnslvlpphbszc7zzp6vfkddf4qdb8";
}
