# Generated by guix-transfer
builtins.derivation {
  name = "rust-lazy-static-1.5.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-u9K8tMlj8t2uBqLvx+nzWRMSRzxQxmheHymAaDFuZv4=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/lazy_static/1.5.0/download";
}
