# Generated by guix-transfer
builtins.derivation {
  name = "binutils-mesboot-2.20.1a";
  system = "x86_64-linux";
  builder = "${(import ../store/3sgvmyxar0bp0r707sgivngr256jlw8k-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import''; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; }}"
    "-C"
    "${(import ../store/f1pxw9ip8s5g4ka338rz03kza9ip49mz-module-import-compiled.nix).out}"
    "${builtins.path { name = ''binutils-mesboot-2.20.1a-builder''; path = ./../sources/mfrk3j6920dvcsgr98acx4c4kss8d305-binutils-mesboot-2.20.1a-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import"; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; })
    (builtins.path { name = "binutils-mesboot-2.20.1a-builder"; path = ./../sources/mfrk3j6920dvcsgr98acx4c4kss8d305-binutils-mesboot-2.20.1a-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/xvcs6bjwxn94js3m8vzy54xrkbhp6v2k-binutils-2.20.1a.tar.xz.nix).out} ${(import ../store/j785pn7gg6dhcm2wka5cdlijapvfrn1p-linux-libre-headers-bootstrap-0.nix).out} ${(import ../store/lr9ya21fn56knxaamc7wqds2c4valcfb-patch-mesboot-2.5.9.nix).out} ${(import ../store/xmhwxb82l5x07947k7caihxaxn0ai41x-gash-utils-boot-0.2.0.nix).out} ${(import ../store/fjmvzg51h4pk1ql93kknpf6f9hvvil5b-bootar-1b.nix).out} ${(import ../store/nsb2k7jhx9h6f4gm500bbigkwm827j4v-gcc-mesboot1-4.6.4.nix).out} ${(import ../store/gvvzwfdbb0nqnzj2knggj53cxqhc9fsn-gzip-mesboot-1.2.4.nix).out} ${(import ../store/pa53m4v2xxzv6q5akyj2f37m1v32lxlq-make-mesboot-3.82.nix).out} ${(import ../store/vb87rfqy4f7q9pcdm8n0iigbpxj7slq0-glibc-mesboot0-2.2.5.nix).out} ${(import ../store/szbj0pn2jc40qja0n49zsgx5z9h7x6dd-binutils-mesboot1-2.20.1a.nix).out} ${(import ../store/dgxgix2wsjrl9gbscq5p6sfkwzw0rlfp-gash-boot-0.3.1.nix).out}";
}
