# Generated by guix-transfer
builtins.derivation {
  name = "rust-serial-test-derive-0.5.1.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-sqzW3v7dtB62C7Ro+IJdDP0MKna8A7/SNbah3E9qGtU=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/serial_test_derive/0.5.1/download";
}
