# Generated by guix-transfer
builtins.derivation {
  name = "file-boot0-5.46";
  system = "x86_64-linux";
  builder = "${(import ../store/3sgvmyxar0bp0r707sgivngr256jlw8k-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import''; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; }}"
    "-C"
    "${(import ../store/f1pxw9ip8s5g4ka338rz03kza9ip49mz-module-import-compiled.nix).out}"
    "${builtins.path { name = ''file-boot0-5.46-builder''; path = ./../sources/rh4wfc3f3185gsnnf8kxv022sspalj8y-file-boot0-5.46-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import"; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; })
    (builtins.path { name = "file-boot0-5.46-builder"; path = ./../sources/rh4wfc3f3185gsnnf8kxv022sspalj8y-file-boot0-5.46-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/qz2i6v5yrdiji10dbjhi7cma0vw2mslk-gcc-mesboot-4.9.4.nix).out} ${(import ../store/3cgm50j9hgngvv7dwzl9z12jv6rn01h6-coreutils-mesboot-9.1.nix).out} ${(import ../store/767p3xlb4xkybb0w5f1ibahkb8c8dga5-bash-mesboot-5.2.37.nix).out} ${(import ../store/6q4wczw41fysqyy94zkv5fv8sya0jxpp-patch-mesboot-2.5.9.nix).out} ${(import ../store/pnn5ld33kqhc7gmjqm9zixisna2ggs0p-glibc-mesboot-2.16.0.nix).out} ${(import ../store/5miw6nlkh03k5i48x0qym2bc9p6lhwrx-gawk-mesboot-3.1.8.nix).out} ${(import ../store/6qspdcx199d7sqqr7v5krd6qmb478ifq-grep-mesboot-3.11.nix).out} ${(import ../store/wszhslshv1jd5bwgisw25hwiqw4q2yzy-file-5.46.tar.gz.nix).out} ${(import ../store/730yn4856ykv2306b65pbq3rcnyngi7f-gzip-mesboot-1.2.4.nix).out} ${(import ../store/f5ycya9m4zs53gqi76p3xv8xngaskgzp-gcc-mesboot-wrapper-4.9.4.nix).out} ${(import ../store/njaqylj1hfrg3zzand13rijp4mfqjbmz-make-mesboot-3.82.nix).out} ${(import ../store/jfla56j63iqmbqvvag0nmh4iqj6j82ry-xz-mesboot-5.4.5.nix).out} ${(import ../store/2lpk6b0s00wrgwfz69i6cr1g5n7v1ynw-sed-mesboot-4.8.nix).out} ${(import ../store/by8agbq5llk1j14z7mkjvyp97ih97vbx-tar-mesboot-1.35.nix).out} ${(import ../store/pk6c369qd9vkzrcq1sv3cxpcc5lxrdrb-make-boot0-4.4.1.nix).out} ${(import ../store/fxnnbmlc05zil82j9cyi8r84rhsqk1xh-binutils-mesboot-2.20.1a.nix).out}";
}
