# Generated by guix-transfer
builtins.derivation {
  name = "attr-2.5.1.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-uuHGlJslig1oABNnzgx0HOvazdO2KWXRfl6yPNeK2vg=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/attr-2.5.1.tar.gz/sha256/1y6sibbkrcjygv8naadnsg6xmsqwfh6cwrqk01l0v2i5kfacdqds";
}
