# Generated by guix-transfer
builtins.derivation {
  name = "linux-libre-headers-stripped-4.14.67-i686-linux.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-Gs2Pg+J9L6wxGlynjpvxGpoWOLgkaYcNXIVMTnr6omo=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://ftpmirror.gnu.org/guix/bootstrap//i686-linux/20190815/linux-libre-headers-stripped-4.14.67-i686-linux.tar.xz";
}
