# Generated by guix-transfer
builtins.derivation {
  name = "rust-js-sys-0.3.77.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-HPrzPGlfxuCAZO+8H3Lsk3QpYU8l7vg6+ULQ4ifDoo8=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-js-sys-0.3.77.tar.gz/sha256/13x2qcky5l22z4xgivi59xhjjx4kxir1zg7gcj0f1ijzd4yg7yhw";
}
