# Generated by guix-transfer
builtins.derivation {
  name = "libunwind-cfa-rsp";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-0mQ6ifCfzXXeZjhKYbO8ncJX/GtNmz2nwiVrWmBYRWM=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/libunwind-cfa-rsp/sha256/0qs5b1h5lsr5qakkv6sddgy5ghlxpjrn2jiqcvg7bkczy24klr6j";
}
