# Generated by guix-transfer
builtins.derivation {
  name = "rust-thread-local-1.1.8.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-i575utATraOAiFTOrHtGgSpkZbo2iFmjfiEAKD0tcZw=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/thread_local/1.1.8/download";
}
