# Generated by guix-transfer
builtins.derivation {
  name = "rust-windows-targets-0.52.6.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-m3JPcnluA2q5DBAh1HgNTT1kispZ5JHmuY5yW4TpmXM=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/windows-targets/0.52.6/download";
}
