# Generated by guix-transfer
builtins.derivation {
  name = "automake-1.16.5.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-8B1YzW2dd/vcqetLvV6tGYgij9tz1veiAfX41rEYtGk=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://ftp.gnu.org/gnu/automake/automake-1.16.5.tar.xz";
}
