# Generated by guix-transfer
builtins.derivation {
  name = "CUnit-2.1-3.tar.bz2";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-9bKRN/hFuwi3fsYFhP23KLTljxAj5vJJpGTvpJpA8hQ=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/CUnit-2.1-3.tar.bz2/sha256/057j82da9vv4li4z5ri3227ybd18nzyq81f6gsvhifs5z0vr3cpm";
}
