# Generated by guix-transfer
builtins.derivation {
  name = "rust-self-cell-1.1.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-wv38JLxWb4OaLaTEKVuC230lokJThn1cZDVau1eZvb4=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-self-cell-1.1.0.tar.gz/sha256/1gmxk5bvnnimcif7v1jk8ai2azfvh9djki545nd86vsnphjgrzf2";
}
