# Generated by guix-transfer
builtins.derivation {
  name = "Python-3.5.9.tar.xz";
  system = "x86_64-linux";
  builder = "${(import ../store/8ldwd1vqvlrg2lvjxfyqm5lg0v2v0i76-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/wn2s4pb2x5vf1g05a54v1l4laaycqpqd-module-import-compiled.nix).out}"
    "${builtins.path { name = ''Python-3.5.9.tar.xz-builder''; path = ./../sources/1vfq090nwggxhsjqp8hawvviyi7vzcad-Python-3.5.9.tar.xz-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "Python-3.5.9.tar.xz-builder"; path = ./../sources/1vfq090nwggxhsjqp8hawvviyi7vzcad-Python-3.5.9.tar.xz-builder; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 0))";
  __phantom_deps = "${(import ../store/56fih5c1cnpskh363gk85bv4mmiskzyx-bootstrap-binaries-0.nix).out} ${(import ../store/pqwm7s3bb2bpfk6s8zw70nwgbikamdc3-Python-3.5.9.tar.xz.nix).out}";
}
