# Generated by guix-transfer
builtins.derivation {
  name = "pathspec-0.12.1.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-pILVFQOhqzOxxnpsOBOiaVPb3HHDHayu+ag4xOKfVxI=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://files.pythonhosted.org/packages/source/p/pathspec/pathspec-0.12.1.tar.gz";
}
