# Generated by guix-transfer
builtins.derivation {
  name = "libgee-0.20.6.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-G/g09eENYMxhJNdO08HdONpkZ4f794ciILi0Bo5HbU0=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/libgee-0.20.6.tar.xz/sha256/0kbd8y70dd5q40i8gxzvhxkn9niqvp0x6knp4ihwqq0dw7sk9y0v";
}
