# Generated by guix-transfer
builtins.derivation {
  name = "markupsafe-3.0.2.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-7lXT7fgBZ+SOoRqSPHOG9Gad9n15lFVDh/hOfYsKK/A=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/markupsafe-3.0.2.tar.gz/sha256/1w1b1a5pskpqhx1mb53rgpv9srplhrrkr4hsl67f8rq1z3nx6mgf";
}
