# Generated by guix-transfer
builtins.derivation {
  name = "rust-asn1-0.20.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-LYuEtOod4r8dzSp1lzfdsyj7ZpWyqV635E/tZ+NAbzI=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/asn1/0.20.0/download";
}
