# Generated by guix-transfer
builtins.derivation {
  name = "IO-HTML-1.00.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-BOKf1fJTXjWp1Hjyd1Rx154tpqPPK9M777Lc14Ea0ho=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://www.cpan.org/authors/id/C/CJ/CJM/IO-HTML-1.00.tar.gz";
}
