# Generated by guix-transfer
builtins.derivation {
  name = "rust-phf-macros-0.11.3.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-+ErARCnBOn/0N4XXWtJ1afKVHOD/0wozISMNsvxychY=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/phf_macros/0.11.3/download";
}
