# Generated by guix-transfer
builtins.derivation {
  name = "rust-tinyvec-1.9.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-CbNmHxfoZSTszUNxqwQpGU4NfACKu0X3p0lbFxlGPHE=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/tinyvec/1.9.0/download";
}
