# Generated by guix-transfer
builtins.derivation {
  name = "rust-rustls-webpki-0.103.1.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-/vi4dpqsz3MJhVeofNGBa0+cfBaBHJx3FCqmlcFvLAM=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/rustls-webpki/0.103.1/download";
}
