# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://github.com/asottile/re-assert"; rev = "v1.1.0"; hash = "sha256-UTXFTD3QOKIzjq05J9Ontv5h9aClOwlPYKFXfDnBWuc="; name = "python-re-assert-1.1.0-checkout"; fetchSubmodules = false; }
