# Generated by guix-transfer
builtins.derivation {
  name = "socksio-1.0.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-+IvrPaW1w4uYkEad5n0MsPnUlLeLEGyhhF+WwQuRxKw=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://files.pythonhosted.org/packages/source/s/socksio/socksio-1.0.0.tar.gz";
}
