# Generated by guix-transfer
builtins.derivation {
  name = "pylsqpack-0.3.22.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-tn9xGzyDcNn0D39/U2qmAY2JAPoJ+kn3Lww/E4hs7No=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/pylsqpack-0.3.22.tar.gz/sha256/1npcdj416gqc5zvlkyh9z808k381lrm56zvz1zsdjw437hdp2zxn";
}
