# Generated by guix-transfer
builtins.derivation {
  name = "rust-unicode-ident-1.0.18.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-Wl85QEpdpQcSpMHuzyXpDdYrYTUCt+kl/U5NGbXJZRI=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-unicode-ident-1.0.18.tar.gz/sha256/04k5r6sijkafzljykdq26mhjpmhdx4jwzvn1lh90g9ax9903jpss";
}
