# Generated by guix-transfer
builtins.derivation {
  name = "ld-wrapper-0";
  system = "x86_64-linux";
  builder = "${import ../store/h6j68xwpj7dm4xbrkw5n28k434wlw0g0-guile-3.0.9.nix}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${../sources/zfz0k7p3wv8g31j0ycb3p9s75wpyq3jw-jsxgc979x79h81kzqz9n6cpf5pk4z262-module-import}"
    "-C"
    "${import ../store/li5xpkgwwawrqd9zkdzjlpincr26cmpg-module-import-compiled.nix}"
    "${../sources/r2xryirzn31yhg8frdk7c56raacqrbra-ld-wrapper-0-builder}"
  ];
  __phantom_deps = "6i7xalmqcwlqahjvi3hyx32a7wx8j6r6-binutils-2.41 ij17qzygirhzqd96dzll0s3qlaiqrgkx-libunistring-1.1 wpjgv9skygxi8b96jcqyjfsd2wnwiis0-bash-minimal-5.1.16 y8gjff6kygm92bmrfzwcgly4inlvx0s1-libgc-8.2.4";
}
