# Generated by guix-transfer
builtins.derivation {
  name = "types_setuptools-80.9.0.20250529.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-eeCIugy6IYbI1kmcvT4UOrsULSikSwQsKNMUix41PJE=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://files.pythonhosted.org/packages/source/t/types_setuptools/types_setuptools-80.9.0.20250529.tar.gz";
}
