# Generated by guix-transfer
builtins.derivation {
  name = "libxcb-1.17.0.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-WZ6/mZZxD+pxYi5uGE86itW0PQ5fqMTkBxI8iKWabVU=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/libxcb-1.17.0.tar.xz/sha256/0mbdkajqhg0j0zjc9a2z1qyv9mca797ihvifc9qyl3vijscvz7jr";
}
