# Generated by guix-transfer
builtins.derivation {
  name = "shadow-4.13.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-mv4kXXmi58qsXx7WJRmxdBawV+yJ3zFt8cOTVQL53Sw=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/shadow-4.13.tar.xz/sha256/0b6xz415b4y3y5nk3pw9xibv05kln4cjbmhybyncmrx2g5fj9zls";
}
