# Generated by guix-transfer
builtins.derivation {
  name = "glibc-2.16.0.tar.xz";
  system = "x86_64-linux";
  builder = "${(import ../store/3sgvmyxar0bp0r707sgivngr256jlw8k-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/vqpyw7y1k6p4barzxp5x7j41h8ax7w1b-module-import-compiled.nix).out}"
    "${builtins.path { name = ''glibc-2.16.0.tar.xz-builder''; path = ./../sources/2lib9s5rxkz6k4zx7b07fp7lzzrziw0y-glibc-2.16.0.tar.xz-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "glibc-2.16.0.tar.xz-builder"; path = ./../sources/2lib9s5rxkz6k4zx7b07fp7lzzrziw0y-glibc-2.16.0.tar.xz-builder; })
    (builtins.path { name = "glibc-bootstrap-system-2.16.0.patch"; path = ./../sources/l0zxllys8vx79izgsawxyqw49rd7ishs-glibc-bootstrap-system-2.16.0.patch; })
    (builtins.path { name = "glibc-boot-2.16.0.patch"; path = ./../sources/3vspi3iqk6kfphyl9a408c1s52l095c4-glibc-boot-2.16.0.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 2))";
  __phantom_deps = "${(import ../store/18jfanl2nz6z95cxz7pwryc1h5v0m8cn-glibc-2.16.0.tar.gz.nix).out} ${(import ../store/gx9yhjw5zcfzxm1d3gmfb5sbc64xw6ww-bootstrap-binaries-0.nix).out}";
}
