# Generated by guix-transfer
builtins.derivation {
  name = "rust-textwrap-0.16.2.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-wTVHYVpE3JxFKopTRjis3wcSDUtoR8gXhwXaBjBqMFc=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-textwrap-0.16.2.tar.gz/sha256/0mrhd8q0dnh5hwbwhiv89c6i41yzmhw4clwa592rrp24b9hlfdf1";
}
