# Generated by guix-transfer
builtins.derivation {
  name = "Python-3.5.9.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-wko3xjpn9TvdCcXyh7XP+Oi5j4V780jFd9RU0/dNsEk=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/Python-3.5.9.tar.xz/sha256/0jdh9pvx6m6lfz2liwvvhn7vks7qrysqgwn517fkpxb77b33fjn2";
}
