# Generated by guix-transfer
builtins.derivation {
  name = "bash51-010";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-osjXsnBO7O/3sVA7etlQDqHLbpOT+uvbOs0q/deurio=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/bash51-010/sha256/0amfmvbzsand7bdypylkjdpcp88fa3cplfshn7vyzv2ff2rdgj52";
}
