# Generated by guix-transfer
builtins.derivation {
  name = "libxml2-2.14.6.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/wg6a52r8m6gpqyi8fkg4ckx79a8cssi2-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/3cyx2qfklxdby1cbv7hgdszysi8vy265-module-import-compiled.nix).out}"
    "${builtins.path { name = ''libxml2-2.14.6.tar.zst-builder''; path = ./../sources/b0wmzd1a29sd488ii2lwqikgr9mkq6b6-libxml2-2.14.6.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "libxml2-2.14.6.tar.zst-builder"; path = ./../sources/b0wmzd1a29sd488ii2lwqikgr9mkq6b6-libxml2-2.14.6.tar.zst-builder; })
    (builtins.path { name = "python-libxml2-utf8.patch"; path = ./../sources/kxfhvf4062bhdx037lvp30jy77qllnkj-python-libxml2-utf8.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 1))";
  __phantom_deps = "${(import ../store/snwfvxdyy5mai1bzbxfaxyrhybp511m3-libxml2-2.14.6.tar.xz.nix).out} ${(import ../store/hdad4zwl98nl0hchzl9mkj6a0x28dvg9-tar-1.35.nix).out} ${(import ../store/xl31iqcfsavmw028lc04l6x2bvvzh35d-xz-5.4.5.nix).out} ${(import ../store/k6phbn4vk739m795r8j61scq8q5sh8af-zstd-1.5.6.nix).out} ${(import ../store/r3k6250656z966lc83x9f64qrzhiy2n8-patch-2.7.6.nix).out}";
}
