# Generated by guix-transfer
builtins.derivation {
  name = "selinux-3.4-checkout";
  system = "x86_64-linux";
  builder = "builtin:git-download";
  outputHash = "sha256-gOH8GHTrjBf2SHXSJQMznCHOrKnyLPM4K+9gkF19ldE=";
  outputHashAlgo = "sha256";
  outputHashMode = "recursive";
  commit = "3.4";
  impureEnvVars = "http_proxy https_proxy LC_ALL LC_MESSAGES LANG COLUMNS";
  preferLocalBuild = "1";
  "recursive?" = "#f";
  url = "\"https://github.com/SELinuxProject/selinux\"";
}
