# Generated by guix-transfer
builtins.derivation {
  name = "lmdb-0.9.29-checkout";
  system = "x86_64-linux";
  builder = "builtin:git-download";
  outputHash = "sha256-gyJ4oqY3mN2uyb7z33m3OgCkXNwPHv+WDamBxoi+OSo=";
  outputHashAlgo = "sha256";
  outputHashMode = "recursive";
  commit = "LMDB_0.9.29";
  impureEnvVars = "http_proxy https_proxy LC_ALL LC_MESSAGES LANG COLUMNS";
  preferLocalBuild = "1";
  "recursive?" = "#f";
  url = "\"https://git.openldap.org/openldap/openldap.git\"";
}
