# Generated by guix-transfer
builtins.derivation {
  name = "rust-syn-1.0.109.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-crZBkbJ1tm/+JGnorywc/juvpntSnq15Km0BYIiLQjc=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/syn/1.0.109/download";
}
