# Generated by guix-transfer
builtins.derivation {
  name = "grep-3.11";
  system = "x86_64-linux";
  builder = "${import ../store/p5v431hpxdm5qffl79h47h8mn2kx8na4-guile-bootstrap-2.0.nix}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${../sources/9p7iwxh6r030nilkb9690djwc7mcf9w2-6qhr7s8431yv7ikcax3l30hw6cim95kc-module-import}"
    "-C"
    "${import ../store/j1niviwm09f99xbgp9rjb267igaazxpz-module-import-compiled.nix}"
    "${../sources/rbij4hnh04jrl4cjm40wb368hc17j9a4-grep-3.11-builder}"
  ];
  __phantom_deps = "0pzj3j8xlq4xxwfwca8bwdylvr5jw833-binutils-cross-boot0-2.41 1n598h4cl6p4fbl7ynpqpm71dmxvgz2y-gzip-mesboot-1.2.4 2mm6m2fmp01kz1zsr3cz1165fl1x4ikh-gcc-11.4.0 2wsfmwcjlxd6x3qjf49iv1qrmf0ck2va-sed-boot0-4.8 4wm6xfkfsjrc1k4skj6q80zjljg5ywqd-diffutils-boot0-3.10 57dnnshk74r07grk0q3asigxaiby6vnq-findutils-boot0-4.9.0 6w5jdpf7wjx2xqcbdkqj7rx1yk6sx7wx-file-boot0-5.45 6xkybilz0idp1aav7slkr33h79d50hq5-gcc-mesboot-wrapper-4.9.4 77ra6cj36w9n6yy97wyvcz9nmclkgdzf-grep-3.11.tar.xz 841918rn4cjlgfly0dq78q04h8bqsiir-glibc-2.39-static azibadwmcjxm4qf1jj54xvzjqva694l8-gawk-mesboot-3.1.8 cxfr7hshww80g05zz8mck8x31grvs596-tar-mesboot-1.34 d7p6dv4yzi67nqzwl1440m16x55y0l4p-xz-mesboot-5.4.5 g9g4mwzvdws6avx83f30bx9j1750v92l-make-mesboot-3.82 hgfsha82s5m1smf4x902svxz39v7h57b-perl-boot0-5.36.0 hk4r2k4vrsafzbcfqr8kpkyj1jmnvkga-ld-wrapper-boot0-0 iv04wlr9pm4jgi2a2y5c7ilgzkjviyba-patch-mesboot-2.5.9 kp2jv87p751c0470cyx4avpy87228wyc-patch-boot0-2.7.6 lsl82fa2rfnkn0j22q2wbyr5d1p94344-make-boot0-4.4.1 mfhs66qai2mm45yjznz7rzv9n45222f1-coreutils-mesboot-9.1 mm2arizx2wqdblpzjin8gzd7nkf8xqzj-linux-libre-headers-5.15.49 nbssf9pf7j0dqy0f54kwwqb1nmmmvqhb-sed-mesboot-4.8 nn8dgdsvz40847n2fq49fqb70wm08x4l-gawk-boot0-5.3.0 qhg4vqhjza9dwk64rnj8rqwphibldq7h-tar-boot0-1.34 rjizvrk6a8h0a2p42qjh74wmkpvk6f1h-bzip2-boot0-1.0.8 vwmlz0wkxgqmzbjy86ksiivhyqz5rfn2-ld-wrapper-boot3-0 wpjgv9skygxi8b96jcqyjfsd2wnwiis0-bash-minimal-5.1.16 xx4qhjdd3vkp6h1kvm93p9gj4fz6zly8-grep-mesboot-3.11 xxbly5717sxyshn8akzh0mi9vw4mbppp-glibc-2.39 y47il52bzl8gwwbnla9hb9czlp6drzix-coreutils-boot0-9.1";
}
