# Generated by guix-transfer
builtins.derivation {
  name = "bash";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-b4h9RfoPflnlXG17qGo9jDU2nHr7s6WCm47SJr/vSmY=";
  outputHashAlgo = "sha256";
  outputHashMode = "recursive";
  url = "https://codeberg.org/guix/guix/raw/commit/44f07d1dc6806e97c4e9ee3e6be883cc59dc666e/gnu/packages/bootstrap/i686-linux/bash";
  executable = "1";
}
