# Generated by guix-transfer
builtins.derivation {
  name = "rust-futures-0.3.31.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-ZbwHsai8fIXF8uEQxHbHOJtFVLpyr1fYRF6mOldrCHY=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/futures/0.3.31/download";
}
