# Generated by guix-transfer
builtins.derivation {
  name = "gcc-core-mesboot0-2.95.3";
  system = "x86_64-linux";
  builder = "${(import ../store/8ldwd1vqvlrg2lvjxfyqm5lg0v2v0i76-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import''; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; }}"
    "-C"
    "${(import ../store/2sjrq5xy90chdrmvgc9fprq5bnz22gqi-module-import-compiled.nix).out}"
    "${builtins.path { name = ''gcc-core-mesboot0-2.95.3-builder''; path = ./../sources/2pk5scklhg97qzvign4mwwlr26m8ckc9-gcc-core-mesboot0-2.95.3-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import"; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; })
    (builtins.path { name = "gcc-boot-2.95.3.patch"; path = ./../sources/dl8bywsqbx9wr00van7xshakvxmhsy7f-gcc-boot-2.95.3.patch; })
    (builtins.path { name = "gcc-core-mesboot0-2.95.3-builder"; path = ./../sources/2pk5scklhg97qzvign4mwwlr26m8ckc9-gcc-core-mesboot0-2.95.3-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/09qa2c1idc10kiqrra7gs482l9ad2hdr-binutils-mesboot0-2.20.1a.nix).out} ${(import ../store/nb7fnfskh95fhzcp3y5vvigrjg6l0wyp-patch-mesboot-2.5.9.nix).out} ${(import ../store/27dv0nikhia0vgv9g862nvgxbnazmlhf-bootar-1b.nix).out} ${(import ../store/i8ddd0yhv545vkzf8z679pm5lvk3g3yc-gash-boot-0.3.1.nix).out} ${(import ../store/dnnd97d8z5scpr3bxxr6sgvnks014645-make-mesboot0-3.80.nix).out} ${(import ../store/6xh3dcbzdyplbqzgvqj9vrhnx7y45bba-gash-utils-boot-0.2.0.nix).out} ${(import ../store/qpd2g78g7j441y4mybwwgsi5b5qcmdkh-tcc-boot-0.9.27.nix).out} ${(import ../store/v567lxbp8x4148l161yx1nyskpimk75s-gcc-core-2.95.3.tar.gz.nix).out} ${(import ../store/fr8i9nz1l56fbrhf559zvwgavlyfw78v-gzip-mesboot-1.2.4.nix).out}";
}
