# Generated by guix-transfer
builtins.derivation {
  name = "werkzeug-3.1.3.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-YHI86UXBkyhnl5DjKCzHWKpKYEDkuzMPU9MPpUbUR0Y=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/werkzeug-3.1.3.tar.gz/sha256/0ij7si3aa3ykac7k7fz481h4majqqwn2iqwhjxkji4y18plkqwk0";
}
