# Generated by guix-transfer
builtins.derivation {
  name = "rust-encode-unicode-1.0.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-NKpzZG/7AGuPUUfz3Bgr1LyxkCJ86GH8SkhEv448ssA=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-encode-unicode-1.0.0.tar.gz/sha256/1h5j7j7byi289by63s3w4a8b3g6l5ccdrws7a67nn07vdxj77ail";
}
