# Generated by guix-transfer
builtins.derivation {
  name = "rust-dirs-sys-0.4.1.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-Ug8FpcvTNfrlqZ/3pquGJ1d2YO5c/WqUpqkptS/wMhw=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/dirs-sys/0.4.1/download";
}
