# Generated by guix-transfer
builtins.derivation {
  name = "CPAN-Meta-Requirements-2.140.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-CJhkXo6G8JIvDwUCtQP1kqjrPTF2tP2Hrcx7pR51H6k=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://www.cpan.org/authors/id/D/DA/DAGOLDEN/CPAN-Meta-Requirements-2.140.tar.gz";
}
