# Generated by guix-transfer
builtins.derivation {
  name = "rustc-1.81.0-src.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/c4ay50vfyk7bxiiy4gzz8wp6d6b9qfay-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/7skwz4rdpxxc3s03vb07mqvpxr8s6j1h-module-import-compiled.nix).out}"
    "${builtins.path { name = ''rustc-1.81.0-src.tar.zst-builder''; path = ./../sources/6b72y8gim90rnk4x4kqdkrkcb1yhfh51-rustc-1.81.0-src.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "rust-1.81-fix-riscv64-bootstrap.patch"; path = ./../sources/3ixpbfwc5778npdj8dzbhwnxjjgsh86a-rust-1.81-fix-riscv64-bootstrap.patch; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "rustc-1.81.0-src.tar.zst-builder"; path = ./../sources/6b72y8gim90rnk4x4kqdkrkcb1yhfh51-rustc-1.81.0-src.tar.zst-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 1))";
  __phantom_deps = "${(import ../store/8pwkslrs5l1w7abzp0xh1vivi57fd16b-rustc-1.81.0-src.tar.gz.nix).out} ${(import ../store/3f5ch18ghnzfbkk1iv2rk12j6n37lp51-xz-5.4.5.nix).out} ${(import ../store/8wg103mjrc4gzj8aq9l1ir8yb7nhqvc6-gzip-1.14.nix).out} ${(import ../store/fhskwarrjxl0726s5svlyqabd7i3ipy2-tar-1.35.nix).out} ${(import ../store/bs5jzy6r2zfk2hn9g21h7biwssm56266-patch-2.7.6.nix).out} ${(import ../store/j62jcz2m4jjnvv3z42mdxvs73xp8d95s-zstd-1.5.6.nix).out}";
}
