# Generated by guix-transfer
builtins.derivation {
  name = "git-2.50.0.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-3/PAAOQArOOmO4pvizt2uI7P3/1FBKBKukJINyzewEU=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://www.kernel.org/pub/software/scm/git/git-2.50.0.tar.xz";
}
