# Generated by guix-transfer
builtins.derivation {
  name = "rust-humantime-2.2.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-mxEqzIs630sQeo7CCXfaAnOow4Z2Wj7AIpvVAKFEP58=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-humantime-2.2.0.tar.gz/sha256/17rz8jhh1mcv4b03wnknhv1shwq2v9vhkhlfg884pprsig62l4cv";
}
