# Generated by guix-transfer
builtins.derivation {
  name = "rust-anyhow-1.0.97.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-3P7VatUGyyxoShSXG4hh/cO6qq4xS55fm7Uyy+O6ek8=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/anyhow/1.0.97/download";
}
