# Generated by guix-transfer
builtins.derivation {
  name = "binutils-2.44.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/0wsxd5g0xbxncz609bqq5hbg48hx8cpm-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/69fricvrgmnbmbm6hi7j08m4cvagza7h-module-import-compiled.nix).out}"
    "${builtins.path { name = ''binutils-2.44.tar.zst-builder''; path = ./../sources/hiriln909h4m8ivq0qd8x246rk8g6r32-binutils-2.44.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "binutils-2.44.tar.zst-builder"; path = ./../sources/hiriln909h4m8ivq0qd8x246rk8g6r32-binutils-2.44.tar.zst-builder; })
    (builtins.path { name = "binutils-loongson-workaround.patch"; path = ./../sources/zhx3zch54xs01i4pi5675xfkd4fix9b7-binutils-loongson-workaround.patch; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "binutils-2.41-fix-cross.patch"; path = ./../sources/4432hk9wr0a70vgnxsj8jlfp9k6mnmig-binutils-2.41-fix-cross.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 2))";
  __phantom_deps = "${(import ../store/fl18v8zafk6wpc2yqxrahapqw7l7n073-xz-5.4.5.nix).out} ${(import ../store/pv1ibrv4pc1km18w8i0iiwklhpn6h9lc-tar-1.35.nix).out} ${(import ../store/szll0bl4pv2r9m3fpq7hs98hwwqh8p26-bzip2-1.0.8.nix).out} ${(import ../store/q8sb66r0q7l58drjj8wdqlf2808abkar-patch-2.7.6.nix).out} ${(import ../store/f60dfz81yizjj1j5x7pzdcmmhc38yr1v-zstd-1.5.6.nix).out} ${(import ../store/3ay2f76mz77n73xsxcq716326sxyvx5x-binutils-2.44.tar.bz2.nix).out}";
}
