# Generated by guix-transfer
builtins.derivation {
  name = "libxft-2.3.8";
  system = "x86_64-linux";
  builder = "${import ../store/h6j68xwpj7dm4xbrkw5n28k434wlw0g0-guile-3.0.9.nix}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${../sources/9p7iwxh6r030nilkb9690djwc7mcf9w2-6qhr7s8431yv7ikcax3l30hw6cim95kc-module-import}"
    "-C"
    "${import ../store/sa3fmqj337davd2inpzbd6cbfg3gg964-module-import-compiled.nix}"
    "${../sources/ynl6b4q7bd1mlw519p8ch6nvi696bm3x-libxft-2.3.8-builder}"
  ];
  __phantom_deps = "${import ../store/4iw3qch66b4r3lpvlc2cdrsrmb6l9aqc-libXft-2.3.8.tar.gz.nix} 2mm6m2fmp01kz1zsr3cz1165fl1x4ikh-gcc-11.4.0 2xvh658qxn0zzjfdvxmnnx03b7zd3s6r-fontconfig-minimal-2.14.0 5zl451rnflw1p02wcbrklacb4xdakyyf-ld-wrapper-0 6i7xalmqcwlqahjvi3hyx32a7wx8j6r6-binutils-2.41 841918rn4cjlgfly0dq78q04h8bqsiir-glibc-2.39-static 94797xsj3sc5axm2x6b2d3yfm2g5ix4a-patch-2.7.6 9cz2iahd65m79kfkx0ascad6g83cypag-expat-2.5.0 a3rwd0b10rn2j7ljvhdj1wpmr3iycyk1-grep-3.11 bbf0h3sjxfh7bb2xl7cr3h3jvx1v83rr-file-5.45 cccmzmbcx20w2swy810kqw3hib4xnpas-xz-5.4.5 cz4qsnixq6ifyvpr69bjw4kz172k5vix-sed-4.8 d4wlszcic57z0m3p6mh4wdrya5dqcs09-make-4.4.1 fyxbh7x1jkxcnbwsw7g83wxva5c8b7zk-bzip2-1.0.8 g9czhgpvnrkrx252lhqrz5wapp9x2lbc-findutils-4.9.0 icvmyhfsj88iypsz71cj4jdvrkc9wa7y-zstd-1.5.2 j3n22gyy4cf7ldcnrykysrq6305v4s14-libxcb-1.17.0 kdpnw5xnvq0nx5ksh54imyfcn3m5hcy8-util-macros-1.20.2 kjq9aj5fs30bhj5iyp0k972f15j8mh0v-coreutils-9.1 klcwy3m6f9qmky3zmn1wdy1iajcvnld9-libxdmcp-1.1.5 m7901m67935kyigr9svbmfr08ns2z9qx-pkg-config-0.29.2 mb5qz0ifpbfl9z4sww7a5zbglcvp19jn-diffutils-3.10 mm2arizx2wqdblpzjin8gzd7nkf8xqzj-linux-libre-headers-5.15.49 mr042cl0rzl2gvy4k4in86qb4hs5svwf-tar-1.34 qbkq0lmvv5s8b84b6f34m4m0vd4k1hrp-zlib-1.3 qk8acd4q0qz93gp47ns4hpmjd70pa8j1-libxrender-0.9.12 r2i25w45h5waj9r89vi0y1bl2a1fl3x9-gawk-5.3.0 rzza1l9ird2ar6gm8c17106mx2bib48p-util-linux-2.37.4-lib sczlqn1mmv4s76gzi092g9j51n1vmn8f-libx11-1.8.10 vnhsqrmwgdjxgljm97g3qs1rbgfixky1-freetype-2.13.0 w3ir0agsyjj7jgq79m998b4sg8i69h8k-xorgproto-2024.1 wpjgv9skygxi8b96jcqyjfsd2wnwiis0-bash-minimal-5.1.16 wsdsc15m3jnzb5ps1ily5iifkdvjbnkx-gzip-1.13 xxbly5717sxyshn8akzh0mi9vw4mbppp-glibc-2.39 y3ksw16gbmxyvgp2m4x0mgfjv7cvrghd-libpng-1.6.39 za22ir63n7qzxj4v28di0yx4ah4zmc4z-libxau-1.0.12";
}
