# Generated by guix-transfer
builtins.derivation {
  name = "rust-valuable-0.1.1.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-unPqnPFqJd8MjKoWxRrLk31XEqhCnbeKPuKdXcrNOmU=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/valuable/0.1.1/download";
}
