# Generated by guix-transfer
builtins.derivation {
  name = "rust-expect-test-1.5.1.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-Y69D/0Qx6Ej7R0cqkg8U+nHCTeEyVaVpLpPU6QMCrLA=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-expect-test-1.5.1.tar.gz/sha256/1c5c081ykm4k5rlsam9jw56w4wgs2h7r4aj78zxlis1i8kzl7bv3";
}
