# Generated by guix-transfer
builtins.derivation {
  name = "rust-utf8parse-0.2.2.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-BqveNhFlet9m04PwCwk9f67Mf6VwccziV4ZgyfEBCCE=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-utf8parse-0.2.2.tar.gz/sha256/088807qwjq46azicqwbhlmzwrbkz7l4hpw43sdkdyyk524vdxaq6";
}
