# Generated by guix-transfer
builtins.derivation {
  name = "rust-data-url-0.3.1.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-XCl6HHS3GuKd8Aw+It2VNIIdYOua9aAZKCP6Ks6nDCo=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-data-url-0.3.1.tar.gz/sha256/0ahclz72myi350cs1xcsxdh1v0iljpfj4ghcy2fy46mpfhf7laaw";
}
