# Generated by guix-transfer
builtins.derivation {
  name = "rust-yoke-0.7.5.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-Eg5q75qmKePU9S3IzEOgFcdyQZTJffr0UYDS2vK3f0A=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/yoke/0.7.5/download";
}
