# Generated by guix-transfer
builtins.derivation {
  name = "rust-equivalent-1.0.2.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-h3pKzocTsLzypOfuyCUpwCnx0GGYhtGBRf6pbD/+XA8=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/equivalent/1.0.2/download";
}
