# Generated by guix-transfer
builtins.derivation {
  name = "bzip2-1.0.8.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-q1oDF27hBtPw+pDjgdpHjdrkBZGBU8yiSOaCzQxKImk=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz";
}
