# Generated by guix-transfer
builtins.derivation {
  name = "rust-anstream-0.6.18.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-isxTaZgRlgBiKOKICfdhh1wDJyEKiR6UH0xoOzqZUps=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-anstream-0.6.18.tar.gz/sha256/16sjk4x3ns2c3ya1x28a44kh6p47c7vhk27251i015hik1lm7k4a";
}
