# Generated by guix-transfer
builtins.derivation {
  name = "rust-dyn-clone-1.0.19.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-HHqPuKn79mwfcD/hYYTRDKDunSO+W0Q2QAQIulSpUAU=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-dyn-clone-1.0.19.tar.gz/sha256/01ahm5abl20480v48nxy4ffyx80cs6263q9zf0gnrxpvm6w8yyhw";
}
