# Generated by guix-transfer
builtins.derivation {
  name = "Python-3.11.14.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/0wsxd5g0xbxncz609bqq5hbg48hx8cpm-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/69fricvrgmnbmbm6hi7j08m4cvagza7h-module-import-compiled.nix).out}"
    "${builtins.path { name = ''Python-3.11.14.tar.zst-builder''; path = ./../sources/5xlqdg6q8vj99mqnxkhijzkyzhfhggan-Python-3.11.14.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "python-3-deterministic-build-info.patch"; path = ./../sources/46q4lgbhbqg6bspswcc437bfw0smb9pi-python-3-deterministic-build-info.patch; })
    (builtins.path { name = "python-3-hurd-configure.patch"; path = ./../sources/pdwyhwcr0iyirfgqcmrgj7xvxf3vnvz5-python-3-hurd-configure.patch; })
    (builtins.path { name = "python-3-search-paths.patch"; path = ./../sources/npn8j9gip9c7xk8zh8p53l6sjjpz6454-python-3-search-paths.patch; })
    (builtins.path { name = "python-3.11-fix-tests.patch"; path = ./../sources/v1b3wrk61lbz0qh64j4az1382q7hyfz9-python-3.11-fix-tests.patch; })
    (builtins.path { name = "Python-3.11.14.tar.zst-builder"; path = ./../sources/5xlqdg6q8vj99mqnxkhijzkyzhfhggan-Python-3.11.14.tar.zst-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 4))";
  __phantom_deps = "${(import ../store/fl18v8zafk6wpc2yqxrahapqw7l7n073-xz-5.4.5.nix).out} ${(import ../store/pv1ibrv4pc1km18w8i0iiwklhpn6h9lc-tar-1.35.nix).out} ${(import ../store/jz6biw8x8bwvgs3gf40475li18cp75bk-Python-3.11.14.tar.xz.nix).out} ${(import ../store/q8sb66r0q7l58drjj8wdqlf2808abkar-patch-2.7.6.nix).out} ${(import ../store/f60dfz81yizjj1j5x7pzdcmmhc38yr1v-zstd-1.5.6.nix).out}";
}
