# Generated by guix-transfer
builtins.derivation {
  name = "libffi-3.4.6.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-sN6p3yPIY6elDoJUQPPr/6vWXfFJcQjl1Dd0eEOJWk4=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/libffi-3.4.6.tar.gz/sha256/0kjsi51phx1pskjhhwa9y5fxdazzxgrl0m421sjsfqy84ggskpmh";
}
