# Generated by guix-transfer
builtins.derivation {
  name = "pcre2-10.42.tar.bz2";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-jTbNjLbqKkwrs1j/ZBGwx4hjOipF2rvxrrS3AdG16EA=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/pcre2-10.42.tar.bz2/sha256/0h78np8h3dxlmvqvpnj558x67267n08n9zsqncmlqapans6csdld";
}
