# Generated by guix-transfer
builtins.derivation {
  name = "rust-matches-0.1.10.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-JTIJZleUHC/qnCidNwolCXHGidTxQ3mP9nET7AQgJKU=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/matches/0.1.10/download";
}
