# Generated by guix-transfer
builtins.derivation {
  name = "coverage-7.11.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-FnvVBKwcoq9/87gdJF3+oCksUDLr751mzAin0owbgFA=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/coverage-7.11.0.tar.gz/sha256/0l403f6d59q8rik9vvzb6982qad0zrfj87dqydzsz8hwmh2dayqn";
}
