# Generated by guix-transfer
builtins.derivation {
  name = "libdmx-1.1.5.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-NaTiaosLK0/jZEHcpGNkXD+lLSgqw1IFAaOOqULL908=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://www.x.org/releases/individual/lib/libdmx-1.1.5.tar.xz";
}
