# Generated by guix-transfer
builtins.derivation {
  name = "rust-cfg-expr-0.15.8.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-0GetSLhlCEi5iaWahsbDapldAtK/d41Fw8XVe8JxjwI=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-cfg-expr-0.15.8.tar.gz/sha256/00lgf717pmf5qd2qsxxzs815v6baqg38d6m5i6wlh235p14asryh";
}
