# Generated by guix-transfer
builtins.derivation {
  name = "module-import-compiled";
  system = "x86_64-linux";
  builder = "${import ../store/h6j68xwpj7dm4xbrkw5n28k434wlw0g0-guile-3.0.9.nix}/bin/guile";
  args = [
    "--no-auto-compile"
    "${../sources/nz1pgy7wqazkw1r9hc3anggs96qqhg8l-compile-modules}"
  ];
  GUILE_WARN_DEPRECATED = "no";
  extensions = "";
  "module count" = "1";
  modules = "${../sources/zfz0k7p3wv8g31j0ycb3p9s75wpyq3jw-jsxgc979x79h81kzqz9n6cpf5pk4z262-module-import}";
  "optimization level" = "1";
  preferLocalBuild = "1";
}
