# Generated by guix-transfer
builtins.derivation {
  name = "pixman-0.46.4.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-0JxE68O9W+5wIcefki/o+y+1f3Mg9V6X/5kU0jRqWRw=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://www.cairographics.org/releases/pixman-0.46.4.tar.gz";
}
