# Generated by guix-transfer
builtins.derivation {
  name = "dnspython-2.7.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-zpxDLtoNyRz2GKXO3xpOFCZRGWu80sgOie1akH5c+vE=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/dnspython-2.7.0.tar.gz/sha256/1wgsbiz90npdi47cilmwdccm29hl9qddzkm533v1rj8dv8p4776f";
}
