# Generated by guix-transfer
builtins.derivation {
  name = "HTTP-Message-6.37.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-DlnaCoXiSIMTJ+v7pmeWMUy2nxv+7/ep2kStdm0H2AI=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/HTTP-Message-6.37.tar.gz/sha256/00nq0xnpdba4valzgvzy3fgvck1ijrksdyzb4w9q6j72hl5dln8f";
}
