# Generated by guix-transfer
builtins.derivation {
  name = "pytest-trio-0.8.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-g2PbYzannmxTN1ohI6Qd2+zMSqk/k3iGUWQXiaVvtS4=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/pytest-trio-0.8.0.tar.gz/sha256/0bmmdyjqj5v4a637i4rzm55crv6v3nj268as6x9nr7m76rixnqw3";
}
