# Generated by guix-transfer
builtins.derivation {
  name = "bison-3.8.2.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-m7oCFMz38QecXVkhAEUie89hlRmEDr+oDNOEnP9aW/I=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://ftp.gnu.org/gnu/bison/bison-3.8.2.tar.xz";
}
