# Generated by guix-transfer
builtins.derivation {
  name = "openssl-1.1.1u.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-4vjYS1I+7NBse+diaDA3AwD7zBU4a/UULXJ1j2lj68Y=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://www.openssl.org/source/openssl-1.1.1u.tar.gz";
}
