# Generated by guix-transfer
builtins.derivation {
  name = "poppler-22.09.0.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-16j3SCETWcrbd0uj4Y7NpkZLNAJwRcBkjrMNWFKkHi4=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/poppler-22.09.0.tar.xz/sha256/0bhyli95h3dkirjc0ibh08s4nim6rn7f38sbfzdwln8k454gga6p";
}
