# Generated by guix-transfer
builtins.derivation {
  name = "cups-2.4.14-checkout";
  system = "x86_64-linux";
  builder = "builtin:git-download";
  outputHash = "sha256-IuY4c+QcOnsot6do0liwGpLRmnMj8ZdCxcH3H6nSZbY=";
  outputHashAlgo = "sha256";
  outputHashMode = "recursive";
  commit = "v2.4.14";
  impureEnvVars = "http_proxy https_proxy LC_ALL LC_MESSAGES LANG COLUMNS";
  preferLocalBuild = "1";
  "recursive?" = "#f";
  url = "\"https://github.com/OpenPrinting/cups\"";
}
