# Generated by guix-transfer
builtins.derivation {
  name = "dnspython-2.7.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-zpxDLtoNyRz2GKXO3xpOFCZRGWu80sgOie1akH5c+vE=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://files.pythonhosted.org/packages/source/d/dnspython/dnspython-2.7.0.tar.gz";
}
