# Generated by guix-transfer
builtins.derivation {
  name = "libunwind-1.5.0.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/c4ay50vfyk7bxiiy4gzz8wp6d6b9qfay-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/7skwz4rdpxxc3s03vb07mqvpxr8s6j1h-module-import-compiled.nix).out}"
    "${builtins.path { name = ''libunwind-1.5.0.tar.zst-builder''; path = ./../sources/m9iv580jpqk78c6d73ry04ig8vdvzyf8-libunwind-1.5.0.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "libunwind-1.5.0.tar.zst-builder"; path = ./../sources/m9iv580jpqk78c6d73ry04ig8vdvzyf8-libunwind-1.5.0.tar.zst-builder; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 3))";
  __phantom_deps = "${(import ../store/3f5ch18ghnzfbkk1iv2rk12j6n37lp51-xz-5.4.5.nix).out} ${(import ../store/8wg103mjrc4gzj8aq9l1ir8yb7nhqvc6-gzip-1.14.nix).out} ${(import ../store/3rlp7cr36snabnbv11ih55b7bs7k4is0-libunwind-prefer-extbl.nix).out} ${(import ../store/fhskwarrjxl0726s5svlyqabd7i3ipy2-tar-1.35.nix).out} ${(import ../store/5gwd67p6kfpbn2hd07igkbsrfs7qj6rr-libunwind-static-arm.nix).out} ${(import ../store/bs5jzy6r2zfk2hn9g21h7biwssm56266-patch-2.7.6.nix).out} ${(import ../store/yb1sws411b1zwr1rs7gdfk7la4crdj78-libunwind-1.5.0.tar.gz.nix).out} ${(import ../store/j62jcz2m4jjnvv3z42mdxvs73xp8d95s-zstd-1.5.6.nix).out} ${(import ../store/gm88z5skfkkwv9pi15y13rfr12ajw1ma-libunwind-cfa-rsp.nix).out}";
}
