# Generated by guix-transfer
builtins.derivation {
  name = "docbook-xsl-1.79.2-0.fe16c90-checkout";
  system = "x86_64-linux";
  builder = "${(import ../store/0wsxd5g0xbxncz609bqq5hbg48hx8cpm-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/69fricvrgmnbmbm6hi7j08m4cvagza7h-module-import-compiled.nix).out}"
    "${builtins.path { name = ''docbook-xsl-1.79.2-0.fe16c90-checkout-builder''; path = ./../sources/pn975m2cxaza77mpgbkf1wgyy1g5q8yc-docbook-xsl-1.79.2-0.fe16c90-checkout-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "docbook-xsl-1.79.2-0.fe16c90-checkout-builder"; path = ./../sources/pn975m2cxaza77mpgbkf1wgyy1g5q8yc-docbook-xsl-1.79.2-0.fe16c90-checkout-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 0))";
  __phantom_deps = "${(import ../store/fl18v8zafk6wpc2yqxrahapqw7l7n073-xz-5.4.5.nix).out} ${(import ../store/przplmr5p7drhhnblshi6aigzv2kmm5g-docbook-xsl-1.79.2-0.fe16c90-checkout.nix).out} ${(import ../store/pv1ibrv4pc1km18w8i0iiwklhpn6h9lc-tar-1.35.nix).out} ${(import ../store/q8sb66r0q7l58drjj8wdqlf2808abkar-patch-2.7.6.nix).out} ${(import ../store/f60dfz81yizjj1j5x7pzdcmmhc38yr1v-zstd-1.5.6.nix).out}";
}
