# Generated by guix-transfer
builtins.derivation {
  name = "rust-subtle-2.6.1.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-E8K93sxXs4Te4YZSNY+yMXL6y4osUczBDXTBV73qMpI=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-subtle-2.6.1.tar.gz/sha256/14ijxaymghbl1p0wql9cib5zlwiina7kall6w7g89csprkgbvhhk";
}
