# Generated by guix-transfer
builtins.derivation {
  name = "rust-rayon-core-1.12.1.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-FGWHOj39qornyxS0ODZXyqsLPooKqa6OBLBEhUyN/OI=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/rayon-core/1.12.1/download";
}
