# Generated by guix-transfer
builtins.derivation {
  name = "libproxy-0.4.17.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-vIn4QvZU7hmFoxwLpW3H4s6ARKAmTdyoTmUPRs1/iwU=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/libproxy-0.4.17.tar.xz/sha256/01cbgz6lc3v59sldqk96l1281kp2qxnsa2qwlf2ikvjlyr1gi2dw";
}
