# Generated by guix-transfer
builtins.derivation {
  name = "glib-2.83.3.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/c4ay50vfyk7bxiiy4gzz8wp6d6b9qfay-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/7skwz4rdpxxc3s03vb07mqvpxr8s6j1h-module-import-compiled.nix).out}"
    "${builtins.path { name = ''glib-2.83.3.tar.zst-builder''; path = ./../sources/ad22d2g27x2mzjcxfj4g55089znsbdq4-glib-2.83.3.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "glib-skip-failing-test.patch"; path = ./../sources/kz6y3dhpm6dqcfii7ncnh3jr5vg0mlm9-glib-skip-failing-test.patch; })
    (builtins.path { name = "glib-appinfo-watch.patch"; path = ./../sources/c65zp3yfssf4mmyb403dq6670i5xj9z9-glib-appinfo-watch.patch; })
    (builtins.path { name = "glib-2.83.3.tar.zst-builder"; path = ./../sources/ad22d2g27x2mzjcxfj4g55089znsbdq4-glib-2.83.3.tar.zst-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 2))";
  __phantom_deps = "${(import ../store/3f5ch18ghnzfbkk1iv2rk12j6n37lp51-xz-5.4.5.nix).out} ${(import ../store/iqqbc5i78jgkh6isdw35mfqmm3s82kxw-glib-2.83.3.tar.xz.nix).out} ${(import ../store/fhskwarrjxl0726s5svlyqabd7i3ipy2-tar-1.35.nix).out} ${(import ../store/bs5jzy6r2zfk2hn9g21h7biwssm56266-patch-2.7.6.nix).out} ${(import ../store/j62jcz2m4jjnvv3z42mdxvs73xp8d95s-zstd-1.5.6.nix).out}";
}
