# Generated by guix-transfer
builtins.derivation {
  name = "gpgme-1.24.1.tar.bz2";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-6gXQJY5xBh1hcWWE7DTO9ZMwqRNAVx7cRreDdJc7qF8=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/gpgme-1.24.1.tar.bz2/sha256/0px87fbp90xp8vf1wms02flk14zmrqsfr135f5his1kiiqjx01ga";
}
