# Generated by guix-transfer
builtins.derivation {
  name = "coreutils-runtime-env";
  system = "x86_64-linux";
  builder = "${(import ../store/hn59viz2gmjdjjikmjmmlf5lnnp4wzn1-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''him4s80rycgl78anc4njh5bwq5wmajhk-module-import''; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; }}"
    "-C"
    "${(import ../store/y1zhhyv04z5fnhg9ashiqdfxd6k0hzfd-module-import-compiled.nix).out}"
    "${builtins.path { name = ''coreutils-runtime-env-builder''; path = ./../sources/256rzlpx0ygj30b602hgr97mq62i7vv4-coreutils-runtime-env-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "coreutils-runtime-env-builder"; path = ./../sources/256rzlpx0ygj30b602hgr97mq62i7vv4-coreutils-runtime-env-builder; })
    (builtins.path { name = "him4s80rycgl78anc4njh5bwq5wmajhk-module-import"; path = ./../sources/izhjw0ip5baab18999xyy358ny2m4n2z-him4s80rycgl78anc4njh5bwq5wmajhk-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  allowSubstitutes = "0";
  "guix properties" = "((type . guixpkgs-runtime-env))";
  preferLocalBuild = "1";
  __phantom_deps = "${(import ../store/3l7igs3iy2wq6g860w7lqzidb26sv5zb-gmp-6.3.0.nix).out} ${(import ../store/44nwkl7zhi0arc680ll2hvgf7l44fqrb-acl-2.3.1.nix).out} ${(import ../store/8sm4ynggb2nakmv0kvzyin41rqrj3hvg-libcap-2.64.nix).out} ${(import ../store/71831kwfic918x9b89ixws2191v7gfzk-coreutils-9.1.nix).out} ${(import ../store/372l7jmvivifq6kki1xrf759s2f6qhnm-attr-2.5.1.nix).out}";
}
