# Generated by guix-transfer
builtins.derivation {
  name = "rust-criterion-0.5.1.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-8rEtAXqSlgPYDbGDHNOiQIL4E3zhnGnmRH9U9fyNaS8=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/criterion/0.5.1/download";
}
