# Generated by guix-transfer
builtins.derivation {
  name = "emacs-dash-2.20.0-checkout";
  system = "x86_64-linux";
  builder = "builtin:git-download";
  outputHash = "sha256-1TxfU88Ouc9Tx+ouzLxTKNpS/HjJPOsFobyZuIJxUyQ=";
  outputHashAlgo = "sha256";
  outputHashMode = "recursive";
  commit = "2.20.0";
  impureEnvVars = "http_proxy https_proxy LC_ALL LC_MESSAGES LANG COLUMNS";
  preferLocalBuild = "1";
  "recursive?" = "#f";
  url = "\"https://github.com/magnars/dash.el\"";
}
