# Generated by guix-transfer
builtins.derivation {
  name = "nss-3.101.4.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/hn59viz2gmjdjjikmjmmlf5lnnp4wzn1-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/nnjrv59xc0zvampmfnv1xac2gk3f8ffp-module-import-compiled.nix).out}"
    "${builtins.path { name = ''nss-3.101.4.tar.zst-builder''; path = ./../sources/fh6ajxzpdskhk82nrsgwin4azcsisr81-nss-3.101.4.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "nss-increase-test-timeout.patch"; path = ./../sources/6dch85qam7dalkchcrkc92zs70nghdn5-nss-increase-test-timeout.patch; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "nss-3.56-pkgconfig.patch"; path = ./../sources/d7cdg5iai52p5bcid6ikp2f6nnxs6vkx-nss-3.56-pkgconfig.patch; })
    (builtins.path { name = "nss-disable-broken-tests.patch"; path = ./../sources/pjgngjidlqi126x624n1f7ss4jxapyar-nss-disable-broken-tests.patch; })
    (builtins.path { name = "nss-3.101.4.tar.zst-builder"; path = ./../sources/fh6ajxzpdskhk82nrsgwin4azcsisr81-nss-3.101.4.tar.zst-builder; })
    (builtins.path { name = "nss-getcwd-nonnull.patch"; path = ./../sources/d3m5daz2xig07g5jsah75jr5ckgvqd2q-nss-getcwd-nonnull.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 4))";
  __phantom_deps = "${(import ../store/h9ys9ff47zjq8g6glpw9vckvjszbid19-xz-5.4.5.nix).out} ${(import ../store/xdhd9k0narw3a72pspxgm0hgdww3a4x0-gzip-1.14.nix).out} ${(import ../store/09b2nkz74rpqw1xg8lhs2z4lvxa79kk6-nss-3.101.4.tar.gz.nix).out} ${(import ../store/6mcsn3vji1fs82g0jlksppd7nwiyzk0x-tar-1.35.nix).out} ${(import ../store/ix63qg734rsvk1jafvk2d9f83nhssk1a-patch-2.7.6.nix).out} ${(import ../store/sq6pj4hf188957l7vjnc38lavkpcj4pl-zstd-1.5.6.nix).out}";
}
