# Generated by guix-transfer
builtins.derivation {
  name = "pytest_rerunfailures-15.1.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-xgQDaKvXuBOMW2coi+F9blYRtzaHVc4EZd2gNiyOzoA=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://files.pythonhosted.org/packages/source/p/pytest_rerunfailures/pytest_rerunfailures-15.1.tar.gz";
}
