# Generated by guix-transfer
builtins.derivation {
  name = "texlive-latex-lab-2025.2-checkout";
  system = "x86_64-linux";
  builder = "${(import ../store/0wsxd5g0xbxncz609bqq5hbg48hx8cpm-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import''; path = ./../sources/l9qrfq20vvrf1r54k0fr7xds1f9dlqmk-m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import; }}"
    "-L"
    "${(import ../store/ww3lnzlx927117603wp6k80yxxm8rf9x-guile-json-4.7.3.nix).out}/share/guile/site/3.0"
    "-L"
    "${(import ../store/dn07p8vpchfy15w3r4mrf68w3cc69ljf-guile-gnutls-5.0.1.nix).out}/share/guile/site/3.0"
    "-L"
    "${(import ../store/3x2yx4nry504h5ygb8pakd5v5ib5s67n-guile-lzlib-0.3.0.nix).out}/share/guile/site/3.0"
    "-C"
    "${(import ../store/yij66sqbk0wdz79yisp1m8g03s9bfj6d-module-import-compiled.nix).out}"
    "-C"
    "${(import ../store/ww3lnzlx927117603wp6k80yxxm8rf9x-guile-json-4.7.3.nix).out}/lib/guile/3.0/site-ccache"
    "-C"
    "${(import ../store/dn07p8vpchfy15w3r4mrf68w3cc69ljf-guile-gnutls-5.0.1.nix).out}/lib/guile/3.0/site-ccache"
    "-C"
    "${(import ../store/3x2yx4nry504h5ygb8pakd5v5ib5s67n-guile-lzlib-0.3.0.nix).out}/lib/guile/3.0/site-ccache"
    "${builtins.path { name = ''svn-multi-download''; path = ./../sources/sncvp7xxnhhxrzx5ysf4vipcgn96bplq-svn-multi-download; }}"
  ];
  srcs = [
    (builtins.path { name = "svn-multi-download"; path = ./../sources/sncvp7xxnhhxrzx5ysf4vipcgn96bplq-svn-multi-download; })
    (builtins.path { name = "m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import"; path = ./../sources/l9qrfq20vvrf1r54k0fr7xds1f9dlqmk-m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import; })
  ];
  outputHash = "sha256-wDvguMYFoA8s1hj2rtJAe+0x9fokJPbMjmd1zKyZBSs=";
  outputHashAlgo = "sha256";
  outputHashMode = "recursive";
  hash = "192,59,224,184,198,5,160,15,44,214,24,246,174,210,64,123,237,49,245,250,36,36,246,204,142,103,117,204,172,153,5,43";
  impureEnvVars = "http_proxy https_proxy LC_ALL LC_MESSAGES LANG COLUMNS";
  preferLocalBuild = "1";
  "svn locations" = "(\"doc/latex/latex-lab/\" \"source/latex/latex-lab/\" \"tex/latex/latex-lab/\")";
  "svn revision" = "74725";
  "svn url" = "svn://www.tug.org/texlive/tags/texlive-2025.2/Master/texmf-dist";
  __phantom_deps = "${(import ../store/dn07p8vpchfy15w3r4mrf68w3cc69ljf-guile-gnutls-5.0.1.nix).debug} ${(import ../store/8l53snldrx4gk81nhl3d5866b6xhc446-gzip-1.14.nix).out} ${(import ../store/di2b6xx0caqh12d2x5ivccriz1bm1j55-tar-1.35.nix).out} ${(import ../store/14fa99n8af61jhhdqilkcl94m64m3h4h-subversion-1.14.5.nix).out}";
}
