# Generated by guix-transfer
builtins.derivation {
  name = "libidn-1.43.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-vcZiwS0EGyU50OY486bnQRMM2zOmRO80lpY6RDSC0WQ=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://ftp.gnu.org/gnu/libidn/libidn-1.43.tar.gz";
}
