# Generated by guix-transfer
builtins.derivation {
  name = "rust-redox-syscall-0.2.16.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-+1pYwYVbS2gZ1ZASFVYD8LIq0wytdSYAqt/LaVJlUZo=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/redox_syscall/0.2.16/download";
}
