# Generated by guix-transfer
builtins.derivation {
  name = "libidn-1.41.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-iE1wY2S4Gr3Re+6Whtj/KudDHFoUZRBHxorfizH9iUU=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/libidn-1.41.tar.gz/sha256/0ic9zlqqppwaqr3i0r8lb8f47rrazzc8d5pfgg8vs6mqciip0kc8";
}
