# Generated by guix-transfer
builtins.derivation {
  name = "libtool-2.4.7.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-T38hfwV85lX/IlWa0iGg/Y74StH8X8tpkM7MMzqhY10=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/libtool-2.4.7.tar.xz/sha256/0pb3l4x37k6fj1lwnpzws55gi3pxl0hx56jm4bzmbrkw0mzj2zsg";
}
