# Generated by guix-transfer
builtins.derivation {
  name = "rustc-1.77.1-src.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-7hBuTFafUtujtbKCsQWCD4a9j2s9CcBrjc6C+xuzpKE=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rustc-1.77.1-src.tar.gz/sha256/18d4ncdzp0nfimmw029xdf7vv1hgh82v30mjnnixnllzar66w47f";
}
