# Generated by guix-transfer
builtins.derivation {
  name = "libdmx-1.1.5.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-NaTiaosLK0/jZEHcpGNkXD+lLSgqw1IFAaOOqULL908=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/libdmx-1.1.5.tar.xz/sha256/0kzprd1ak3m3042m5hra50nsagswciis9p21ckilyaqbidmf591m";
}
