# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://github.com/sissaschool/xmlschema"; rev = "v4.1.0"; hash = "sha256-3nvl49rlwQpNARmWBSw+faL+yNGqNecokjGGpnaC8a0="; name = "python-xmlschema-4.1.0-checkout"; fetchSubmodules = false; }
