# Generated by guix-transfer
builtins.derivation {
  name = "rust-futures-channel-0.3.31.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-Lf8Vv3iMZxwZNONm0H4wwYFKjvUU4a9ySmAuii++GxA=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-futures-channel-0.3.31.tar.gz/sha256/040vpqpqlbk099razq8lyn74m0f161zd0rp36hciqrwcg2zibzrd";
}
