# Generated by guix-transfer
builtins.derivation {
  name = "emacs-30.2.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-s/NvGKbdJxVxM3AWYlfeL64B+dOM/oeM7Zsebe1b79k=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://ftp.gnu.org/gnu/emacs/emacs-30.2.tar.xz";
}
