# Generated by guix-transfer
builtins.derivation {
  name = "rust-bzip2-0.5.2.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-Sez7ItkG+ADU/oM7YoLPTcHCmPUFfKC1RF5cIJc1ykc=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-bzip2-0.5.2.tar.gz/sha256/0iya6nbj0p2y8jss0z05yncc5hadry164fw3zva01y06v4igpv29";
}
