# Generated by guix-transfer
builtins.derivation {
  name = "rust-clap-4.5.35.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-2KqGk0tEwZxQ+HzCeQ4Z9U96Z67bZBAcLhouXs+3OUQ=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-clap-4.5.35.tar.gz/sha256/0i1rnz7mwbhs5qf10r6vmrkplkzm3477khkwz189rha49f9qdanq";
}
