# Generated by guix-transfer
builtins.derivation {
  name = "libunwind-1.5.0.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/pq24yb7jw5rqgccsssvkk9n4lj9m1ri3-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/66alicjhn34r3fdisxzh1xvlkfhvllm9-module-import-compiled.nix).out}"
    "${builtins.path { name = ''libunwind-1.5.0.tar.zst-builder''; path = ./../sources/m9iv580jpqk78c6d73ry04ig8vdvzyf8-libunwind-1.5.0.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "libunwind-1.5.0.tar.zst-builder"; path = ./../sources/m9iv580jpqk78c6d73ry04ig8vdvzyf8-libunwind-1.5.0.tar.zst-builder; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 3))";
  __phantom_deps = "${(import ../store/gyhiimwajbnkd9myji0qfi40jhy7w9y2-xz-5.4.5.nix).out} ${(import ../store/08bq32vfm5vz5x0q3f59p8rchaacbcgb-gzip-1.14.nix).out} ${(import ../store/3rlp7cr36snabnbv11ih55b7bs7k4is0-libunwind-prefer-extbl.nix).out} ${(import ../store/vpi87n22f8dbhvbwaqr470xp83hnbf1y-tar-1.35.nix).out} ${(import ../store/3gb27lnl65jidh9cyxjqq8j6xv39n8sj-libunwind-static-arm.nix).out} ${(import ../store/759rgw9c7j48gb1bv5fgr2sb3d9f5p1v-patch-2.7.6.nix).out} ${(import ../store/yb1sws411b1zwr1rs7gdfk7la4crdj78-libunwind-1.5.0.tar.gz.nix).out} ${(import ../store/r2mqn9i7k9h1xzrx3jbihckz3lhymvpv-zstd-1.5.6.nix).out} ${(import ../store/gm88z5skfkkwv9pi15y13rfr12ajw1ma-libunwind-cfa-rsp.nix).out}";
}
