# Generated by guix-transfer
builtins.derivation {
  name = "zile-2.6.4.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-1dRLhctJBkPQcH4aIYbzoymYwvbquqlIFHm2XK7uV8A=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/zile-2.6.4.tar.gz/sha256/1h2pxsp5rdkr2i4akfpayv19had3yf3226kyf38461j9rf2lpm6m";
}
