# Generated by guix-transfer
builtins.derivation {
  name = "gdk-pixbuf-2.42.12.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-uVBbNEW5p+SM7TR2DDvLc+lm3zrJTJWhSMtmmrdI48c=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://download.gnome.org/sources/gdk-pixbuf/2.42/gdk-pixbuf-2.42.12.tar.xz";
}
