# Generated by guix-transfer
builtins.derivation {
  name = "stage0-posix-1.6.0";
  system = "x86_64-linux";
  builder = "${(import ../store/xxpwmhk6fpk8c3x18vrz1yfzh1bvppm5-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/70ns6s1k8i1kzkwhhbyw02p2a4lxfba0-module-import-compiled.nix).out}"
    "${builtins.path { name = ''stage0-posix-1.6.0-builder''; path = ./../sources/vnpbmz06wf7klc5dkb3bcgjab0z77wrh-stage0-posix-1.6.0-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "stage0-posix-1.6.0-builder"; path = ./../sources/vnpbmz06wf7klc5dkb3bcgjab0z77wrh-stage0-posix-1.6.0-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/zdvnfljr8gd2axb3q26k3pwanvgh79bl-stage0-posix-1.6.0.tar.gz.nix).out} ${(import ../store/hzzpl5rjqwclnkm9fxl10a64ci9z8aly-gash-utils-boot-0.2.0.nix).out} ${(import ../store/mrvry9pgdbwkwvwxv4r2x4vd4by7q2nh-bootar-1b.nix).out} ${(import ../store/h0gp28m6wbq7dx9cln7lqv46bavwsjj5-gash-boot-0.3.1.nix).out}";
}
