# Generated by guix-transfer
builtins.derivation {
  name = "readline82-005";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-Yiujh9rlwYWvtLmyBjSATl9sHG5eh+vufDWo8GURTJk=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/readline82-005/sha256/16ac25jz1a1mgkpfp1sydqf6qpsfh0s0dcmrnjpqbhg5va3s6av2";
}
