# Generated by guix-transfer
builtins.derivation {
  name = "automake-1.17.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-iSDB/EEeE7kL9wTvnbbynVQOdtIyyzssn03EzFmb2ZA=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://ftp.gnu.org/gnu/automake/automake-1.17.tar.xz";
}
