# Generated by guix-transfer
builtins.derivation {
  name = "rust-windows-implement-0.60.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-pH/d0TrwgpDmf0rKv0tFn2R1UnGPaDp7QV0pCsdEqDY=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-windows-implement-0.60.0.tar.gz/sha256/0dm88k3hlaax85xkls4gf597ar4z8m5vzjjagzk910ph7b8xszx4";
}
