# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://github.com/rainstormstudio/nerd-icons.el"; rev = "4bd9795f1f3f47cb874e10ff5c3845e037f0b3e2"; hash = "sha256-gSbypgBG90GHA/TYlwElLICD20VV6nxlkwJrGVCls8Y="; name = "emacs-nerd-icons-0.1.0-1.4bd9795-checkout"; fetchSubmodules = false; }
