# Generated by guix-transfer
builtins.derivation {
  name = "rust-dtoa-1.0.10.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-1q3TuM/zlCgr6B8/waBgXbWU7WmJAHjKbiyrHECLzwQ=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-dtoa-1.0.10.tar.gz/sha256/016gid01rarcdv57h049d7nr9daxc2hc2gqzx0mji57krywd7bfn";
}
