# Generated by guix-transfer
builtins.derivation {
  name = "bash52-018";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-RkHdSd2SO0VN0KNGJ3kHCQQQ9dYKKaLeO4LJjkmqqoA=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/bash52-018/sha256/105am94qxjc27gga4a8asvsi01090xwjfim3s16lafwjvm4xsha6";
}
