# Generated by guix-transfer
builtins.derivation {
  name = "binutils-2.20.1a.tar.xz";
  system = "x86_64-linux";
  builder = "${(import ../store/xxpwmhk6fpk8c3x18vrz1yfzh1bvppm5-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/70ns6s1k8i1kzkwhhbyw02p2a4lxfba0-module-import-compiled.nix).out}"
    "${builtins.path { name = ''binutils-2.20.1a.tar.xz-builder''; path = ./../sources/jvb2r23lfy91gkifi26rzl82inrdsdab-binutils-2.20.1a.tar.xz-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "binutils-boot-2.20.1a.patch"; path = ./../sources/4b679hf1iykpcm5j09p3rdz1vmg2hxif-binutils-boot-2.20.1a.patch; })
    (builtins.path { name = "binutils-2.20.1a.tar.xz-builder"; path = ./../sources/jvb2r23lfy91gkifi26rzl82inrdsdab-binutils-2.20.1a.tar.xz-builder; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 1))";
  __phantom_deps = "${(import ../store/4hqv4a82yqn4d2yzhiyhgc1n8548kcyy-binutils-2.20.1a.tar.bz2.nix).out} ${(import ../store/r9lli79l2f45sfis06sa8hyp6s0pkxhc-bootstrap-binaries-0.nix).out}";
}
