# Generated by guix-transfer
builtins.derivation {
  name = "rust-scroll-derive-0.12.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-f4HC/eAlr35psdFCBTHIqIEcqJiRnbF3FBqFMTscuTI=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-scroll-derive-0.12.0.tar.gz/sha256/0cmr3hxk318s2ivv37cik2l1r0d8r0qhahnin5lpxbr5w3yw50bz";
}
