# Generated by guix-transfer
builtins.derivation {
  name = "pkg-config-0.29.2.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-b8acAWiMlFilfrmhZkyaujcszaQgoCv0Qp/mEOfn1ZE=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/pkg-config-0.29.2.tar.gz/sha256/14fmwzki1rlz8bs2p810lk6jqdxsk966d8drgsjmi54cd00rrikg";
}
