# Generated by guix-transfer
builtins.derivation {
  name = "nspr-4.36.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-Vd7DF/FAHNLl26hE00C5MKt1R/gYF5pAArzmLm8caJU=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://ftp.mozilla.org/pub/mozilla.org/nspr/releases/v4.36/src/nspr-4.36.tar.gz";
}
