# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://github.com/samuelcolvin/watchfiles"; rev = "v1.0.5"; hash = "sha256-a6SHqYRNMGXNkVvwj9RpLj449dAQtWXO44v1ko5suaw="; name = "python-watchfiles-1.0.5-checkout"; fetchSubmodules = false; }
