# Generated by guix-transfer
builtins.derivation {
  name = "rust-phf-shared-0.10.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-tnlq13Gs3AEj0qiNxCi1447yRFZ0PdsXRO1ij5gVwJY=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/phf_shared/0.10.0/download";
}
