# Generated by guix-transfer
builtins.derivation {
  name = "cups-2.4.14-checkout";
  system = "x86_64-linux";
  builder = "${(import ../store/hn59viz2gmjdjjikmjmmlf5lnnp4wzn1-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/nnjrv59xc0zvampmfnv1xac2gk3f8ffp-module-import-compiled.nix).out}"
    "${builtins.path { name = ''cups-2.4.14-checkout-builder''; path = ./../sources/yngqznc2rf5ns4lbdch27kavwzn0wh54-cups-2.4.14-checkout-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "cups-2.4.14-checkout-builder"; path = ./../sources/yngqznc2rf5ns4lbdch27kavwzn0wh54-cups-2.4.14-checkout-builder; })
    (builtins.path { name = "cups-relax-root-ownership-check.patch"; path = ./../sources/dm746s4ccz52xkj3mnyn2ch2m87q1q6x-cups-relax-root-ownership-check.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 1))";
  __phantom_deps = "${(import ../store/348v0f75qxdj6rji4hf6b4w6n37dizw8-cups-2.4.14-checkout.nix).out} ${(import ../store/h9ys9ff47zjq8g6glpw9vckvjszbid19-xz-5.4.5.nix).out} ${(import ../store/6mcsn3vji1fs82g0jlksppd7nwiyzk0x-tar-1.35.nix).out} ${(import ../store/ix63qg734rsvk1jafvk2d9f83nhssk1a-patch-2.7.6.nix).out} ${(import ../store/sq6pj4hf188957l7vjnc38lavkpcj4pl-zstd-1.5.6.nix).out}";
}
