# Generated by guix-transfer
builtins.derivation {
  name = "rust-toml-0.5.11.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-9Pfw3Y1QqFOlMcQmNZBFsZmPBCGdiHmYEHYs1K0xQjQ=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/toml/0.5.11/download";
}
