# Generated by guix-transfer
builtins.derivation {
  name = "automake-1.16.5.tar.zst";
  system = "x86_64-linux";
  builder = "${import ../store/h6j68xwpj7dm4xbrkw5n28k434wlw0g0-guile-3.0.9.nix}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${../sources/zfz0k7p3wv8g31j0ycb3p9s75wpyq3jw-jsxgc979x79h81kzqz9n6cpf5pk4z262-module-import}"
    "-C"
    "${import ../store/li5xpkgwwawrqd9zkdzjlpincr26cmpg-module-import-compiled.nix}"
    "${../sources/225idx9w6y1k4m0is0826c50wvk7xnsc-automake-1.16.5.tar.zst-builder}"
  ];
  "guix properties" = "((type . origin) (patches . 1))";
  __phantom_deps = "${import ../store/6wd11plgnd3pxx08q0yr298wiln3gl5n-automake-1.16.5.tar.xz.nix} 94797xsj3sc5axm2x6b2d3yfm2g5ix4a-patch-2.7.6 cccmzmbcx20w2swy810kqw3hib4xnpas-xz-5.4.5 icvmyhfsj88iypsz71cj4jdvrkc9wa7y-zstd-1.5.2 mr042cl0rzl2gvy4k4in86qb4hs5svwf-tar-1.34";
}
