# Generated by guix-transfer
builtins.derivation {
  name = "rust-web-sys-0.3.77.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-M7bdLvkYbx8gcuQJ6ZzSKpdTMaazWRsSx2Tg5Vxg1dI=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/web-sys/0.3.77/download";
}
