# Generated by guix-transfer
builtins.derivation {
  name = "gcc-mesboot1-4.6.4";
  system = "x86_64-linux";
  builder = "${(import ../store/xxpwmhk6fpk8c3x18vrz1yfzh1bvppm5-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import''; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; }}"
    "-C"
    "${(import ../store/g1g9hl4rdrinpkr04d79w724bld8biiv-module-import-compiled.nix).out}"
    "${builtins.path { name = ''gcc-mesboot1-4.6.4-builder''; path = ./../sources/fr3a31bsygqg0hr88sixsx2aw8msrkz7-gcc-mesboot1-4.6.4-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import"; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; })
    (builtins.path { name = "gcc-boot-4.6.4.patch"; path = ./../sources/vvs3n0s0z06w3pmim66c1gbgngj1w34i-gcc-boot-4.6.4.patch; })
    (builtins.path { name = "gcc-mesboot1-4.6.4-builder"; path = ./../sources/fr3a31bsygqg0hr88sixsx2aw8msrkz7-gcc-mesboot1-4.6.4-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/pgblp47dqahdk1pks2zbf1yks7wrmzka-gcc-mesboot0-2.95.3.nix).out} ${(import ../store/k4n2ncfcn82bv2mhvz1rj6794r264c33-gcc-g++-4.6.4.tar.gz.nix).out} ${(import ../store/xggzkkkiipw1wm6dv9cyizizdvywrab8-gcc-core-4.6.4.tar.gz.nix).out} ${(import ../store/s5fv59dcq37yy7r089mha6nyij2wxyry-gzip-mesboot-1.2.4.nix).out} ${(import ../store/7acbr2h8fcs2w4flc3fjrw91bl4k6d0b-gmp-4.3.2.tar.gz.nix).out} ${(import ../store/25l0kl6dxhahm90b53x8svd1ihiywmjq-linux-libre-headers-bootstrap-0.nix).out} ${(import ../store/pi9i7yr597qlxzfqaa5fh6c7qmadj1a2-patch-mesboot-2.5.9.nix).out} ${(import ../store/g48x68pyc0b0k39qw9bix8sjj5i6jv4a-make-mesboot-3.82.nix).out} ${(import ../store/hzzpl5rjqwclnkm9fxl10a64ci9z8aly-gash-utils-boot-0.2.0.nix).out} ${(import ../store/mrvry9pgdbwkwvwxv4r2x4vd4by7q2nh-bootar-1b.nix).out} ${(import ../store/66q3fdqrir9cglvv1gd5x2k07v9krcfr-mpfr-2.4.2.tar.gz.nix).out} ${(import ../store/h0gp28m6wbq7dx9cln7lqv46bavwsjj5-gash-boot-0.3.1.nix).out} ${(import ../store/drfcp0fzlqv6pnc640pyir6q6h3lzdx1-glibc-mesboot0-2.2.5.nix).out} ${(import ../store/60ys8hh8rs0igbr4aw59r1rxwss8flvq-binutils-mesboot1-2.20.1a.nix).out} ${(import ../store/gxa2y5niwj6mjry1k8xwacpcsfjai4br-mpc-1.0.3.tar.gz.nix).out}";
}
