# Generated by guix-transfer
builtins.derivation {
  name = "rust-archery-1.2.1.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-6uLtIc1VAh8FcHqAel/IVpXa+5iDKSH2z6BttnyluGk=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-archery-1.2.1.tar.gz/sha256/0sdqlmybcvd0rzv22ac3k3xxm5anr1gpm03sf02iy0jmrlhyvqpa";
}
