# Generated by guix-transfer
builtins.derivation {
  name = "backports_tarfile-1.2.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-114Cwmh0bhuBRMJ4l4tumOhd5q0W+OSwhEoVRVfsqZE=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://files.pythonhosted.org/packages/source/b/backports_tarfile/backports_tarfile-1.2.0.tar.gz";
}
