# Generated by guix-transfer
builtins.derivation {
  name = "rust-rustix-0.38.44.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-/bW8GuK6pZGADfFsnKeGGb9lwEiLQblszsXREiDYwVQ=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/rustix/0.38.44/download";
}
