# Generated by guix-transfer
builtins.derivation {
  name = "rust-phf-macros-0.11.3.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-+ErARCnBOn/0N4XXWtJ1afKVHOD/0wozISMNsvxychY=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-phf-macros-0.11.3.tar.gz/sha256/05kjfbyb439344rhmlzzw0f9bwk9fp95mmw56zs7yfn1552c0jpq";
}
