# Generated by guix-transfer
builtins.derivation {
  name = "autoconf-wrapper-2.69";
  system = "x86_64-linux";
  builder = "${(import ../store/c4ay50vfyk7bxiiy4gzz8wp6d6b9qfay-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/7skwz4rdpxxc3s03vb07mqvpxr8s6j1h-module-import-compiled.nix).out}"
    "${builtins.path { name = ''autoconf-wrapper-2.69-builder''; path = ./../sources/6hd8ym2x9bc6wq0mp3yiwzscxl0yzjay-autoconf-wrapper-2.69-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "autoconf-wrapper-2.69-builder"; path = ./../sources/6hd8ym2x9bc6wq0mp3yiwzscxl0yzjay-autoconf-wrapper-2.69-builder; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/fdf705vfqwv9by2c3mf1nkzdcgsq6mlj-m4-1.4.19.nix).out} ${(import ../store/gvhlymx9c4m0fxd0f85v8cdgz0bi3p7h-perl-5.36.0.nix).out} ${(import ../store/zkqawn8zracwmj60az7z3mg8cg4qxl9s-libgc-8.2.8.nix).out} ${(import ../store/a2radl74x2kz8csdqiqi5h72629fa33j-guile-3.0.9.nix).out} ${(import ../store/b5fnqzs2zlc9gpf73ky07y3vwhiv7z40-bash-minimal-5.2.37.nix).out} ${(import ../store/45w080s6clwyw7ncn6cskh4nys7dfkv9-autoconf-2.69.tar.xz.nix).out} ${(import ../store/dn16p3kk2vjhbg57fsw15zhirkjcjjwr-libunistring-1.3.nix).out} ${(import ../store/maarkk3diyg7w10hngyvrgiigg0ff5gg-autoconf-2.69.nix).out}";
}
