# Generated by guix-transfer
builtins.derivation {
  name = "rust-plain-0.2.3.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-tFlrbQcLJxF+mHEZtNrGBPPFjPsLGRES4kdxsvrqwaY=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/plain/0.2.3/download";
}
