# Generated by guix-transfer
builtins.derivation {
  name = "rust-derivative-2.2.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-/MPdXp6cCyldbh5NgR+28VfV/9eEuNIC/GLqyANadws=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/derivative/2.2.0/download";
}
