# Generated by guix-transfer
builtins.derivation {
  name = "rust-rustls-pemfile-2.2.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-3OMU5f7j85lT1Gu2O7ikbUDC+Pt8xaO2yrK96XIdblA=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/rustls-pemfile/2.2.0/download";
}
