# Generated by guix-transfer
builtins.derivation {
  name = "gzip-mesboot-1.2.4";
  system = "x86_64-linux";
  builder = "${(import ../store/xxpwmhk6fpk8c3x18vrz1yfzh1bvppm5-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import''; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; }}"
    "-C"
    "${(import ../store/g1g9hl4rdrinpkr04d79w724bld8biiv-module-import-compiled.nix).out}"
    "${builtins.path { name = ''gzip-mesboot-1.2.4-builder''; path = ./../sources/k7rpyfjzyy6bszvnjv4vddrc4q7zxhgw-gzip-mesboot-1.2.4-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import"; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; })
    (builtins.path { name = "gzip-mesboot-1.2.4-builder"; path = ./../sources/k7rpyfjzyy6bszvnjv4vddrc4q7zxhgw-gzip-mesboot-1.2.4-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/8vpq4apgfmi1zh4wvxpal5ch0cc7fxcn-tcc-boot0-0.9.26-1149-g46a75d0c.nix).out} ${(import ../store/hzzpl5rjqwclnkm9fxl10a64ci9z8aly-gash-utils-boot-0.2.0.nix).out} ${(import ../store/mrvry9pgdbwkwvwxv4r2x4vd4by7q2nh-bootar-1b.nix).out} ${(import ../store/h0gp28m6wbq7dx9cln7lqv46bavwsjj5-gash-boot-0.3.1.nix).out} ${(import ../store/plpc8ak4mqkrv0478h4jgrcnmkly5dzn-gzip-1.2.4.tar.nix).out}";
}
