# Generated by guix-transfer
builtins.derivation {
  name = "elfutils-0.192.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/hn59viz2gmjdjjikmjmmlf5lnnp4wzn1-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/nnjrv59xc0zvampmfnv1xac2gk3f8ffp-module-import-compiled.nix).out}"
    "${builtins.path { name = ''elfutils-0.192.tar.zst-builder''; path = ./../sources/v6fhgh7yvn5h1x17ic8rp9ipkcf3dzq5-elfutils-0.192.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "elfutils-tests-ptrace.patch"; path = ./../sources/x98ap58zfhmdpgyld56p8v0clnqgm1q6-elfutils-tests-ptrace.patch; })
    (builtins.path { name = "elfutils-0.192.tar.zst-builder"; path = ./../sources/v6fhgh7yvn5h1x17ic8rp9ipkcf3dzq5-elfutils-0.192.tar.zst-builder; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 1))";
  __phantom_deps = "${(import ../store/h9ys9ff47zjq8g6glpw9vckvjszbid19-xz-5.4.5.nix).out} ${(import ../store/6mcsn3vji1fs82g0jlksppd7nwiyzk0x-tar-1.35.nix).out} ${(import ../store/ivwf3hfr8wgqk80igr38mfd022jlwsaw-elfutils-0.192.tar.bz2.nix).out} ${(import ../store/1579v3jai551gzha5i02ccazjxy382jk-bzip2-1.0.8.nix).out} ${(import ../store/ix63qg734rsvk1jafvk2d9f83nhssk1a-patch-2.7.6.nix).out} ${(import ../store/sq6pj4hf188957l7vjnc38lavkpcj4pl-zstd-1.5.6.nix).out}";
}
