# Generated by guix-transfer
builtins.derivation {
  name = "binutils-mesboot1-2.20.1a";
  system = "x86_64-linux";
  builder = "${(import ../store/3sgvmyxar0bp0r707sgivngr256jlw8k-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import''; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; }}"
    "-C"
    "${(import ../store/f1pxw9ip8s5g4ka338rz03kza9ip49mz-module-import-compiled.nix).out}"
    "${builtins.path { name = ''binutils-mesboot1-2.20.1a-builder''; path = ./../sources/5jd10j2zfd9dhzx61lhvml7mgv7ai7zk-binutils-mesboot1-2.20.1a-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import"; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; })
    (builtins.path { name = "binutils-mesboot1-2.20.1a-builder"; path = ./../sources/5jd10j2zfd9dhzx61lhvml7mgv7ai7zk-binutils-mesboot1-2.20.1a-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/rv3vnspbirb8c9vys61w5r9d211ckj3w-binutils-mesboot0-2.20.1a.nix).out} ${(import ../store/xvcs6bjwxn94js3m8vzy54xrkbhp6v2k-binutils-2.20.1a.tar.xz.nix).out} ${(import ../store/l46qfmdxhqdb47fglp4m1hb9swq6jzkp-linux-libre-headers-bootstrap-0.nix).out} ${(import ../store/6q4wczw41fysqyy94zkv5fv8sya0jxpp-patch-mesboot-2.5.9.nix).out} ${(import ../store/kqgx82wczsgs3ps0hyh4sak2fp7nz8jv-gash-utils-boot-0.2.0.nix).out} ${(import ../store/x6yr5bpjnj89rnn1rxawhk0cgn0wx9jw-bootar-1b.nix).out} ${(import ../store/27czm9gbhppl5wisbz77znn40yijk0w6-make-mesboot0-3.80.nix).out} ${(import ../store/730yn4856ykv2306b65pbq3rcnyngi7f-gzip-mesboot-1.2.4.nix).out} ${(import ../store/5xpac7sh9dsa690il2g08wsrvl3zckmg-gcc-mesboot0-2.95.3.nix).out} ${(import ../store/g4d9mmhvis6dw00drnwqa69rynlp8m06-glibc-mesboot0-2.2.5.nix).out} ${(import ../store/bwx4qmi4638ia9mmrhbav5sh7izvbv8n-gash-boot-0.3.1.nix).out}";
}
