# Generated by guix-transfer
builtins.derivation {
  name = "referencing-0.35.1.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-JbQhJKbItjKkJRdPJAh3g++zSKbx4ACOY81EZv7fcDw=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/referencing-0.35.1.tar.gz/sha256/0g3hvzz6ci6dcf701q7ilr4b7vw3fw428kqp4nj35dn8lqj23d15";
}
