# Generated by guix-transfer
builtins.derivation {
  name = "module-import-compiled";
  system = "x86_64-linux";
  builder = "${import ../store/h6j68xwpj7dm4xbrkw5n28k434wlw0g0-guile-3.0.9.nix}/bin/guile";
  args = [
    "--no-auto-compile"
    "${../sources/nz1pgy7wqazkw1r9hc3anggs96qqhg8l-compile-modules}"
  ];
  GUILE_WARN_DEPRECATED = "no";
  extensions = "";
  "module count" = "4";
  modules = "${../sources/9p7iwxh6r030nilkb9690djwc7mcf9w2-6qhr7s8431yv7ikcax3l30hw6cim95kc-module-import}";
  "optimization level" = "1";
  preferLocalBuild = "1";
}
