# Generated by guix-transfer
builtins.derivation {
  name = "numpy-1.26.4.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/pq24yb7jw5rqgccsssvkk9n4lj9m1ri3-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/66alicjhn34r3fdisxzh1xvlkfhvllm9-module-import-compiled.nix).out}"
    "${builtins.path { name = ''numpy-1.26.4.tar.zst-builder''; path = ./../sources/8a6ps1abr0r7fracv81j9jr9vw3y5fpa-numpy-1.26.4.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "numpy-1.26.4.tar.zst-builder"; path = ./../sources/8a6ps1abr0r7fracv81j9jr9vw3y5fpa-numpy-1.26.4.tar.zst-builder; })
    (builtins.path { name = "python-numpy-gcc-14.patch"; path = ./../sources/cyq3s0y5662afd3bmqa5gddv46017rd1-python-numpy-gcc-14.patch; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 1))";
  __phantom_deps = "${(import ../store/gyhiimwajbnkd9myji0qfi40jhy7w9y2-xz-5.4.5.nix).out} ${(import ../store/08bq32vfm5vz5x0q3f59p8rchaacbcgb-gzip-1.14.nix).out} ${(import ../store/kia3x802l19g1n9fw6q80v7qzk5x6mh4-numpy-1.26.4.tar.gz.nix).out} ${(import ../store/vpi87n22f8dbhvbwaqr470xp83hnbf1y-tar-1.35.nix).out} ${(import ../store/759rgw9c7j48gb1bv5fgr2sb3d9f5p1v-patch-2.7.6.nix).out} ${(import ../store/r2mqn9i7k9h1xzrx3jbihckz3lhymvpv-zstd-1.5.6.nix).out}";
}
