# Generated by guix-transfer
builtins.derivation {
  name = "rust-self-cell-1.1.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-wv38JLxWb4OaLaTEKVuC230lokJThn1cZDVau1eZvb4=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/self_cell/1.1.0/download";
}
