# Generated by guix-transfer
builtins.derivation {
  name = "markdown-3.10.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-NwYtTyqksrazKu+4D6owD4LMeQy5SaNbjK7eNPK2jA4=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/markdown-3.10.tar.gz/sha256/03lcnvr39pmfiids6jdr1iwwr0hg62m0zf7g5arvdcm4597js1ip";
}
