# Generated by guix-transfer
builtins.derivation {
  name = "rust-fnv-1.0.7.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-P57skY0/JAad7LmvFVTK18iA4tokqa/YisoABTGrgsE=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-fnv-1.0.7.tar.gz/sha256/1hc2mcqha06aibcaza94vbi81j6pr9a1bbxrxjfhc91zin8yr7iz";
}
