# Generated by guix-transfer
builtins.derivation {
  name = "rust-gobject-sys-0.19.8.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-Lml+JS1uBBb9HZ4Wm9pRwPHJJgJsOcoh++ixu1w7i54=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-gobject-sys-0.19.8.tar.gz/sha256/17lb7dfbpcg8zchwlfbc08kckwf0a7d9n5ly3pyic13f5ljpws9f";
}
