# Generated by guix-transfer
builtins.derivation {
  name = "rust-tracing-log-0.2.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-7oVfH0AL0OXALRUK5d44QAOaP1SwJRVkBONMI8A/R8M=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-tracing-log-0.2.0.tar.gz/sha256/1hs77z026k730ij1a9dhahzrl0s073gfa2hm5p0fbl0b80gmz1gf";
}
