# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://github.com/golang/go"; rev = "go1.20.14"; hash = "sha256-1Un9bOXkv/9wCAhoJAz2cPaJEv4OvKFYMwcXcIZgEKs="; name = "go-1.20.14-checkout"; fetchSubmodules = false; }
