# Generated by guix-transfer
builtins.derivation {
  name = "rust-fxhash-0.2.1.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-wxttdRrix/ETIEAtNOQTSd0QFvjV1F5IxDEryGJa9Qw=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/fxhash/0.2.1/download";
}
