# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://github.com/asottile/covdefaults"; rev = "v2.3.0"; hash = "sha256-/RqqvGL2a6sCNe5HrJ9Ty5SlingQ+dblVtGYd+z8ZKw="; name = "python-covdefaults-2.3.0-checkout"; fetchSubmodules = false; }
