# Generated by guix-transfer
builtins.derivation {
  name = "boost_1_83_0.tar.bz2";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-ZHjt/i8zBRJ8/+jK9z6gF2xTdp9L8Vhb4jfrMHmMO44=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://archives.boost.io/release/1.83.0/source/boost_1_83_0.tar.bz2";
}
