# Generated by guix-transfer
builtins.derivation {
  name = "watchdog-6.0.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-nd98gv2jro4k3s2hM47eZuHJmIPbk3Edj7lB6qLYwoI=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/watchdog-6.0.0.tar.gz/sha256/10n2v2iflhdriwfp34yvhfcckqb6vs7378fdvqj8xbm3zn17rpwx";
}
