# Generated by guix-transfer
builtins.derivation {
  name = "rust-rand-0.8.5.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-NK+NGg4lkkvFt8Q8B5yUIznY8Ki1fDkEm+9YG0YydAQ=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/rand/0.8.5/download";
}
