# Generated by guix-transfer
builtins.derivation {
  name = "libxml2-2.14.6.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/vihw99pskl1w6knya9dcvbacizccwdrd-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/facvks9qmjk78i76bjx7cjaajngr0ma8-module-import-compiled.nix).out}"
    "${builtins.path { name = ''libxml2-2.14.6.tar.zst-builder''; path = ./../sources/0l9w7iv5f5l2jra9yfmv5r49ngzcfbyr-libxml2-2.14.6.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "libxml2-2.14.6.tar.zst-builder"; path = ./../sources/0l9w7iv5f5l2jra9yfmv5r49ngzcfbyr-libxml2-2.14.6.tar.zst-builder; })
    (builtins.path { name = "python-libxml2-utf8.patch"; path = ./../sources/kxfhvf4062bhdx037lvp30jy77qllnkj-python-libxml2-utf8.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 1))";
  __phantom_deps = "${(import ../store/k4s0yg5jkpp3nqb9za9jkfsgd1da9a19-libxml2-2.14.6.tar.xz.nix).out} ${(import ../store/khc7qqckwrr8rq5dq5fg65ndwhcwamxj-zstd-1.5.6.nix).out} ${(import ../store/33qkpmasidc168qy89vxamki3iqb04r4-patch-2.7.6.nix).out} ${(import ../store/0y1qp7pia269f83byngfy0vac8pa623s-xz-5.4.5.nix).out} ${(import ../store/ml37n5h6g693171lhlwf717jxd4yhaqb-tar-1.35.nix).out}";
}
