# Generated by guix-transfer
builtins.derivation {
  name = "compiler-rt-13.0.1.src.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-ezOVUDH5qcXWMHfe2w+Z135OfJliZpUsHOxVYm3KXfw=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/compiler-rt-13.0.1.src.tar.xz/sha256/1z2xr9nn4mgc3hn9ark2k5y4wznpk47xppkp63bcbagr6589acvv";
}
