# Generated by guix-transfer
builtins.derivation {
  name = "rust-annotate-snippets-0.11.5.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-cQ6OrliFTNwXkPy1bMoE1xKhe+hJ7rgdoqckv0uuK8Q=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/annotate-snippets/0.11.5/download";
}
