# Generated by guix-transfer
builtins.derivation {
  name = "rust-minicov-0.3.7.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-8n/p8cw8IuFof5RGwgg8TF/H8Lzxx6hr297RSYWJW0s=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/minicov/0.3.7/download";
}
