# Generated by guix-transfer
builtins.derivation {
  name = "sed-4.8.tar.xz";
  system = "x86_64-linux";
  builder = "${(import ../store/3sgvmyxar0bp0r707sgivngr256jlw8k-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/vqpyw7y1k6p4barzxp5x7j41h8ax7w1b-module-import-compiled.nix).out}"
    "${builtins.path { name = ''sed-4.8.tar.xz-builder''; path = ./../sources/4bqxfn6913hqd4k4szjpznv56ab7w0yp-sed-4.8.tar.xz-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "sed-4.8.tar.xz-builder"; path = ./../sources/4bqxfn6913hqd4k4szjpznv56ab7w0yp-sed-4.8.tar.xz-builder; })
    (builtins.path { name = "coreutils-gnulib-tests.patch"; path = ./../sources/h5a5lxx5ybg56ykis0j41c2cbz3y97nw-coreutils-gnulib-tests.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 1))";
  __phantom_deps = "${(import ../store/gx9yhjw5zcfzxm1d3gmfb5sbc64xw6ww-bootstrap-binaries-0.nix).out} ${(import ../store/60z4xhwjsh8f8mgz4p5m8payjf3023p5-sed-4.8.tar.gz.nix).out}";
}
