# Generated by guix-transfer
builtins.derivation {
  name = "pytest-xprocess-1.0.2.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-FeJwY3WG6rxWdV7l/MgcSL20a6fvfA1bG2QwLQgMxg8=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://files.pythonhosted.org/packages/source/p/pytest-xprocess/pytest-xprocess-1.0.2.tar.gz";
}
