# Generated by guix-transfer
builtins.derivation {
  name = "openblas-0.3.30-checkout";
  system = "x86_64-linux";
  builder = "builtin:git-download";
  outputHash = "sha256-foP2OXUL6ttgYvCxLsxUiVdkPoTvGiHomdNudbSUmSE=";
  outputHashAlgo = "sha256";
  outputHashMode = "recursive";
  commit = "v0.3.30";
  impureEnvVars = "http_proxy https_proxy LC_ALL LC_MESSAGES LANG COLUMNS";
  preferLocalBuild = "1";
  "recursive?" = "#f";
  url = "\"https://github.com/xianyi/OpenBLAS\"";
}
