# Generated by guix-transfer
builtins.derivation {
  name = "rust-stacker-0.1.20.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-YB+SAf65sJwAJmR4v0WZUrnvmmuU7bLyHroUq2gaYKk=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/stacker/0.1.20/download";
}
