# Generated by guix-transfer
builtins.derivation {
  name = "libSM-1.2.5.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-KvnhLaXvZw3Dp7zhiVycDxv7DLnmTo20D8wz+IO9ILw=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://www.x.org/releases/individual/lib/libSM-1.2.5.tar.xz";
}
