# Generated by guix-transfer
builtins.derivation {
  name = "rust-cargo-config2-0.1.32.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-bcN0mjbgQjyZHx56Pkqww2ofSJZYMT20sYfUAdecxGE=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-cargo-config2-0.1.32.tar.gz/sha256/0qf4kkbh3m47n6s3scaqjr41ysn3n153wyhy3yckqhp06sd79hvd";
}
