# Generated by guix-transfer
builtins.derivation {
  name = "rust-windows-aarch64-gnullvm-0.52.6.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-MqRiIYDnoOwES7VVQEyAC8n9nsJi7BR+3VmJzNDALNM=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/windows_aarch64_gnullvm/0.52.6/download";
}
