# Generated by guix-transfer
builtins.derivation {
  name = "socat-1.7.4.4.tar.bz2";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-+9Qr0vDlSjr20BvfFThThKuC28Dk8aXhU7PgvhtjgKw=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "http://www.dest-unreach.org/socat/download/socat-1.7.4.4.tar.bz2";
}
