# Generated by guix-transfer
builtins.derivation {
  name = "compiler-rt-13.0.1.src.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/0wsxd5g0xbxncz609bqq5hbg48hx8cpm-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/69fricvrgmnbmbm6hi7j08m4cvagza7h-module-import-compiled.nix).out}"
    "${builtins.path { name = ''compiler-rt-13.0.1.src.tar.zst-builder''; path = ./../sources/sazjrl4k8r8w5qdnaqym02hi73yyq9by-compiler-rt-13.0.1.src.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "compiler-rt-13.0.1.src.tar.zst-builder"; path = ./../sources/sazjrl4k8r8w5qdnaqym02hi73yyq9by-compiler-rt-13.0.1.src.tar.zst-builder; })
    (builtins.path { name = "clang-13-remove-crypt-interceptors.patch"; path = ./../sources/k5qy21qb24wcqfrf498snc3pwgjj0h1d-clang-13-remove-crypt-interceptors.patch; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "clang-runtime-13-glibc-2.36-compat.patch"; path = ./../sources/7yvx3dri9izsnjwfrac3l1bhpdk33c1p-clang-runtime-13-glibc-2.36-compat.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 2))";
  __phantom_deps = "${(import ../store/fl18v8zafk6wpc2yqxrahapqw7l7n073-xz-5.4.5.nix).out} ${(import ../store/pv1ibrv4pc1km18w8i0iiwklhpn6h9lc-tar-1.35.nix).out} ${(import ../store/v9sn5mw54rwax3b96iz4gajq79phw9q1-compiler-rt-13.0.1.src.tar.xz.nix).out} ${(import ../store/q8sb66r0q7l58drjj8wdqlf2808abkar-patch-2.7.6.nix).out} ${(import ../store/f60dfz81yizjj1j5x7pzdcmmhc38yr1v-zstd-1.5.6.nix).out}";
}
