# Generated by guix-transfer
builtins.derivation {
  name = "libgd-2.3.3.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-P+gi7OIHlgYK9jt8YKyxUeWEQgTSidoM4I+P3xMeWmE=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://github.com/libgd/libgd/releases/download/gd-2.3.3/libgd-2.3.3.tar.xz";
}
