# Generated by guix-transfer
builtins.derivation {
  name = "flex-2.6.4.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-6HquAyvwfCb4WsDtMlCZjDdiHZX4vXSLMfFbM8Re6ZU=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/flex-2.6.4.tar.gz/sha256/15g9bv236nzi665p9ggqjlfn4dwck5835vf0bbw2cz7h5c1swyp8";
}
