# Generated by guix-transfer
builtins.derivation {
  name = "rust-minijinja-2.9.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-mGQqbfypESJ3mjB7d80HpKqVH74yIyqvW62f68Zr51Q=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-minijinja-2.9.0.tar.gz/sha256/0m77dg3fp7xdbfpjl8rjpqgrbam40z6pfyrhk9vj44d9zinjlr4q";
}
