# Generated by guix-transfer
builtins.derivation {
  name = "nss-certs-for-test-3.101.4";
  system = "x86_64-linux";
  builder = "${(import ../store/0wsxd5g0xbxncz609bqq5hbg48hx8cpm-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''m1p3dycplk4fv8q9jd9blkss8i8mayfi-module-import''; path = ./../sources/h0m3ix02ngm6hwzwbhs4c9wqfkixvh3a-m1p3dycplk4fv8q9jd9blkss8i8mayfi-module-import; }}"
    "-C"
    "${(import ../store/kqgs46r5cs2vg3q3dhh68crj1994jh3i-module-import-compiled.nix).out}"
    "${builtins.path { name = ''nss-certs-for-test-3.101.4-builder''; path = ./../sources/4saa0gb5ks7nkf9hwgbq9rhjz0smsvq8-nss-certs-for-test-3.101.4-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "nss-certs-for-test-3.101.4-builder"; path = ./../sources/4saa0gb5ks7nkf9hwgbq9rhjz0smsvq8-nss-certs-for-test-3.101.4-builder; })
    (builtins.path { name = "m1p3dycplk4fv8q9jd9blkss8i8mayfi-module-import"; path = ./../sources/h0m3ix02ngm6hwzwbhs4c9wqfkixvh3a-m1p3dycplk4fv8q9jd9blkss8i8mayfi-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/s8bg833b75lxg1vmj88l1ha15qn9v9vm-nss-certs-3.101.4.nix).out}";
}
