# Generated by guix-transfer
builtins.derivation {
  name = "rust-gdk-pixbuf-sys-0.19.8.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-TvoFpPg8jMUOtNiDeHuRm4Xl8djdELWh31O/Vol4I3k=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/gdk-pixbuf-sys/0.19.8/download";
}
