# Generated by guix-transfer
builtins.derivation {
  name = "curio-1.6.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-VipYbbICFrp9K+gmPeuesHnlYEj5uJBtEdX0WqgcUkc=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/curio-1.6.tar.gz/sha256/0isj3jl5mx6m25nr1f7r91hfaydhkvmks9p85dyvl5h2n9nmhajn";
}
