# Generated by guix-transfer
builtins.derivation {
  name = "readline82-001";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-u/l/HsQKkp7ataqBmYweLvQ1Q2xZd1SRbmpYaPJzr/c=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/readline82-001/sha256/1xxgfgr6hn3ads8m8xsrdi1kbx1f3s69k0danpd9x4haqhg7zydv";
}
