# Generated by guix-transfer
builtins.derivation {
  name = "bash51-006";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-deF9k33oYmFcY3Xe9Ap1dEYiENzojPdB9mDizClHPRQ=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/bash51-006/sha256/051x8wlwrqk0yr0zg378vh824iklfl5g9pkmcdf62qp8gn9pvqbm";
}
