# Generated by guix-transfer
builtins.derivation {
  name = "rust-serde-1.0.219.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-Xw4sbtZgYBm04p5p26upWxGFRBDlNH1SUAJFbbu3hrY=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-serde-1.0.219.tar.gz/sha256/1dl6nyxnsi82a197sd752128a4avm6mxnscywas1jq30srp2q3jz";
}
