# Generated by guix-transfer
builtins.derivation {
  name = "libXt-1.3.1.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-4Kd0szMk9NTAWxmepFBQ+HIGWG2BZV+L7026Q02TEog=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://www.x.org/releases/individual/lib/libXt-1.3.1.tar.xz";
}
