# Generated by guix-transfer
builtins.derivation {
  name = "ld-wrapper-boot0-0";
  system = "x86_64-linux";
  builder = "${(import ../store/3sgvmyxar0bp0r707sgivngr256jlw8k-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/vqpyw7y1k6p4barzxp5x7j41h8ax7w1b-module-import-compiled.nix).out}"
    "${builtins.path { name = ''ld-wrapper-boot0-0-builder''; path = ./../sources/kyabvn140bh5qws71y2jq6qvg0y80v0s-ld-wrapper-boot0-0-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "ld-wrapper.in"; path = ./../sources/qsw2fycvyk1w029yn82ps1657h4cywcp-ld-wrapper.in; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "ld-wrapper-boot0-0-builder"; path = ./../sources/kyabvn140bh5qws71y2jq6qvg0y80v0s-ld-wrapper-boot0-0-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/bgknh9j5mgmmvsrynqk9ryxw90cc1m89-binutils-cross-boot0-2.44.nix).out} ${(import ../store/kwyi24694bv3bzhfn9w5km6ivzylhi10-bash-mesboot-5.2.37.nix).out}";
}
