# Generated by guix-transfer
builtins.derivation {
  name = "file-5.46.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-ycx3x8VgxUMTXtxVWvYJ1WGdvvARmX6YjOQKPXXYYIg=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/file-5.46.tar.gz/sha256/1230v1sks2p4ijc7x68iy2z9sqfm17v5lmfwbq9l7ib0qp3pgk69";
}
