# Generated by guix-transfer
builtins.derivation {
  name = "glibc-2.41.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/hn59viz2gmjdjjikmjmmlf5lnnp4wzn1-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/nnjrv59xc0zvampmfnv1xac2gk3f8ffp-module-import-compiled.nix).out}"
    "${builtins.path { name = ''glibc-2.41.tar.zst-builder''; path = ./../sources/i031rrj6z24s9zdnj39h0b8jz7qvvqjp-glibc-2.41.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "glibc-hurd-pthread_setcancelstate.patch"; path = ./../sources/mi77q66f7a33sayfqc29z1404hd7fdg5-glibc-hurd-pthread_setcancelstate.patch; })
    (builtins.path { name = "glibc-hurd-2.41-pthread-sigmask.patch"; path = ./../sources/54sggk9a3wd95c2fj81p6l3h2db4dxn5-glibc-hurd-2.41-pthread-sigmask.patch; })
    (builtins.path { name = "glibc-hurd-gettyent.patch"; path = ./../sources/z182qp6i5mb4drcarrx5z8a132dwhy5x-glibc-hurd-gettyent.patch; })
    (builtins.path { name = "glibc-2.37-hurd-clock_t_centiseconds.patch"; path = ./../sources/vvwrf3b5ysgn9byra68mw41iy2n4chyw-glibc-2.37-hurd-clock_t_centiseconds.patch; })
    (builtins.path { name = "glibc-ldd-powerpc.patch"; path = ./../sources/gpmljabnp3hjgv6zdzwady51s7r64x1m-glibc-ldd-powerpc.patch; })
    (builtins.path { name = "glibc-2.41.tar.zst-builder"; path = ./../sources/i031rrj6z24s9zdnj39h0b8jz7qvvqjp-glibc-2.41.tar.zst-builder; })
    (builtins.path { name = "glibc-2.41-ldd-x86_64.patch"; path = ./../sources/33fkl1ry0yyy7cqcqvr8n5493pryixsj-glibc-2.41-ldd-x86_64.patch; })
    (builtins.path { name = "glibc-hurd64-gcc-14.2-tls-bug.patch"; path = ./../sources/f9q9mcpd1064a5ccycp2wsxqnnl23lqn-glibc-hurd64-gcc-14.2-tls-bug.patch; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "glibc-hurd-2.41-pthread-once.patch"; path = ./../sources/g7xz67x10blbr9xsf3510156s6ihry1q-glibc-hurd-2.41-pthread-once.patch; })
    (builtins.path { name = "glibc-hurd-getauxval.patch"; path = ./../sources/h552spzzjhr8gcqv9px8h3xj6fqn0wwb-glibc-hurd-getauxval.patch; })
    (builtins.path { name = "glibc-2.37-versioned-locpath.patch"; path = ./../sources/1jajb6x08m8bavxflxcpwz4dixdrp5b0-glibc-2.37-versioned-locpath.patch; })
    (builtins.path { name = "glibc-hurd-2.41-symlink.patch"; path = ./../sources/bfnn3d37qrc73mm2id4x4b5ka2m1gh82-glibc-hurd-2.41-symlink.patch; })
    (builtins.path { name = "glibc-hurd-mach-print.patch"; path = ./../sources/l7r71809pvdv49zgqr8hq851nqvz128h-glibc-hurd-mach-print.patch; })
    (builtins.path { name = "glibc-supported-locales.patch"; path = ./../sources/idmmxzammni69w0cyj06sabz550c4waz-glibc-supported-locales.patch; })
    (builtins.path { name = "glibc-2.41-hurd-local-clock_gettime_MONOTONIC.patch"; path = ./../sources/1msfxp2pvdpvblflgjv0xpx6230rv392-glibc-2.41-hurd-local-clock_gettime_MONOTONIC.patch; })
    (builtins.path { name = "glibc-2.40-dl-cache.patch"; path = ./../sources/lkn439z2v5lvldx66s7wv1p8rhd5iyrv-glibc-2.40-dl-cache.patch; })
    (builtins.path { name = "glibc-reinstate-prlimit64-fallback.patch"; path = ./../sources/i6qqjp572lbjppkx7n50hi3hcb6jnk5x-glibc-reinstate-prlimit64-fallback.patch; })
    (builtins.path { name = "glibc-hurd64-intr-msg-clobber.patch"; path = ./../sources/m6mvixh5aj859d56my3wiw344226l7iz-glibc-hurd64-intr-msg-clobber.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 17))";
  __phantom_deps = "${(import ../store/h9ys9ff47zjq8g6glpw9vckvjszbid19-xz-5.4.5.nix).out} ${(import ../store/6mcsn3vji1fs82g0jlksppd7nwiyzk0x-tar-1.35.nix).out} ${(import ../store/bgzman47ny3szjkadr90rzs5wd32kkjl-glibc-2.41.tar.xz.nix).out} ${(import ../store/ix63qg734rsvk1jafvk2d9f83nhssk1a-patch-2.7.6.nix).out} ${(import ../store/sq6pj4hf188957l7vjnc38lavkpcj4pl-zstd-1.5.6.nix).out}";
}
