# Generated by guix-transfer
builtins.derivation {
  name = "trove_classifiers-2025.5.9.12.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-fKfIp6duLNMURoxnfGnRLMI1dxH8q0pg+HmUwVieXLU=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/trove_classifiers-2025.5.9.12.tar.gz/sha256/1dawkrcc353rz1h4mazw25vkbhics5lpqrwc8qad6b3flykwi9vw";
}
