# Generated by guix-transfer
builtins.derivation {
  name = "rust-pyo3-build-config-0.23.5.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-lPbL6G7zvxiZjZ324PP8EFCoxe+kCb9xLmYaQ2bgEPs=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-pyo3-build-config-0.23.5.tar.gz/sha256/1yqhw1k466k65rqvy2d4xz2shl0hzkry1xlxinciigzkdvlcpxll";
}
