# Generated by guix-transfer
builtins.derivation {
  name = "rust-windows-x86-64-msvc-0.52.6.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-WJ9tqExkYgR0fRJwoqVmHqZu0cztJjHVRv37FVlZ+ew=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/windows_x86_64_msvc/0.52.6/download";
}
