# Generated by guix-transfer
builtins.derivation {
  name = "poppler-data-0.4.11.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-LOwFzRuwOvmKiwah4i9ubhplseLzgWyzBpuwh0gl8Iw=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/poppler-data-0.4.11.tar.gz/sha256/137h4m48gc4v0srnr0gkwaqna6kfdqpy5886if5gjfmh3g6hbv1c";
}
