# Generated by guix-transfer
builtins.derivation {
  name = "rust-windows-x86-64-msvc-0.48.5.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-7ZT85hVxpABoUrc4mgY6uYPALrG7N7R/gnLOktBtlTg=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/windows_x86_64_msvc/0.48.5/download";
}
