# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://gitlab.com/emacs-geiser/guile"; rev = "0.28.3"; hash = "sha256-zi2JzFgPt0G2VMHE5iZfBIqnIVg731n0Oqlbdj7OzUQ="; name = "emacs-geiser-guile-0.28.3-checkout"; fetchSubmodules = false; }
