# Generated by guix-transfer
builtins.derivation {
  name = "gcc-core-4.6.4.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-5TSlywWrg51897JJb9XfQudjUpJsHPDZTedhhMJqc5w=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/gcc-core-4.6.4.tar.gz/sha256/173kdb188qg79pcz073cj9967rs2vzanyjdjyxy9v0xb0p5sad75";
}
