# Generated by guix-transfer
builtins.derivation {
  name = "subversion-1.14.5.tar.bz2";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-54op53Zri3s1RJfQj3GlVkGrxTZ1zhh1WEeBquNWRKE=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/subversion-1.14.5.tar.bz2/sha256/18a4avism0a7b1siikkm6v2snhanlmqqzl4p8hspp2vbfvkjk2p7";
}
