# Generated by guix-transfer
builtins.derivation {
  name = "rust-gdk-pixbuf-sys-0.19.8.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-TvoFpPg8jMUOtNiDeHuRm4Xl8djdELWh31O/Vol4I3k=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-gdk-pixbuf-sys-0.19.8.tar.gz/sha256/0y93g24mdgskvyhva46xv3qyb1cvj5xpi0yqnh7cb31wz2j0byjf";
}
