# Generated by guix-transfer
builtins.derivation {
  name = "openssl-3.0.8.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/f75k9wv63ksf2s8m5jfnhzbwvbqv84ps-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/g04gyzlav8k6j9bsh5awq479yyiga760-module-import-compiled.nix).out}"
    "${builtins.path { name = ''openssl-3.0.8.tar.zst-builder''; path = ./../sources/c2dv36hdwnwz5vhi15mw6jnmdh8aava9-openssl-3.0.8.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "openssl-3.0.8.tar.zst-builder"; path = ./../sources/c2dv36hdwnwz5vhi15mw6jnmdh8aava9-openssl-3.0.8.tar.zst-builder; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "openssl-3.0-c-rehash-in.patch"; path = ./../sources/71k1d3pd616m10qywnr4lv4zw94ankcp-openssl-3.0-c-rehash-in.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 1))";
  __phantom_deps = "${(import ../store/vp4z2nnisya9dakfk4xm2rymv9nzjdaj-gzip-1.14.nix).out} ${(import ../store/prbr2b006j916llx53bhzla6vx1rxpih-patch-2.7.6.nix).out} ${(import ../store/jg77mkrxf4mj622s55bqsw667cryqyxd-tar-1.35.nix).out} ${(import ../store/6yl1l324h9vk7jm4xcjk7silhilby7zp-zstd-1.5.6.nix).out} ${(import ../store/83h6ihm240dq5m1ha0i15h0lj5w9kbsj-openssl-3.0.8.tar.gz.nix).out} ${(import ../store/nlxczvbla673cx586blzfwml5ix51rnq-xz-5.4.5.nix).out}";
}
