# Generated by guix-transfer
builtins.derivation {
  name = "libspectre-0.2.10";
  system = "x86_64-linux";
  builder = "${(import ../store/hn59viz2gmjdjjikmjmmlf5lnnp4wzn1-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import''; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; }}"
    "-C"
    "${(import ../store/a5gdksr5dppbvjrbk52nq82a51vz5m6d-module-import-compiled.nix).out}"
    "${builtins.path { name = ''libspectre-0.2.10-builder''; path = ./../sources/008fbsfmiwrp7vp2l818z5cw48czla4v-libspectre-0.2.10-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import"; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; })
    (builtins.path { name = "libspectre-0.2.10-builder"; path = ./../sources/008fbsfmiwrp7vp2l818z5cw48czla4v-libspectre-0.2.10-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/asrzfr2qas01nlii0qczhzlxd7zr4rdy-gcc-14.3.0.nix).out} ${(import ../store/h9ys9ff47zjq8g6glpw9vckvjszbid19-xz-5.4.5.nix).out} ${(import ../store/9c2qf69dhbrgpqx2a8ab46qphsgi110w-glibc-2.41.nix).out} ${(import ../store/dh4rlzrx7kj128kimpp40x350gvcnxda-file-5.46.nix).out} ${(import ../store/49i6hrswdr0izpjlj7g3085xd5c7nnv6-ghostscript-9.56.1.nix).out} ${(import ../store/d3ipgrk70f0iq21pln0q6fpw6r4iw5xx-bash-minimal-5.2.37.nix).out} ${(import ../store/xdhd9k0narw3a72pspxgm0hgdww3a4x0-gzip-1.14.nix).out} ${(import ../store/gqq9b0s40fd9j498bwqky7r0m9h11r3y-gawk-5.3.0.nix).out} ${(import ../store/p157xy8a0kv4p30x49rmds66a3dlpqfd-ld-wrapper-0.nix).out} ${(import ../store/6mcsn3vji1fs82g0jlksppd7nwiyzk0x-tar-1.35.nix).out} ${(import ../store/dkhqfiqzfbx2iwlgy5i252v39gfm1xhi-linux-libre-headers-6.12.17.nix).out} ${(import ../store/9cjadwpjygly4pan6fks8gzxmv2dvfvb-coreutils-9.1.nix).out} ${(import ../store/n7a6qpk7xgxl8j78a9ngnbqb2lcjad0x-binutils-2.44.nix).out} ${(import ../store/1579v3jai551gzha5i02ccazjxy382jk-bzip2-1.0.8.nix).out} ${(import ../store/xav3wsb3h8qvqxqxsfi2r1r318gp72hx-pkg-config-0.29.2.nix).out} ${(import ../store/mqyj4agc5ji9pzyb5xia0cb2iziy9lp2-make-4.4.1.nix).out} ${(import ../store/k4p5rnkc77gdfzh8jaxxr088500d2ik4-diffutils-3.12.nix).out} ${(import ../store/s522q9vy9vdx3ar51z4gv0x9i0p5cjv0-grep-3.11.nix).out} ${(import ../store/ix63qg734rsvk1jafvk2d9f83nhssk1a-patch-2.7.6.nix).out} ${(import ../store/sq6pj4hf188957l7vjnc38lavkpcj4pl-zstd-1.5.6.nix).out} ${(import ../store/zq2byd52990bdwcxjpgk1frry438wfrh-sed-4.9.nix).out} ${(import ../store/r0dwx6jdw0v7xbp5qszqp5f4q41mq9kp-libspectre-0.2.10.tar.gz.nix).out} ${(import ../store/mq36a6vmid855whv156dnrjd3s52dysk-findutils-4.10.0.nix).out} ${(import ../store/9c2qf69dhbrgpqx2a8ab46qphsgi110w-glibc-2.41.nix).static}";
}
