# Generated by guix-transfer
builtins.derivation {
  name = "rust-unicode-xid-0.2.6.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-68HATHFRDH9wK1K3w1BzTJ/xKVxGSgMzWwC7hPxU+FM=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-unicode-xid-0.2.6.tar.gz/sha256/0lzqaky89fq0bcrh6jj6bhlz37scfd8c7dsj5dq7y32if56c1hgb";
}
