# Generated by guix-transfer
builtins.derivation {
  name = "pciutils-3.13.0.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-d/EfeCmFAmNNGvUDCPFaV4hin2z0XLo3b1AJrqTLSSY=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/pciutils-3.13.0.tar.xz/sha256/09j9rfjaw2ahdwvvlp7ldjgn522pbbqhh0zm396n60l555w1zwbp";
}
