# Generated by guix-transfer
builtins.derivation {
  name = "docbook-xsl-1.79.2-0.fe16c90-checkout";
  system = "x86_64-linux";
  builder = "${import ../store/h6j68xwpj7dm4xbrkw5n28k434wlw0g0-guile-3.0.9.nix}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${../sources/zfz0k7p3wv8g31j0ycb3p9s75wpyq3jw-jsxgc979x79h81kzqz9n6cpf5pk4z262-module-import}"
    "-C"
    "${import ../store/li5xpkgwwawrqd9zkdzjlpincr26cmpg-module-import-compiled.nix}"
    "${../sources/5x8xv6gsnw9k18f6c8q9n1j9rr1cqcbk-docbook-xsl-1.79.2-0.fe16c90-checkout-builder}"
  ];
  "guix properties" = "((type . origin) (patches . 0))";
  __phantom_deps = "${import ../store/3zf89k72g49r6mq6pp3n5r2025w3mjs5-docbook-xsl-1.79.2-0.fe16c90-checkout.nix} 94797xsj3sc5axm2x6b2d3yfm2g5ix4a-patch-2.7.6 cccmzmbcx20w2swy810kqw3hib4xnpas-xz-5.4.5 icvmyhfsj88iypsz71cj4jdvrkc9wa7y-zstd-1.5.2 mr042cl0rzl2gvy4k4in86qb4hs5svwf-tar-1.34";
}
