# Generated by guix-transfer
builtins.derivation {
  name = "docbook-xsl-1.79.2-0.fe16c90-checkout";
  system = "x86_64-linux";
  builder = "${(import ../store/pq24yb7jw5rqgccsssvkk9n4lj9m1ri3-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/66alicjhn34r3fdisxzh1xvlkfhvllm9-module-import-compiled.nix).out}"
    "${builtins.path { name = ''docbook-xsl-1.79.2-0.fe16c90-checkout-builder''; path = ./../sources/pn975m2cxaza77mpgbkf1wgyy1g5q8yc-docbook-xsl-1.79.2-0.fe16c90-checkout-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "docbook-xsl-1.79.2-0.fe16c90-checkout-builder"; path = ./../sources/pn975m2cxaza77mpgbkf1wgyy1g5q8yc-docbook-xsl-1.79.2-0.fe16c90-checkout-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 0))";
  __phantom_deps = "${(import ../store/gyhiimwajbnkd9myji0qfi40jhy7w9y2-xz-5.4.5.nix).out} ${(import ../store/bj8pzxaby4mj5rh3dfd6km9wn8pnq99y-docbook-xsl-1.79.2-0.fe16c90-checkout.nix).out} ${(import ../store/vpi87n22f8dbhvbwaqr470xp83hnbf1y-tar-1.35.nix).out} ${(import ../store/759rgw9c7j48gb1bv5fgr2sb3d9f5p1v-patch-2.7.6.nix).out} ${(import ../store/r2mqn9i7k9h1xzrx3jbihckz3lhymvpv-zstd-1.5.6.nix).out}";
}
