# Generated by guix-transfer
builtins.derivation {
  name = "avahi-0.8.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-BgMJ16Mz042VG8J1mMZ3rxeWk029mOECTnrY3nmP7do=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/avahi-0.8.tar.gz/sha256/1npdixwxxn3s9q1f365x9n9rc5xgfz39hxf23faqvlrklgbhj0q6";
}
