# Generated by guix-transfer
builtins.derivation {
  name = "at-spi2-core-2.52.0.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-CsP8gyDI0B+hR8Jyun+gOAY4nGsD08QG0II+MONf9as=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/at-spi2-core-2.52.0.tar.xz/sha256/1azmbzik0gl2s03c9lq3dff3h1iql1zvlwn28yhizl68421zrhqa";
}
