# Generated by guix-transfer
builtins.derivation {
  name = "Python-3.11.14.tar.xz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-jT7Y7FyIwclfXlWGEqclRQ0kUoE92tXlj9saU7Egm3g=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://www.python.org/ftp/python/3.11.14/Python-3.11.14.tar.xz";
}
