# Generated by guix-transfer
builtins.derivation {
  name = "python-httptools-0.6.4-checkout";
  system = "x86_64-linux";
  builder = "builtin:git-download";
  outputHash = "sha256-7HN4yKBdxYPHSrpMKOP66w5JJ27PSLfBT1BUKs9R+hc=";
  outputHashAlgo = "sha256";
  outputHashMode = "recursive";
  commit = "v0.6.4";
  impureEnvVars = "http_proxy https_proxy LC_ALL LC_MESSAGES LANG COLUMNS";
  preferLocalBuild = "1";
  "recursive?" = "#f";
  url = "\"https://github.com/MagicStack/httptools\"";
}
