# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://github.com/seagle0128/doom-modeline"; rev = "v4.2.1"; hash = "sha256-68Dln0FIMmEHvIP8uzDLR24Ccfv4RmCulIt0fYKoEuw="; name = "emacs-doom-modeline-4.2.1-checkout"; fetchSubmodules = false; }
