# Generated by guix-transfer
builtins.derivation {
  name = "rust-pin-project-lite-0.2.16.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-Ozz/kivVFwm2Bdnq2apxAx2BRHFC2CjrSm66dv5hn5s=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/pin-project-lite/0.2.16/download";
}
