# Generated by guix-transfer
builtins.derivation {
  name = "texlive-atbegshi-2025.2-checkout";
  system = "x86_64-linux";
  builder = "${(import ../store/hn59viz2gmjdjjikmjmmlf5lnnp4wzn1-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import''; path = ./../sources/l9qrfq20vvrf1r54k0fr7xds1f9dlqmk-m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import; }}"
    "-L"
    "${(import ../store/0jgi9nl1jj70nqyv0xzwpismpd521g0m-guile-json-4.7.3.nix).out}/share/guile/site/3.0"
    "-L"
    "${(import ../store/1imj7rc51r305m25bchvqc9262c52rvq-guile-gnutls-5.0.1.nix).out}/share/guile/site/3.0"
    "-L"
    "${(import ../store/n2spw7akcvxnd9y7p9ardx3qp8g2kx1r-guile-lzlib-0.3.0.nix).out}/share/guile/site/3.0"
    "-C"
    "${(import ../store/kfffhpwx1daz8lq0x50siygzgb0h3p6b-module-import-compiled.nix).out}"
    "-C"
    "${(import ../store/0jgi9nl1jj70nqyv0xzwpismpd521g0m-guile-json-4.7.3.nix).out}/lib/guile/3.0/site-ccache"
    "-C"
    "${(import ../store/1imj7rc51r305m25bchvqc9262c52rvq-guile-gnutls-5.0.1.nix).out}/lib/guile/3.0/site-ccache"
    "-C"
    "${(import ../store/n2spw7akcvxnd9y7p9ardx3qp8g2kx1r-guile-lzlib-0.3.0.nix).out}/lib/guile/3.0/site-ccache"
    "${builtins.path { name = ''svn-multi-download''; path = ./../sources/sncvp7xxnhhxrzx5ysf4vipcgn96bplq-svn-multi-download; }}"
  ];
  srcs = [
    (builtins.path { name = "svn-multi-download"; path = ./../sources/sncvp7xxnhhxrzx5ysf4vipcgn96bplq-svn-multi-download; })
    (builtins.path { name = "m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import"; path = ./../sources/l9qrfq20vvrf1r54k0fr7xds1f9dlqmk-m92kyiz8sjx3xkr4plcsanfm47775m6h-module-import; })
  ];
  outputHash = "sha256-ydi3OXWOTRU2kBA4HofhsseXh66WqNnJI7xILhsHqW0=";
  outputHashAlgo = "sha256";
  outputHashMode = "recursive";
  hash = "201,216,183,57,117,142,77,21,54,144,16,56,30,135,225,178,199,151,135,174,150,168,217,201,35,188,72,46,27,7,169,109";
  impureEnvVars = "http_proxy https_proxy LC_ALL LC_MESSAGES LANG COLUMNS";
  preferLocalBuild = "1";
  "svn locations" = "(\"doc/latex/atbegshi/\" \"source/latex/atbegshi/\" \"tex/generic/atbegshi/\")";
  "svn revision" = "74725";
  "svn url" = "svn://www.tug.org/texlive/tags/texlive-2025.2/Master/texmf-dist";
  __phantom_deps = "${(import ../store/1imj7rc51r305m25bchvqc9262c52rvq-guile-gnutls-5.0.1.nix).debug} ${(import ../store/48dacb0ailv8r7zg91m2w5nh9ddw9pjb-gzip-1.14.nix).out} ${(import ../store/47vrqp50amqr5vzf2nhirb6m7pzjz898-tar-1.35.nix).out} ${(import ../store/z2yd2f58hspdpipsa4rw1yx49xnx3kwx-subversion-1.14.5.nix).out}";
}
