# Generated by guix-transfer
builtins.derivation {
  name = "rust-wit-bindgen-rt-0.39.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-b0IyDmH+LP00NU7LWX+G9BNISnmLpEqMoRZcWNQtpsE=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-wit-bindgen-rt-0.39.0.tar.gz/sha256/1hd65pa5hp0nl664m94bg554h4zlhrzmkjsf6lsgsb7yc4734hkg";
}
