# Generated by guix-transfer (git source)
(import ../fetch-git.nix) { url = "https://github.com/protesilaos/modus-themes"; rev = "5.1.0"; hash = "sha256-TP1t8fKyc8M0CUixPH7bAJrtSRNcSjeIqXuuaUlfiqk="; name = "emacs-modus-themes-5.1.0-checkout"; fetchSubmodules = false; }
