# Generated by guix-transfer
builtins.derivation {
  name = "rust-wasm-bindgen-test-0.3.50.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-ZsjV4zyjttn6O0Z213TFd4Ax0npXjCsAf5Baz4FhUsM=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-wasm-bindgen-test-0.3.50.tar.gz/sha256/1hsjc60wynlhgw02p32pgb93303pqmsdfxj67gxdkdm37kixbj36";
}
