# Generated by guix-transfer
builtins.derivation {
  name = "rust-rayon-1.10.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-tBimAVRRDKGgAqdSypcUmE4h5CQegE0yVVJR+vi3j/o=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/rayon/1.10.0/download";
}
