# Generated by guix-transfer
builtins.derivation {
  name = "emacs-buttercup-1.38-checkout";
  system = "x86_64-linux";
  builder = "builtin:git-download";
  outputHash = "sha256-uDNLdTJfNYVFJq6oFH/QqLWEvomrtID60QtFXvLUyCY=";
  outputHashAlgo = "sha256";
  outputHashMode = "recursive";
  commit = "v1.38";
  impureEnvVars = "http_proxy https_proxy LC_ALL LC_MESSAGES LANG COLUMNS";
  preferLocalBuild = "1";
  "recursive?" = "#f";
  url = "\"https://github.com/jorgenschaefer/emacs-buttercup\"";
}
