# Generated by guix-transfer
builtins.derivation {
  name = "libunwind-1.5.0.tar.zst";
  system = "x86_64-linux";
  builder = "${(import ../store/hn59viz2gmjdjjikmjmmlf5lnnp4wzn1-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/nnjrv59xc0zvampmfnv1xac2gk3f8ffp-module-import-compiled.nix).out}"
    "${builtins.path { name = ''libunwind-1.5.0.tar.zst-builder''; path = ./../sources/m9iv580jpqk78c6d73ry04ig8vdvzyf8-libunwind-1.5.0.tar.zst-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "libunwind-1.5.0.tar.zst-builder"; path = ./../sources/m9iv580jpqk78c6d73ry04ig8vdvzyf8-libunwind-1.5.0.tar.zst-builder; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 3))";
  __phantom_deps = "${(import ../store/h9ys9ff47zjq8g6glpw9vckvjszbid19-xz-5.4.5.nix).out} ${(import ../store/xdhd9k0narw3a72pspxgm0hgdww3a4x0-gzip-1.14.nix).out} ${(import ../store/3rlp7cr36snabnbv11ih55b7bs7k4is0-libunwind-prefer-extbl.nix).out} ${(import ../store/6mcsn3vji1fs82g0jlksppd7nwiyzk0x-tar-1.35.nix).out} ${(import ../store/5gwd67p6kfpbn2hd07igkbsrfs7qj6rr-libunwind-static-arm.nix).out} ${(import ../store/ix63qg734rsvk1jafvk2d9f83nhssk1a-patch-2.7.6.nix).out} ${(import ../store/yb1sws411b1zwr1rs7gdfk7la4crdj78-libunwind-1.5.0.tar.gz.nix).out} ${(import ../store/sq6pj4hf188957l7vjnc38lavkpcj4pl-zstd-1.5.6.nix).out} ${(import ../store/gm88z5skfkkwv9pi15y13rfr12ajw1ma-libunwind-cfa-rsp.nix).out}";
}
