# Generated by guix-transfer
builtins.derivation {
  name = "rust-cstr-0.2.12.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-aFI5A8iuWqz6MqDZrmDK3rdk4doU7g0msfMInxOlRjY=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://crates.io/api/v1/crates/cstr/0.2.12/download";
}
