# Generated by guix-transfer
builtins.derivation {
  name = "gitpython-3.1.44.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-yH4wsmJTv1QYsBsGYPgYln88UDGTg4M3/l5XMzEkkmk=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://files.pythonhosted.org/packages/source/g/gitpython/gitpython-3.1.44.tar.gz";
}
