# Generated by guix-transfer
builtins.derivation {
  name = "rust-windows-sys-0.48.0.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-Z30kGL7GXjM47bB26Aa8HsFWk8XQEEaD8u/oV/YQVqk=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-windows-sys-0.48.0.tar.gz/sha256/1aan23v5gs7gya1lc46hqn9mdh8yph3fhxmhxlw36pn6pqc28zb7";
}
