# Generated by guix-transfer
builtins.derivation {
  name = "rust-approx-0.5.1.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-yrES8KhtVo6g5ifMHWvnSh6c1VIUaE21VhmV9trYl8Y=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-approx-0.5.1.tar.gz/sha256/1ilpv3dgd58rasslss0labarq7jawxmivk17wsh8wmkdm3q15cfa";
}
