# Generated by guix-transfer
builtins.derivation {
  name = "mesboot-headers-0.25.1";
  system = "x86_64-linux";
  builder = "${(import ../store/3sgvmyxar0bp0r707sgivngr256jlw8k-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import''; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; }}"
    "-C"
    "${(import ../store/f1pxw9ip8s5g4ka338rz03kza9ip49mz-module-import-compiled.nix).out}"
    "${builtins.path { name = ''mesboot-headers-0.25.1-builder''; path = ./../sources/m3n4aq3nxgsdi42wmvkwpai7p108bx23-mesboot-headers-0.25.1-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import"; path = ./../sources/k56b2j5jn6d1k7rqc03fmaxfz9ibwi5m-0r7lmmb9x0rp855mjvhlk2303pgq99a4-module-import; })
    (builtins.path { name = "mesboot-headers-0.25.1-builder"; path = ./../sources/m3n4aq3nxgsdi42wmvkwpai7p108bx23-mesboot-headers-0.25.1-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/93rr879k35px3q16f39vpj0qs6rpggbh-mes-0.25.1.tar.gz.nix).out} ${(import ../store/8rv9mzd7xa1z60yfgk761gms254m2ff1-tcc-boot-0.9.27.nix).out} ${(import ../store/j785pn7gg6dhcm2wka5cdlijapvfrn1p-linux-libre-headers-bootstrap-0.nix).out} ${(import ../store/lr9ya21fn56knxaamc7wqds2c4valcfb-patch-mesboot-2.5.9.nix).out} ${(import ../store/xmhwxb82l5x07947k7caihxaxn0ai41x-gash-utils-boot-0.2.0.nix).out} ${(import ../store/fjmvzg51h4pk1ql93kknpf6f9hvvil5b-bootar-1b.nix).out} ${(import ../store/c9n5dmp7pndq3pj74194r5v6c8zq2k7h-make-mesboot0-3.80.nix).out} ${(import ../store/gvvzwfdbb0nqnzj2knggj53cxqhc9fsn-gzip-mesboot-1.2.4.nix).out} ${(import ../store/dgxgix2wsjrl9gbscq5p6sfkwzw0rlfp-gash-boot-0.3.1.nix).out}";
}
