# Generated by guix-transfer
builtins.derivation {
  name = "linux-libre-headers-bootstrap-0";
  system = "x86_64-linux";
  builder = "${(import ../store/8ldwd1vqvlrg2lvjxfyqm5lg0v2v0i76-guile-bootstrap-2.0.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/wn2s4pb2x5vf1g05a54v1l4laaycqpqd-module-import-compiled.nix).out}"
    "${builtins.path { name = ''linux-libre-headers-bootstrap-0-builder''; path = ./../sources/016ms4z2301gwygw9g8g83k3kad1mwh4-linux-libre-headers-bootstrap-0-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "linux-libre-headers-bootstrap-0-builder"; path = ./../sources/016ms4z2301gwygw9g8g83k3kad1mwh4-linux-libre-headers-bootstrap-0-builder; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/abh0fd8h5kqvjb21n6926c5z5i49fwbi-linux-libre-headers-stripped-4.14.67-i686-linux.tar.xz.nix).out} ${(import ../store/dnch4jwri4ha1j91jqc0y7pxb7ckr8cl-tar.nix).out} ${(import ../store/c6ykp9y27h9ilrwfkjb9knx3fy4zbb0s-xz.nix).out}";
}
