# Generated by guix-transfer
builtins.derivation {
  name = "rust-gif-0.13.1.tar.gz";
  system = "builtin";
  builder = "builtin:fetchurl";
  outputHash = "sha256-P7LWmxkhXhi7kS+jD3zhWEbjAUCGleRODvcZ8dqeGfI=";
  outputHashAlgo = "sha256";
  outputHashMode = "flat";
  url = "https://bordeaux.guix.gnu.org/file/rust-gif-0.13.1.tar.gz/sha256/1whrkvdg26gp1r7f95c6800y6ijqw5y0z8rgj6xihpi136dxdciz";
}
