# Generated by guix-transfer
builtins.derivation {
  name = "ld-wrapper-0";
  system = "x86_64-linux";
  builder = "${(import ../store/vihw99pskl1w6knya9dcvbacizccwdrd-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/facvks9qmjk78i76bjx7cjaajngr0ma8-module-import-compiled.nix).out}"
    "${builtins.path { name = ''ld-wrapper-0-builder''; path = ./../sources/137h1mxwr638q4ahbg00cc5xmmkcnq68-ld-wrapper-0-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "ld-wrapper-0-builder"; path = ./../sources/137h1mxwr638q4ahbg00cc5xmmkcnq68-ld-wrapper-0-builder; })
    (builtins.path { name = "ld-wrapper.in"; path = ./../sources/qsw2fycvyk1w029yn82ps1657h4cywcp-ld-wrapper.in; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
  ];
  LC_CTYPE = "C.UTF-8";
  __phantom_deps = "${(import ../store/5lpha1qgfgx8j6w16s8w1bqa5gks4kds-libunistring-1.3.nix).out} ${(import ../store/8apxp1kylcsgi99alzbffx5pf0x1zpnr-binutils-2.44.nix).out} ${(import ../store/ymhv06f7jzs799yvgpflmbkkkdvlk7kx-bash-minimal-5.2.37.nix).out} ${(import ../store/s1xnl78b5wzp7i6as2rqsr3v9rakv1n7-libgc-8.2.8.nix).out}";
}
