# Generated by guix-transfer
builtins.derivation {
  name = "tbb-2021.6.0-checkout";
  system = "x86_64-linux";
  builder = "${(import ../store/c4ay50vfyk7bxiiy4gzz8wp6d6b9qfay-guile-3.0.9.nix).out}/bin/guile";
  args = [
    "--no-auto-compile"
    "-L"
    "${builtins.path { name = ''c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import''; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; }}"
    "-C"
    "${(import ../store/7skwz4rdpxxc3s03vb07mqvpxr8s6j1h-module-import-compiled.nix).out}"
    "${builtins.path { name = ''tbb-2021.6.0-checkout-builder''; path = ./../sources/g0zz6q90b2mw04gxvd68mbszlqn8bpmq-tbb-2021.6.0-checkout-builder; }}"
  ];
  srcs = [
    (builtins.path { name = "tbb-2021.6.0-checkout-builder"; path = ./../sources/g0zz6q90b2mw04gxvd68mbszlqn8bpmq-tbb-2021.6.0-checkout-builder; })
    (builtins.path { name = "c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import"; path = ./../sources/08b1sz1fmgm1mgcxayrfam3xkls6w4wd-c6cf35bavqqs5mqsffl45izqaf0qn4dg-module-import; })
    (builtins.path { name = "tbb-gcc-14.patch"; path = ./../sources/vnxgaixv65bkj1a0v9vvsncl1qg47y0l-tbb-gcc-14.patch; })
    (builtins.path { name = "tbb-other-arches.patch"; path = ./../sources/q6z6n7vnix60z49hkhhf1kwkh9w4v2jg-tbb-other-arches.patch; })
  ];
  LC_CTYPE = "C.UTF-8";
  "guix properties" = "((type . origin) (patches . 2))";
  __phantom_deps = "${(import ../store/3f5ch18ghnzfbkk1iv2rk12j6n37lp51-xz-5.4.5.nix).out} ${(import ../store/5wg7ymdizf0fi7k7rzl0m06a0wicz628-tbb-2021.6.0-checkout.nix).out} ${(import ../store/fhskwarrjxl0726s5svlyqabd7i3ipy2-tar-1.35.nix).out} ${(import ../store/bs5jzy6r2zfk2hn9g21h7biwssm56266-patch-2.7.6.nix).out} ${(import ../store/j62jcz2m4jjnvv3z42mdxvs73xp8d95s-zstd-1.5.6.nix).out}";
}
