{
  description = "GuixPkgs: Guix packages via Nix";

  nixConfig = {
    extra-substituters = [ "https://guixpkgs.cachix.org" ];
    extra-trusted-public-keys = [ "guixpkgs.cachix.org-1:rM4xwCs5NUy+FcCKkiWP/CmRaSVxxDPaKWZvM1bRopg=" ];
  };

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    guix-src = {
      url = "git+https://codeberg.org/guix/guix.git?ref=version-1.5.0&shallow=1";
      flake = false;
    };
    guix-transfer.url = "github:fzakaria/guix-transfer";
  };

  outputs = { self, nixpkgs, guix-src, guix-transfer }:
  let
    system = "x86_64-linux";
    pkgs = nixpkgs.legacyPackages.${system};
    lib = pkgs.lib;

    # Lazily load all by-name packages. Generated by-name files may be plain
    # translated derivations (old syncs) or wrapper functions (new syncs).
    readByName = dir:
      let
        loadPackage = path:
          let value = import path;
          in if lib.isFunction value then value { inherit pkgs; } else value;
        letters = builtins.readDir dir;
        loadLetter = letter: type:
          if type == "directory" then
            lib.mapAttrs'
              (fn: _: lib.nameValuePair (lib.removeSuffix ".nix" fn)
                        (loadPackage (dir + "/${letter}/${fn}")))
              (lib.filterAttrs (n: _: lib.hasSuffix ".nix" n)
                (builtins.readDir (dir + "/${letter}")))
          else {};
      in
        lib.foldl' (a: b: a // b) {} (lib.mapAttrsToList loadLetter letters);

    sync-script = pkgs.writeShellScriptBin "sync-guix" ''
      set -euo pipefail

      tmp=$(mktemp -d)
      trap 'rm -rf "$tmp"' EXIT

      echo "Fetching Guix package and runtime-env derivations..."
      cat > "$tmp/channels.scm" <<EOF
      (list (channel
              (name 'guix)
              (url "https://codeberg.org/guix/guix.git")
              (commit "${guix-src.rev}")
              (introduction
               (make-channel-introduction
                "9edb3f66fd807b096b48283debdcddccfea34bad"
                (openpgp-fingerprint
                 "BBB0 2DDF 2CEA F6A8 0D1D  E643 A2A0 6DF2 A33A 54FA")))))
      EOF

      # Use guix time-machine to decouple from the host's Guix version.
      guix time-machine -C "$tmp/channels.scm" -- repl ./get-all-derivations.scm > "$tmp/drv_mapping.txt"
      
      echo "Translating Guix package and runtime-env derivations to Nix expressions..."
      # --disable-tests: skip the gnu-build-system check phase at translation
      # time. Guix's bootstrap test suites probe the daemon sandbox and fail
      # under Nix; this must be done here because builders bake in absolute
      # dependency paths.
      awk -F '\t' '{ print $2; print $3 }' "$tmp/drv_mapping.txt" \
        | xargs ${guix-transfer.packages.${system}.default}/bin/guix-transfer --disable-tests --emit-nix-dir pkgs \
        > "$tmp/transfer_out.txt"

      awk 'NR % 2 == 1 { package = $0; next } { print package "\t" $0 }' \
        "$tmp/transfer_out.txt" > "$tmp/package_env_nix_drvs.txt"

      echo "Creating by-name wrappers..."
      mkdir -p pkgs/by-name
      rm -rf pkgs/by-name/*

      cut -f1 "$tmp/drv_mapping.txt" > "$tmp/names.txt"
      paste "$tmp/names.txt" "$tmp/package_env_nix_drvs.txt" > "$tmp/name_to_nix_drv.txt"

      while IFS=$'\t' read -r name package_nix_drv_path runtime_env_nix_drv_path; do
          if [ -n "$package_nix_drv_path" ] && [ -n "$runtime_env_nix_drv_path" ]; then
              package_nix_filename=$(basename "$package_nix_drv_path" | sed 's/\.drv$/.nix/')
              runtime_env_nix_filename=$(basename "$runtime_env_nix_drv_path" | sed 's/\.drv$/.nix/')
              if [ -f "pkgs/store/$package_nix_filename" ] && [ -f "pkgs/store/$runtime_env_nix_filename" ]; then
                  letter=$(echo "$name" | cut -c 1 | tr '[:upper:]' '[:lower:]')
                  mkdir -p "pkgs/by-name/$letter"
                  cat > "pkgs/by-name/$letter/$name.nix" <<EOF
      { pkgs }:
      import ../../wrap-guix-package.nix {
        inherit pkgs;
        package = import ../../store/$package_nix_filename;
        runtimeEnv = import ../../store/$runtime_env_nix_filename;
      }
      EOF
              fi
          fi
      done < "$tmp/name_to_nix_drv.txt"
      
      echo "Writing channel metadata..."
      echo "{ \"channel\": \"guix\", \"commit\": \"${guix-src.rev}\", \"timestamp\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\" }" > guix-metadata.json
      
      echo "Done! IMPORTANT: Run 'git add pkgs/' so Nix can see the newly generated files!"
    '';

  in {
    packages.${system} = if builtins.pathExists ./pkgs/by-name then readByName ./pkgs/by-name else {};

    apps.${system}.sync = {
      type = "app";
      program = "${sync-script}/bin/sync-guix";
    };
  };
}
