# Generated by guix-transfer. Fetcher for translated Guix git-fetch
# sources: pkgs.fetchgit reproduces Guix's git checkout exactly.
{ url, rev, hash, name, fetchSubmodules ? false }:
(import <nixpkgs> { system = "x86_64-linux"; }).fetchgit {
  inherit url rev hash name fetchSubmodules;
}
