name: Checks

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch: # Allow manual triggers

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GuixPkgs
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true

      - name: Check formatting (treefmt)
        run: nix build --print-build-logs .#checks.x86_64-linux.formatting
